/** @format */

export const enum AbilityFour {
  // Custom Abilities
  BonusSpellBook = "A006",
  BonusArmor = "Z001",
  BonusStats = "Z002",
  BonusDamage = "Z004",
  BonusLife = "Z006",
  BonusLifeRegeneration = "Z007",
  BonusLifeSteal = "Z008",
  BonusMana = "Z009",
  BonusManaRegen = "Z00A",
  BonusAttackSpeed = "Z00B",
  BonusMovementSpeed = "Z00C",
  BonusSightRange = "Z00D",

  Skills = "A01F",

  FelGrunt = "A03Z",
  FelGruntTransformed = "S003",
  FelOgre = "A047",
  FelOgreTransformed = "S004",
  FelWarlord = "A048",
  FelWarlordTransformed = "S006",
  FelWarlock = "A049",
  FelWarlockTransformed = "S005",

  // Footman
  FootmanCharge = "Afzy",
  Militia2Upgrade = "A045",
  Footman1Upgrade = "A051",
  Footman2Upgrade = "A03J",
  Captian1Upgrade = "A052",
  Captian2Upgrade = "A03K",

  // Aspects
  InfectAspect = "A05T",
  InfectAspectDummy = "A04B",

  InfernoAspect = "A025",

  // Mage Towers
  ManaTowerRestore = "A05L",
  ManaShieldTower = "A00H",
  ManaShardsTower = "A03D",
  ChainLightningTower = "A00I",
  ConeOfFireTower = "A05K",

  // Brawler Abilities
  Drain = "A01Y",
  BrawlerBloodlust = "A007",
  Warstomp = "A002",
  UnleashRage = "A029",

  // Mana Addict Abilities
  ManaShield = "A001",
  ManaBomb = "A03P",
  ManaExplosion = "A018",
  Mark = "A015",
  MarkedSoul = "A05V",
  ManaStorm = "A03S",
  ManaStormFeedback = "A05U",

  // Shift Master Abilities
  ShadeStrength = "A037",
  SwiftMoves = "A056",
  SwiftAttacks = "A030",
  MirrorSwitch = "A03U",
  Shift = "A03T",
  FallingStrike = "A059",
  FallingStrikeDummy = "A00F",
  ShadeStorm = "A03C",
  FelForm = "A02Y",

  // Tactician Abilities
  Inspire = "A042",
  InspireSpellBook = "A01J",
  InspireAttack = "A043",
  InspireDefence = "A04F",
  InspireHealth = "A01K",

  IronDefense = "A019",
  RaiseBanner = "A01I",
  TacticionAttack = "A01B",
  Bolster = "A01Z",

  AttackSpellBook = "A04L",
  AttackDamage = "A04X",
  AttackFocus = "A01E",
  AttackRage = "A01Q",
  AttackLoyalty = "A01C",

  // Time Mage Abilities
  ChronoAtrophy = "A04K",
  Decay = "A032",
  TimeTravel = "A04P",
  Paradox = "A04N",

  // Map Abilities
  AOEdamageupondeath = "Adda", // (Sapper)
  AbolishMagic = "Aadm",
  AbolishMagicCreep = "ACdm",
  AbsorbMana = "Aabs",
  AcidBomb = "ANab",
  AerialShackles = "Amls",
  AgilityBonusPlus1 = "AIa1",
  AgilityBonusPlus3 = "AIa3",
  AgilityBonusPlus4 = "AIa4",
  AgilityBonusPlus6 = "AIa6",
  AgilityModPlus2 = "AIgm",
  Ahrs = "Ahrs",
  AlchemistChemicalRage = "ANcr",
  AlchemistHealingSpray = "ANhs",
  AllPlus1 = "AIx1",
  AllPlus2 = "AIx2",
  AllPlus3 = "AIx3",
  AllPlus4 = "AIx4",
  AlliedBuilding = "Aall",
  AncestralSpirit = "Aast",
  AnimateDead = "ACad", // (Neutral Hostile)
  AnimateDead1 = "AUan",
  AnimateDeaditemspecial = "AInd",
  AntimagicShell = "ACam", // (Neutral Hostile)
  AntimagicShell1 = "Aams",
  AntimagicShieldAIxs = "AIxs",
  AntimagicShieldMatrix = "Aam2",
  Anwm = "Anwm",
  Aspx = "Aspx",
  Attack = "Aatk",
  AttackBonusAIt6 = "AIt6",
  AttackBonusAIt9 = "AIt9",
  AttackBonusAItc = "AItc",
  AttackBonusAItf = "AItf",
  AttackBonusPlus1 = "AItg",
  AttackBonusPlus10 = "AItn",
  AttackBonusPlus2 = "AIth",
  AttackBonusPlus4 = "AIti",
  AttackBonusPlus5 = "AItj",
  AttackBonusPlus7 = "AItk",
  AttackBonusPlus8 = "AItl",
  AttackSpeedIncrease = "AIsx",
  AttackSpeedIncreaseGreater = "AIs2",
  AttributeModifierSkill = "Aamk",
  AuraCommandCreep = "ACac",
  AuraPlagueAbomination = "Aap1",
  AuraPlagueCreep = "Aap3",
  AuraPlagueCreepNoDamage = "Aap4",
  AuraRegenerationStatue = "Aabr",
  Avatar = "AHav",
  AvengerForm = "Aave",
  AwakenHero = "Aawa",
  BallsofFire = "Abof",
  Banish = "AHbn",
  Bash = "AHbh",
  Bash1 = "ACbh",
  BashBeastmasterBear = "ANbh",
  Bashitem = "AIbx",
  BashmaulSPBearlevel3 = "ANb2",
  BattleRoar = "ANbr",
  BattleStations = "Abtl",
  BattlestationsChaos = "Sbtl",
  BearForm = "Abrf",
  BeastMasterStampede = "ANst",
  BeastMasterSummonBear = "ANsg",
  BeastMasterSummonHawk = "ANsw",
  BeastMasterSummonQuilbeast = "ANsq",
  BerserkerRage = "ACbr",
  BerserkerRage1 = "Absk",
  BerserkerUpgrade = "Sbsk",
  Bladestorm = "AOww",
  Blight = "Abli",
  BlightDispelLarge = "Abdl",
  BlightDispelSmall = "Abds",
  BlightGrowthLarge = "Abgl",
  BlightGrowthSmall = "Abgs",
  BlightPlacement = "Ablp",
  BlightedGoldMineAbility = "Abgm",
  Blizzard = "AHbz",
  Blizzard1 = "ACbz", // (Neutral Hostile)
  BloodMageFlameStrike = "AHfs",
  Bloodlust = "ACbl", // (Neutral Hostile)
  Bloodlust1 = "Ablo",
  BreathofFireCreep = "ACbc",
  BreathofFrostCreep = "ACbf",
  BrewmasterBreathofFire = "ANbf",
  BrewmasterDrunkenBrawler = "ANdb",
  BrewmasterDrunkenHaze = "ANdh",
  BrewmasterStormEarthandFire = "ANef",
  BrillianceAura = "AHab",
  BrillianceAura1 = "ACba", // (Neutral Hostile)
  BuildTinyCastle = "AIbl",
  BuildTinyGreatHall = "AIbg",
  BuildTinyScoutTower = "AIbt",
  Burrow = "Abur",
  BurrowDetectionFlyers = "Abdt",
  Burrowscarablvl2 = "Abu2",
  Burrowscarablvl3 = "Abu3",
  CallToArms = "Amic", // (Town Hall)
  CalltoArms = "Amil", // (Peasant)
  Cannibalize = "Acan",
  Cannibalizecreep = "ACcn",
  CargoHold = "Abun", // OrcBurrow
  CargoHold1 = "Acar",
  CargoHold2 = "Amtc",
  CargoHoldDeath = "Achd",
  CargoHoldMeatWagon = "Sch2",
  CargoHoldShip = "Sch5",
  CargoHoldTank = "Sch4",
  CargoHoldTransport = "Sch3",
  CarrionSwarm = "ACca", // (Neutral Hostile)
  CarrionSwarm1 = "AUcs",
  ChainLightning = "ACcl", // (Neutral Hostile)
  ChainLightning1 = "AOcl",
  Channel = "ANcl",
  Chaos = "Acha",
  ChaosCargoLoad = "Achl",
  ChaosGrom = "Sca6",
  ChaosGrunt = "Sca1",
  ChaosKodo = "Sca4",
  ChaosPeon = "Sca5",
  ChaosRaider = "Sca2",
  ChaosShaman = "Sca3",
  Charm = "ACch",
  CleavingAttack = "ACce",
  CloudofFog = "Aclf",
  CloudofFogItem = "AIfg",
  ColdArrows = "AHca", // (Sylvanas)
  ColdArrows1 = "ACcw", // (Neutral Hostile)
  CommandAura = "AOac",
  ControlMagic = "Acmg",
  CorporealForm = "Acpf",
  CorrosiveBreath = "Acor",
  CoupleInstantArcher = "Aco2",
  CoupleInstantHippogryph = "Aco3",
  CreateCorpse = "Agyd",
  Cripple = "Acri",
  Cripple1 = "Scri", // (Warlock)
  Cripplecreep = "ACcr",
  CriticalStrike = "ACct", // (Neutral Hostile)
  CriticalStrike1 = "AOcr",
  CrowForm = "Amrf",
  CrownofKingsAllPlus5 = "AIx5",
  CrushingWave = "ACcv",
  CryptLordCarrionScarabs = "AUcb",
  CryptLordImpale = "AUim",
  CryptLordLocustSwarm = "AUls",
  CryptLordSpikedCarapace = "AUts",
  Curse = "Acrs",
  Cursecreep = "ACcs",
  Cyclone = "SCc1", // (Cenarius)
  Cyclone1 = "Acyc",
  CycloneAIcy = "AIcy",
  Cyclonecreep = "ACcy",
  DarkConversion = "ANdc", // (Malganis)
  DarkConversionFast = "SNdc",
  DarkPortal = "ANdp", // (Archimonde)
  DarkRangerBlackArrow = "ANba",
  DarkRangerCharm = "ANch",
  DarkRangerDrain = "ANdr",
  DarkRitual = "AUdr",
  DarkSummoning = "AUmd", // Malganis
  DarkSummoning1 = "AUds", // (Tichondrius)
  DeathAndDecay = "SNdd", // (Neutral Hostile)
  DeathAndDecay1 = "AUdd",
  DeathCoil = "ACdc", // (Neutral Hostile)
  DeathCoil1 = "AUdc",
  DeathDamageAOEmine = "Amnx",
  DeathDamageAOEmineBIG = "Amnz",
  DeathPact = "AUdp",
  Decouple = "Adec",
  Defend = "Adef",
  DefendItem = "AIdd",
  DefenseBonusPlus1 = "AId1",
  DefenseBonusPlus2 = "AId2",
  DefenseBonusPlus3 = "AId3",
  DefenseBonusPlus4 = "AId4",
  DefenseBonusPlus5 = "AId5",
  DetectSentryWard = "Adt1",
  Detector = "Adet",
  Detonate = "Adtn",
  DevotionAura = "AHad",
  DevotionAura1 = "ACav",
  Devour = "ACdv",
  Devour1 = "Adev",
  DevourCargo = "Advc",
  DevourMagic = "Advm",
  DevourMagiccreep = "ACde",
  DiseaseCloud = "Aap2", // (Plague Ward)
  DiseaseCloud1 = "Aapl",
  DiseaseCloud2 = "Apts", // (Meat wagon)
  Disenchantold = "Adch",
  DispelMagic = "Adis",
  DispelMagic1 = "Adsm", // (Neutral Hostile)
  DivineShield = "AHds",
  DivineShield1 = "ACds", // (Neutral Hostile)
  DrainLifeCreep = "ACdr",
  DropCorpse = "Amed",
  DropPilot = "Atdp",
  DustofAppearance = "AItb",
  Earthquake = "SNeq", // (Neutral Hostile)
  Earthquake1 = "AOeq",
  EatTree = "Aeat",
  ElunesGrace = "Aegr",
  EnduranceAura = "SCae", // (Neutral Hostile)
  EnduranceAura1 = "AOae",
  Ensnare = "ACen", // (Neutral Hostile)
  Ensnare1 = "Aens",
  EntangleGoldMine = "Aent",
  EntangledGoldMineAbility = "Aegm",
  EntanglingRoots = "Aenr", // (Neutral Hostile)
  EntanglingRoots1 = "AEer",
  EntanglingSeaweed = "Aenw",
  EnvenomedSpears = "Aven",
  EnvenomedWeapons = "ACvs", // (Neutral Hostile)
  EtherealForm = "Aetf",
  Evasion = "ACev", // (Neutral Hostile)
  Evasion1 = "ACes", // (Neutral Hostile 100%)
  Evasion2 = "AEev",
  Evasion3 = "AIev",
  EvilIllidanMetamorphosis = "AEvi",
  ExchangeGoldforLumber = "ANgl",
  ExchangeLumberforGold = "ANlg",
  Exhume = "Aexh",
  ExperienceModgreater = "AIe2",
  Factory = "ANfy",
  FaerieFire = "Afae",
  FaerieFireAfa2 = "Afa2",
  FaerieFirecreep = "ACff",
  FarSight = "AOfs",
  Feedback = "Afbk",
  FeedbackArcaneTower = "Afbt",
  FeedbackSpiritBeast = "Afbb",
  FeralSpirit = "ACsf", // (Neutral Hostile)
  FeralSpirit1 = "ACs9", // (Neutral Hostile, Pig)
  FeralSpirit2 = "AOsf",
  FigurineIceRevenant = "AIir",
  FigurineUrsaWarrior = "AIuw",
  FingerofDeath = "ANfd", // (Archimonde)
  Firebolt = "ANfb", // (Neutral Hostile)
  Firebolt1 = "ACfb", // (Neutral Hostile)
  Firebolt2 = "Awfb", // (Warlock)
  FirelordIncinerate = "ANic",
  FlakCannon = "Aflk",
  FlameStrikeCreep = "ACfs",
  Flare = "Afla",
  FlareGun = "AIfa",
  ForceofNature = "ACfr", // (Neutral Hostile)
  ForceofNature1 = "AEfn",
  FortificationGlyph = "AIgf",
  FragShards = "Afsh",
  FreezingBreath = "Afrz",
  Frenzy = "Afzy",
  FrostArmor = "ACfa", // (Neutral Hostile)
  FrostArmor1 = "AUfa",
  FrostBolt = "ACcb",
  FrostBreath = "Afrb",
  FrostNova = "ACfn", // (Neutral Hostile)
  FrostNova1 = "AUfn",
  Gather = "Awha", // (Wisp Gold and Lumber)
  Gather1 = "Awh2", // (Wisp Gold and Lumber - Ancient spirits)
  Gather2 = "Aaha", // (Acolyte Gold)
  GetCorpse = "Amel",
  Ghost = "Agho",
  GhostVisible = "Aeth",
  GiveGold = "AIgo",
  GiveLumber = "AIlu",
  GoldMineability = "Agld",
  GrabTree = "Agra",
  GyrocopterBombs = "Agyb",
  HardenedSkin = "Assk",
  Harvest = "Ahar", // (Gold and Lumber)
  Harvest1 = "Ahrl", // (Ghouls Lumber)
  Harvest2 = "Ahr3", // (Goblin Shredders lumber)
  HarvestLumberArchimondeghouls = "Ahr2",
  Heal = "Ahea",
  Heal1 = "Anhe",
  Heal2 = "Awhe",
  HealCreepHigh = "Anh2",
  HealCreepNormal = "Anh1",
  HealingWard = "AChw", // (Neutral Hostile)
  HealingWard1 = "Ahwd", // (Witch Doctor)
  HealingWardAIhw = "AIhw",
  HealingWardAura = "Aoar", // (Healing Ward)
  HealingWaveCreep = "AChv",
  HexCreep = "AChx",
  HolyLight = "AHhb",
  HumanBuild = "AHbu",
  HurlBoulder = "ACtb",
  Immolation = "ACim", // (Neutral Hostile)
  Immolation1 = "AEim",
  ImpaleCreep = "ACmp",
  ImpalingBolt = "Aimp",
  Inferno = "SNin", // (Tichondrius)
  Inferno1 = "ANin", // (Neutral Hostile)
  Inferno2 = "AUin",
  InnerFire = "Ainf",
  InnerFireCreep = "ACif",
  IntelligenceBonusPlus1 = "AIi1",
  IntelligenceBonusPlus3 = "AIi3",
  IntelligenceBonusPlus4 = "AIi4",
  IntelligenceBonusPlus6 = "AIi6",
  IntelligenceModPlus2 = "AItm",
  Inventory = "AInv",
  Inventory2slotunitUndead = "Aiun",
  InventoryPackMule = "Apak",
  Invisibility = "Aivs",
  Invulnerable = "Avul", // (Neutral)
  ItemAgilityGain = "AIam",
  ItemAnimateDead = "AIan",
  ItemAntiMagicShell = "Aami",
  ItemAreaDetection = "AIta",
  ItemAreaHealManaRegain = "AIra",
  ItemAreaHealing = "AIha",
  ItemAreaManaRegain = "AImr",
  ItemAreatreewalldamage = "AIdm",
  ItemArmorBonus = "AIde",
  ItemAttackDamageGain = "AIaa",
  ItemAttackFireBonus = "AIfb",
  ItemAttackFrostBonus = "AIob",
  ItemAttackLightningBonus = "AIlb",
  ItemAttackSpeedBonus = "AIas",
  ItemAuraBrilliance = "AIba",
  ItemAuraCommand = "AIcd",
  ItemAuraDevotion = "AIad",
  ItemAuraEndurance = "AIae",
  ItemAuraTrueshot = "AIar",
  ItemAuraUnholy = "AIau",
  ItemAuraVampiric = "AIav",
  ItemCaptureTheFlag = "AIfl",
  ItemCaptureTheFlag1 = "AIfm", // (Human)
  ItemCaptureTheFlag2 = "AIfn", // (Night elf)
  ItemCaptureTheFlag3 = "AIfo", // (Orc)
  ItemCaptureTheFlag4 = "AIfe", // (Undead)
  ItemChangeTOD = "AIct",
  ItemCommand = "AIco",
  ItemDamageBonus = "AIat",
  ItemDefenseAoePlusHealing = "AIdb",
  ItemDispel = "AIdi",
  ItemDispelAoeWithCooldown = "AIds",
  ItemDispelChain = "AIdc",
  ItemDoomGuardSummon = "AIfu",
  ItemExperienceGain = "AIem",
  ItemFelhoundSummon = "AIfh",
  ItemFirebolt = "AIfi",
  ItemFreezeDamageBonus = "AIzb",
  ItemFurbolgSummon = "AIff",
  ItemHealAoeGreater = "AIhb",
  ItemHealGreater = "AIh2",
  ItemHealLeast = "AIh3",
  ItemHealLesser = "AIh1",
  ItemHealManaRegain = "AIre",
  ItemHealing = "AIhe",
  ItemHeroStatBonus = "AIab",
  ItemIllusions = "AIil",
  ItemImmolation = "AIcf",
  ItemInferno = "AIin",
  ItemIntAgiStrgain = "AIxm",
  ItemIntelligenceGain = "AIim",
  ItemLevelGain = "AIlm",
  ItemLifeBonus = "AIml",
  ItemLifeGain = "AImi",
  ItemLifeRegeneration = "Arel",
  ItemLifeSteal = "AIva",
  ItemManaBonus = "AImm",
  ItemManaRegain = "AIma",
  ItemManaRegeneration = "AIrm",
  ItemManaRestoreGreater = "AIm2",
  ItemManaRestoreLesser = "AIm1",
  ItemMonsterLure = "AImo",
  ItemMoveSpeedBonus = "AIms",
  ItemPlaceGoblinLandMine = "AIpm",
  ItemPotionVampirism = "AIpv",
  ItemPurge = "AIlp",
  ItemRecall = "AIrt",
  ItemRedDrakeSummon = "AIfd",
  ItemRegenManalesser = "AIrn",
  ItemReincarnation = "AIrc",
  ItemResurrection = "AIrs",
  ItemRevealMap = "AIrv",
  ItemRockGolemSummon = "AIfr",
  ItemSightRangeBonus = "AIsi",
  ItemSkeletonSummon = "AIfs",
  ItemSoulPossession = "Asou",
  ItemSoulTheft = "AIso",
  ItemSpeedAoe = "AIsa",
  ItemStrengthGain = "AIsm",
  ItemTemporaryAreaArmorBonus = "AIda",
  ItemTemporaryInvisibility = "AIvi",
  ItemTemporaryInvulnerability = "AIvu",
  ItemTemporarySpeedBonus = "AIsp",
  ItemTownPortal = "AItp",
  ItemWeb = "AIwb",
  Kaboom = "Asds", // (Goblin Sapper)
  LichFrostArmorAutocast = "AUfu",
  LifeRegeneration = "ANrl",
  LifeRegenerationAura = "ACnr", // (Neutral)
  LightningAttack = "Alit",
  LightningShield = "Alsh",
  LightningShieldAIls = "AIls",
  LightningShieldcreep = "ACls",
  LiquidFire = "Aliq",
  Load = "Aloa", // (Goblin Zeppelin)
  Load1 = "Aenc",
  LoadBurrow = "Sloa",
  LoadNavies = "Slo3",
  LoadPilot = "Atlp",
  LoadWisp = "Slo2", // (Entangled Gold Mine)
  Locust = "Aloc", // Makes unit unselectable
  MagicDefense = "Amdf",
  MagicImmunityAImx = "AImx",
  MagicImmunityCreep = "ACmi",
  MagicSentry = "Adts", // (Human Towers)
  ManaBatteryObsidianStatue = "Amb2",
  ManaBurn = "Ambd",
  ManaBurn1 = "AEmb",
  ManaBurndemon = "Amnb",
  ManaFlare = "Amfl",
  ManaRegeneration = "ANre", // (Neutral)
  ManaRegenerationAura = "Aarm",
  ManaShieldCreep = "ACmf",
  ManaSteal = "Aste",
  MassTeleport = "AHmt",
  MaxLifeBonusGreater = "AIl2",
  MaxLifeBonusLeast = "AIlf",
  MaxLifeBonusLesser = "AIl1",
  MaxManaBonusLeast = "AImb",
  MaxManaBonusMost = "AIbm",
  MechanicalCritter = "Amec",
  Metamorphosis = "AEme",
  Metamorphosis1 = "AEIl", // (Illidan)
  MindRot = "ANmr",
  Mineexploding = "Amin", // (Goblin Land Mine)
  MirrorImage = "AOmi",
  Monsoon = "ANmo",
  Monsooncreep = "ACmo",
  MoonGlaive = "Amgl",
  MountHippogryph = "Acoa",
  Move = "Amov",
  NagaBuild = "AGbu",
  NeutralBuild = "ANbu",
  NeutralBuildinganyunit = "Ane2",
  NeutralSpell = "AAns",
  NeutralSpies = "Ansp",
  NightElfBuild = "AEbu",
  Nullroarsummoner = "Ahnl",
  OrbofAnnihilation = "Afak",
  OrbofCorruption = "AIcb",
  OrbofDarkness = "AIdf",
  OrbofDarknessBlackArrow = "ANbs",
  OrbofLightning = "AIll",
  OrbofSpells = "AIsb",
  OrbofVenom = "AIpb",
  OrbofVenomPoisonAttack = "Apo2",
  OrcBuild = "AObu",
  PIlotTankRifleman = "Stpr",
  Parasite = "ANpa",
  PermanentHitpointBonusfromchargeditem = "AImh",
  PermanentImmolation = "ANpi",
  PermanentImmolationflying = "Apmf",
  PermanentImmolationgraphic = "Apig",
  PermanentInvisibility = "Apiv",
  PhaseShift = "Apsh",
  Phoenix = "AHpx",
  Phoenix2 = "Aphx",
  PhoenixFire = "Apxf",
  PickupArcher = "Acoh",
  Pillage = "Asal",
  PilotTank = "Atpi",
  PilotTankMortarTeam = "Stpm",
  PitLordCleavingAttack = "ANca",
  PitLordDoom = "ANdo",
  PitLordHowlofTerror = "ANht",
  PoisonArrows = "AEpa",
  PoisonSting = "Apoi",
  Polymorph = "Aply",
  Polymorphcreep = "ACpy",
  Possession = "Apos",
  PossessionChanneling = "Aps2",
  Possessioncreep = "ACps",
  PotionofLifeRegen = "AIrl",
  PotionofManaRegengreater = "AIpr",
  PotionofManaRegenlesser = "AIpl",
  PotionofRejuvI = "AIp1",
  PotionofRejuvII = "AIp2",
  PotionofRejuvIII = "AIp3",
  PotionofRejuvIV = "AIp4",
  Preservation = "ANpr",
  Pulverize = "Awar",
  Pulverize1 = "ACpv", // (Neutral Hostile)
  Purge = "Aprg",
  PurgeApg2 = "Apg2",
  PurgeCreep = "ACpu",
  Purgeorb = "AIpg",
  RainofChaos = "ANrc", // (Archimonde)
  RainofFire = "ANrf", // (Neutral Hostile)
  RainofFire1 = "ACrf", // (Neutral Hostile)
  RaiseDead = "Arai",
  RaiseDeadCreep = "ACrd",
  RaiseDeadItem = "AIrd",
  RallyPoint = "ARal",
  RegenLifeArll = "Arll",
  Reincarnation = "ANrn", // (Mannoroth)
  Reincarnation1 = "ACrn", // (Neutral Hostile)
  Reincarnation2 = "AOre",
  Rejuvenation = "ACr2", // (Furbolg)
  Rejuvenation1 = "Arej",
  Rejuvinationcreep = "ACrj",
  ResistantSkin = "ACrk",
  Renew = "Aren",
  Repair = "Arep",
  RepairHuman = "Ahrp",
  ReplenishLife = "Arpl",
  ReplenishLifeMana = "Arpb",
  ReplenishMana = "Arpm",
  ReplenishManaandLife = "Ambt",
  Restore = "Arst",
  Resurrection = "AHre",
  Return111 = "Artn",
  ReturnGold = "Argd",
  ReturnGoldLumber = "Argl",
  ReturnLumber = "Arlm",
  Reveal = "Adta",
  Reveal1 = "Andt",
  Revenge = "Arng",
  ReviveHero = "Arev",
  RitualDaggerInstantHeal = "AIdg",
  RitualDaggerRegenerate = "AIg2",
  Roar = "Aroa",
  RoarAIrr = "AIrr",
  RoarAra2 = "Ara2",
  Roarcreep = "ACro",
  RoarcreepSkeletalOrc = "ACr1",
  RocketAttack = "Aroc",
  Root = "Aroo",
  RootAncientProtector = "Aro2",
  RootAncients = "Aro1",
  RunedBracers = "AIsr",
  RuneofGreaterResurrection = "APrr",
  RuneofLesserResurrection = "APrl",
  RuneofSpiritLink = "Aspp",
  Sacrifice = "Alam", // (Acolyte)
  Sacrifice1 = "Asac", // (Sacrificial Pit)
  Sanctuary = "ANsa",
  Scout = "AEst",
  ScrollofLifeRegen = "AIsl",
  ScrollofRejuvI = "AIp5",
  ScrollofRejuvII = "AIp6",
  SeaWitchForkedLightning = "ANfl",
  SeaWitchFrostArrows = "ANfa",
  SeaWitchManaShield = "ANms",
  SearingArrows = "ACsa", // (Neutral Hostile)
  SearingArrows1 = "AHfa",
  SelectHero = "Aneu",
  SelfDestruct2ClockwerkGoblins = "Asd2",
  SelfDestruct3ClockwerkGoblins = "Asd3",
  SelfDestructClockwerkGoblins = "Asdg",
  Sentinel = "Aesn",
  SentryWard = "Aeye",
  SentryWardAIsw = "AIsw",
  SerpentWardtentacleForgottenone = "ACtn",
  ShadowHunterHealingWave = "AOhw",
  ShadowHunterHex = "AOhx",
  ShadowHunterSerpentWard = "AOsw",
  ShadowHunterSerpentWard2 = "AOwd",
  ShadowMeld = "Ashm",
  ShadowMeldAkama = "Ahid",
  ShadowMeldInstant = "Sshm",
  ShadowStrike = "AEsh",
  ShadowStrikeCreep = "ACss",
  Shockwave = "ACsh", // (Neutral Hostile)
  Shockwave1 = "ACst", // (Trap)
  Shockwave2 = "AOsh",
  ShopPurchaseItem = "Apit",
  ShopSharingAlliedBldg = "Aall",
  Silence = "ANsi",
  SilenceCreep = "ACsi",
  SilenceItem = "AIse",
  SiphonMana = "AHdr",
  SiphonManaCreep = "ACsm",
  Slam = "ACtc", // (Neutral Hostile)
  Slam1 = "ACt2", // (Thunder Lizard)
  Sleep = "ACsp",
  Sleep1 = "ACsl", // (Neutral Hostile)
  Sleep2 = "AUsl",
  SleepAlways = "Asla",
  Slow = "Aslo",
  Slow1 = "ACsw", // (Neutral Hostile)
  SlowAIos = "AIos",
  SlowAura = "Aasl", // (Tornado)
  SlowPoison = "Aspo",
  SoulBurn = "ANso",
  SoulPreservation = "ANsl", // (Malganis)
  SpawnHydra = "Aspy",
  SpawnHydraHatchling = "Aspt",
  SpawnOnDeathskeleton = "Asod",
  SpawnSpiderlings = "Assp", // (Neutral Hostile)
  SpawnSpiders = "Aspd", // (Neutral Hostile)
  SpellBook = "Aspb",
  SpellImmunity = "ACm2", // (Archimonde)
  SpellImmunity1 = "ACm3", // (Dragon)
  SpellImmunity2 = "Amim",
  SpellShieldAOE = "ANse",
  SpiderAttack = "Aspa",
  SpikedBarricades = "Aspi",
  SpiritLink = "Aspl",
  Spy = "ANsp",
  StaffoTeleportation = "AImt",
  StandDown = "Astd",
  Starfall = "AEsf",
  Starfall1 = "AEsb", // (more powerful)
  StasisTrap = "Asta",
  StoneForm = "Astn",
  StormBolt = "AHtb",
  StormCrowForm = "Arav",
  StormHammers = "Asth",
  StrengthBonusPlus1 = "AIs1",
  StrengthBonusPlus3 = "AIs3",
  StrengthBonusPlus4 = "AIs4",
  StrengthBonusPlus6 = "AIs6",
  StrengthModPlus2 = "AInm",
  SubmergeMyrmidon = "Asb1",
  SubmergeRoyalGuard = "Asb2",
  SubmergeSnapDragon = "Asb3",
  SummonHeadhunteritem = "AIsh",
  SummonLavaSpawn = "ANlm",
  SummonSeaElemental = "ACwe",
  SummonWaterElemental = "AHwe",
  SunderingBlades = "Ahsb",
  TankUpgrade = "Srtt",
  Taunt = "Atau",
  Taunt1 = "ANta", // (Neutral Hostile)
  ThornsAura = "ACah", // (Neutral Hostile)
  ThornsAura1 = "AEah",
  ThornyShieldCreep = "ANth",
  ThunderClap = "AHtc",
  TinkererClusterRocketsLevel0 = "ANcs",
  TinkererClusterRocketsLevel1 = "ANc1",
  TinkererClusterRocketsLevel2 = "ANc2",
  TinkererClusterRocketsLevel3 = "ANc3",
  TinkererDemolishLevel0 = "ANde",
  TinkererDemolishLevel1 = "ANd1",
  TinkererDemolishLevel2 = "ANd2",
  TinkererDemolishLevel3 = "ANd3",
  TinkererEngineeringUpgrade = "ANeg",
  TinkererRoboGoblinLevel0 = "ANrg",
  TinkererRoboGoblinLevel1 = "ANg1",
  TinkererRoboGoblinLevel2 = "ANg2",
  TinkererRoboGoblinLevel3 = "ANg3",
  TinkererSummonFactoryLevel0 = "ANsy",
  TinkererSummonFactoryLevel1 = "ANs1",
  TinkererSummonFactoryLevel2 = "ANs2",
  TinkererSummonFactoryLevel3 = "ANs3",
  Tornado = "ANto",
  TornadoDamage = "Atdg",
  TornadoSpin = "Atsp",
  Tracking = "Anit",
  Tranquility = "AEtq",
  Transmute = "ANtm",
  TreeofLifeupgradeability = "Atol",
  TrueSight = "Agyv", // (Gyrocopter)
  TrueSight1 = "Adtg", // (Neutral)
  TrueSight2 = "Atru", // (Shade)
  TrueshotAura = "ACat", // (Neutral Hostile)
  TrueshotAura1 = "AEar",
  UltraVisionGlyph = "AIgu",
  Ultravision = "Ault",
  UndeadBuild = "AUbu",
  UnholyAura = "ACua", // (Neutral Hostile)
  UnholyAura1 = "AUau",
  UnholyFrenzy = "Auhf",
  UnholyFrenzy1 = "Suhf", // (Warlock)
  UnholyFrenzycreep = "ACuf",
  Unload = "Adro", // (Goblin Zeppelin)
  UnloadInstant = "Adri", // (Entangled Mine)
  UnstableConcoction = "Auco",
  Unsummon = "Buns",
  UnsummonBuilding = "Auns",
  VampiricAura = "ACvp", // (Neutral Hostile)
  VampiricAura1 = "AUav",
  Vampiricattack = "SCva",
  Vengeance = "Avng",
  Volcano = "ANvc",
  Wander = "Awan", // (Neutral)
  WarDrums = "Aakb",
  WarStomp = "Awrs", // (Neutral Hostile)
  WarStomp1 = "AOws",
  WarStomphydra = "Awrh",
  WarStompseagiant = "Awrg",
  WardenBlink = "AEbl",
  WardenFanofKnives = "AEfk",
  WardenSpiritofVengeance = "AEsv",
  WateryMinion = "ANwm",
  Waygateability = "Awrp",
  Web = "Aweb",
  Webcreep = "ACwb",
  WindWalk = "AOwk",
  WindWalk1 = "ANwk", // (Neutral Hostile)
}

export const enum BuffFour {
  // Custom
  ManaAddictSoulBind = "B00F",
  AttackUnit = "B006",
  Inspired = "B00I",
  Infected = "B00B",

  // Timed Generic Life
  TimedLifeGeneric = "BTLF",

  // Default
  AcidBomb = "BNab",
  AerialShackles = "Bmlt",
  AerialShacklesCaster = "Bmlc",
  AnimateDead = "BUan",
  AnimateDeadExtra = "BUad",
  AntiMagicShell = "Bams", // (Spell cannot target)
  AntiMagicShellExtra = "Bam2", // (Shell absord spell damage)
  AuraofBlight = "Babr",
  Avatar = "BHav",
  Banish = "BHbn",
  Barkskin = "Bbar",
  BattleRoar = "BNbr",
  Bear = "BNsg",
  Berserk = "Bbsk",
  BigBadVoodoo = "BOvd",
  BigBadVoodooCaster = "BOvc",
  BlackArrow = "BNba",
  BladestormCaster = "BOww",
  BlightEffect = "Xbli",
  Blizzard = "BHbd",
  BlizzardCaster = "BHbz",
  BlizzardEffect = "XHbz",
  Bloodlust = "Bblo",
  BreathofFire = "BNbf",
  BreathofFrost = "BCbf",
  BrillianceAura = "BHab",
  BuildingDamageHumanLarge = "Xfhl",
  BuildingDamageHumanMedium = "Xfhm",
  BuildingDamageHumanSmall = "Xfhs",
  BuildingDamageNightElfLarge = "Xfnl",
  BuildingDamageNightElfMedium = "Xfnm",
  BuildingDamageNightElfSmall = "Xfns",
  BuildingDamageOrcLarge = "Xfol",
  BuildingDamageOrcMedium = "Xfom",
  BuildingDamageOrcSmall = "Xfos",
  BuildingDamageUndeadLarge = "Xful",
  BuildingDamageUndeadMedium = "Xfum",
  BuildingDamageUndeadSmall = "Xfus",
  BurningOil = "Bbof",
  BurningOilEffect = "Xbof",
  CarrionBeetles = "BUcb",
  CarrionSwarmCaster = "BUcs",
  ChemicalRage = "BNcr",
  ClarityPotion = "BIrm",
  CloakofFlames = "BIcf",
  ClockwerkGoblin = "BNcg",
  Cloud = "Bclf",
  CloudEffect = "Xclf",
  ClusterRockets = "BNcs",
  ClusterRocketsEffect = "XNcs",
  ColdArrowsInfo = "Bcsi",
  ColdArrowsNonStacking = "BHca",
  ColdArrowsStacking = "Bcsd",
  CommandAura = "BOac",
  ControlMagic = "Bcmg",
  CorrosiveBreath = "Bcor",
  Corruption = "BIcb",
  Cripple = "Bcri",
  Curse = "Bcrs",
  Cyclone = "Bcyc",
  CycloneExtra = "Bcy2",
  DarkConversion = "BNdc",
  DarkMinion = "BNdm",
  DeathandDecay = "BUdd",
  DeathAndDecayEffect = "XUdd",
  DevotionAura = "BHad",
  Devour = "Bdvv",
  DevourCaster = "Bdig",
  Disease = "Bapl",
  DiseaseCloud = "Bplg",
  DivineShield = "BHds",
  Dizziness = "Bchd",
  Doom = "BNdo",
  DoomMinion = "BNdi",
  DrainLifeCaster = "Bdcl",
  DrainLifeManaCaster = "Bdcb",
  DrainLifeManaTarget = "Bdtb",
  DrainLifeTarget = "Bdtl",
  DrainManaCaster = "Bdcm",
  DrainManaTarget = "Bdtm",
  DrunkenHaze = "BNdh",
  DustofAppearance = "Bdet",
  Earthquake = "BOeq",
  EarthquakeCaster = "BOea",
  EarthquakeEffect = "XOeq",
  EatTree = "Beat",
  EnduranceAura = "BOae",
  EngineeringUpgrade = "BNeg",
  EnsnareAir = "Bena",
  EnsnareGeneral = "Bens",
  EnsnareGround = "Beng",
  EntanglingRoots = "BEer",
  EssenceofBlight = "Brpl",
  FaerieFire = "Bfae",
  FeralSpirit = "BOsf",
  FlameStrike = "BHfs",
  FlameStrikeEffect = "XHfs",
  FlareEffect = "Xfla",
  ForceofNature = "BEfn",
  Freeze = "Bfre",
  FreezingBreath = "Bfrz",
  Frenzy = "Bfzy",
  FrostArmor = "BUfa",
  Hawk = "BNsw",
  HeadhunterSpirit = "BIsh",
  Heal = "Bhea",
  HealingSpray = "BNhs",
  HealingSprayEffect = "XNhs",
  HealingWard = "Bhwd",
  HealingWardAura = "Boar",
  HealReduction = "BIhm",
  HeroDissipateEffect = "Xdis",
  Hex = "BOhx",
  HowlofTerror = "BNht",
  Illusion = "BIil",
  Immolation = "BEim",
  ImmolationCaster = "BEia",
  Impale = "BUim",
  Incinerate = "BNic",
  Infernal = "BNin",
  InnerFire = "Binf",
  Invisibility = "Binv",
  InvisibilityExtra = "Bivs",
  Invulnerable = "Bvul",
  ItemChangeTimeofDay = "XIct",
  ItemWeb = "BIwb",
  LavaSpawn = "BNlm",
  LightningShield = "Blsh",
  LightningShieldCaster = "Blsa",
  LiquidFire = "Bliq",
  ManaFlare = "Bmfl",
  ManaFlareExtra = "Bmfa",
  ManaRegenerationAura = "Barm",
  ManaShield = "BNms",
  MechanicalCritter = "Bmec",
  Metamorphosis = "BEme",
  Militia = "Bmil",
  MindRot = "BNmr",
  MirrorImage = "BOmi",
  Monsoon = "ANmd",
  MonsoonEffect = "XNmo",
  MonsterLure = "BImo",
  PandarenElemental = "BNef",
  Parasite = "BNpa",
  ParasiteMinion = "BNpm",
  PermanentImmolationGreen = "BNpi", // (Neutral Hostile 1)
  PermanentImmolationRed = "Bpig", // (Neutral Hostile 2)
  PhaseShift = "Bpsh",
  Phoenix = "Bphx",
  PhoenixFire = "Bpxf",
  PocketFactory = "BNfy",
  PoisonInfo = "Bpsi",
  PoisonNonStacking = "Bpoi",
  PoisonStacking = "Bpsd",
  Polymorph = "Bply",
  Possession = "Bpos",
  PossessionCaster = "Bpoc",
  Purge = "Bprg",
  Quilbeast = "BNsq",
  RainofChaosEffect = "XErc",
  RainofFire = "BNrd",
  RainofFireArea = "BNrf",
  RainofFireEffect = "XErf",
  Reborn = "BIrb",
  Regeneration = "BIrl",
  ReincarnationEffect = "XOre",
  Rejuvenation = "Brej",
  RejuvenationItem = "BIrg",
  Replenish = "Brpb",
  RevealEffect = "Xbdt",
  Roar = "Broa",
  Sanctuary = "BNsa",
  Scout = "BEst",
  ScrollofProtection = "Bdef",
  SentinelEffect = "Xesn",
  SentryWard = "Beye",
  ShadowStrike = "BEsh",
  SharedVision = "Bsha",
  ShockwaveCaster = "BOsh",
  Silence = "BNsi",
  SkeletalMinion = "Brai",
  Slam = "BCtc",
  Sleep = "BUsl",
  SleepPause = "BUsp",
  SleepStun = "BUst",
  Slow = "Bslo",
  Slowed = "Bfro",
  SlowPoisonInfo = "Bssi",
  SlowPoisonNonStacking = "Bspo",
  SlowPoisonStacking = "Bssd",
  SoulBurn = "BNso",
  SoulPreservation = "BNsl",
  SoulTheft = "BIsv",
  SpeedBonus = "Bspe",
  SpellShield = "BNss",
  Spiderling = "Bspa",
  SpikedCarapace = "BUts",
  SpiritLink = "Bspl",
  SpiritofVengeance = "Bvng",
  SpiritTouch = "Brpm",
  Stampede = "BNst",
  StarfallEffect = "XEsf",
  StarfallTarget = "AEsd",
  StasisTrap = "Bstt",
  Stunned = "BSTN",
  StunnedPause = "BPSE",
  SummonedUnit = "BFig",
  TeleportReveal = "Btrv",
  ThornsAura = "BEah",
  ThunderClap = "BHtc",
  TornadoDamage = "Btdg",
  TornadoSlowAura = "Basl",
  TornadoSpin = "Btsp",
  TornadoSpinArea = "Btsa",
  TornadoTimedLife = "BNto",
  TranquilityEffect = "XEtq",
  TranquilityTarget = "AEtr",
  Transmute = "BNtm",
  TrueshotAura = "BEar",
  Ultravision = "Bult",
  UnholyAura = "BUau",
  UnholyFrenzy = "Buhf",
  Unknown = "Bps1",
  Unsummon = "Buns",
  VampiricAura = "BUav",
  VampiricPotion = "BIpv",
  Vengeance = "BEsv",
  Volcano = "BNvc",
  VolcanoArea = "BNva",
  VolcanoEffect = "XNvc",
  WandofShadowsight = "Bshs",
  WarClub = "Bgra",
  Ward = "BOwd",
  WarDrums = "Bakb",
  WaterElemental = "BHwe",
  WateryMinion = "BNwm",
  WebAir = "Bwea",
  WebGround = "Bweb",
  WindWalk = "BOwk",
}

export const enum ItemFour {
  AlleriasFluteofAccuracy = "afac",
  AmuletofRecall = "amrc",
  AmuletofSpellShield = "spsh",
  AmuletoftheWild = "wild",
  AncestralStaff = "axas",
  AncientFigurine = "anfg",
  AncientJanggoofEndurance = "ajen",
  AnkhofReincarnation = "ankh",
  AntimagicPotion = "pams",
  ArcaneScroll = "arsc",
  ArcaniteShield = "arsh",
  AssassinsBlade = "asbl",
  BattleStandard = "btst",
  BeltofGiantStrength6 = "bgst",
  BladebaneArmor = "blba",
  BloodfeathersHeart = "bfhr",
  BloodKey = "kybl",
  BookoftheDead = "fgsk",
  BootsofQuelThalas6 = "belv",
  BootsofSpeed = "bspd",
  BracerofAgility = "brag",
  BundleofLumber = "lmbr",
  CelestialOrbofSouls = "cosl",
  Cheese = "ches",
  CircletofNobility = "cnob",
  ClarityPotion = "pclr",
  ClawsofAttack12 = "ratc",
  ClawsofAttack15 = "ratf",
  ClawsofAttack3 = "rat3",
  ClawsofAttack6 = "rat6",
  ClawsofAttack9 = "rat9",
  CloakofFlames = "clfm",
  CloakofShadows = "clsd",
  ClockworkPenguin = "stpg",
  CrownofKings5 = "ckng",
  CrownoftheDeathlord = "crdt",
  CrystalBall = "crys",
  DemonicFigurine = "fgdg",
  DiamondofSummoning = "dsum",
  DrektharsSpellbook = "dtsb",
  DruidPouch = "drph",
  DustofAppearance = "dust",
  EmptyVial = "bzbe",
  EnchantedGemstone = "engs",
  EnchantedShield = "shen",
  EnchantedVial = "envl",
  EssenceofAszune = "esaz",
  FirehandGauntlets = "frhg",
  FlareGun = "fgun",
  Frostguard = "frgd",
  FrostWyrmSkullShield = "fwss",
  FullVial = "bzbf",
  GauntletsofOgreStrength3 = "rst1",
  GemFragment = "gmfr",
  GemofTrueSeeing = "gemt",
  GerardsLostLedger = "ledg",
  GhostKey = "kygh",
  GlovesofHaste = "gcel",
  GlovesofSpellMastery = "gvsm",
  GlyphofFortification = "gfor",
  GlyphofOmniscience = "gomn",
  GlyphofPurification = "gopr",
  GlyphofUltravision = "guvi",
  GoblinLandMines = "gobm",
  GoblinNightScope = "tels",
  GoldCoins = "gold",
  GreaterReplenishmentPotion = "rej4",
  GreaterScrollofReplenishment = "rej6",
  GrimoireofSouls = "grsl",
  HealingSalve = "hslv",
  HealingWards = "whwd",
  HealthStone = "hlst",
  HeartofAszune = "azhr",
  HelmofBattlethirst = "hbth",
  HelmofValor = "hval",
  HoodofCunning = "hcun",
  HornofCenarius = "cnhn",
  HornoftheClouds = "sfog",
  HumanFlag = "flag",
  IceShard = "shar",
  InfernoStone = "infs",
  IronwoodBranch = "iwbr",
  IvoryTower = "tsct",
  JadeRing = "jdrn",
  KegofAle = "kgal",
  KegofThunderwater = "dkfw",
  KelensDaggerofEscape = "desc",
  KeyofThreeMoons = "k3m3",
  KhadgarsGemofHealth = "rhth",
  KhadgarsPipeofInsight = "kpin",
  Killmaim = "klmm",
  LegionDoomHorn = "lgdh",
  LesserClarityPotion = "plcl",
  LesserReplenishmentPotion = "rej2",
  LesserScrollofReplenishment = "rej5",
  LionsRing = "lnrn",
  MagicKeyChain = "mgtk",
  ManaStone = "mnst",
  MantleofIntelligence3 = "rin1",
  ManualofHealth = "manh",
  MaskofDeath = "modt",
  MaulofStrength = "mlst",
  MechanicalCritter = "mcri",
  MedallionofCourage = "mcou",
  Mindstaff = "mnsf",
  MinorReplenishmentPotion = "rej1",
  MogrinsReport = "mort",
  MonsterLure = "lure",
  Mooncrystal = "k3m1",
  MoonKey = "kymn",
  Moonstone = "moon",
  NecklaceofSpellImmunity = "nspi",
  NightElfFlag = "nflg",
  NotetoJainaProudmoore = "jpnt",
  OrbofCorruption = "ocor",
  OrbofDarkness = "odef",
  OrbofFire = "ofir",
  OrbofFireNew = "ofr2", // (Reduce Healing)
  OrbofFrost = "ofro",
  OrbofKiljaeden = "gldo",
  OrbofLightning = "olig",
  OrbofLightningNew = "oli2",
  OrbofSlow = "oslo",
  OrbofVenom = "oven",
  OrcFlag = "oflg",
  PartialKeyoftheThreeMoons = "k3m2",
  PendantofEnergy = "penr",
  PendantofMana = "pmna",
  PeriaptofVitality = "prvt",
  PhatLewt = "phlt",
  PotionofDivinity = "pdiv",
  PotionofGreaterHealing = "pghe",
  PotionofGreaterInvisibility = "pgin",
  PotionofGreaterMana = "pgma",
  PotionofHealing = "phea",
  PotionofInvisibility = "pinv",
  PotionofInvulnerability = "pnvu",
  PotionofLesserInvulnerability = "pnvl",
  PotionofMana = "pman",
  PotionofOmniscience = "pomn",
  PotionofRestoration = "pres",
  PotionofSpeed = "pspd",
  RedDrakeEgg = "fgrd",
  ReplenishmentPotion = "rej3",
  RingofProtection1 = "rde0",
  RingofProtection2 = "rde1",
  RingofProtection3 = "rde2",
  RingofProtection4 = "rde3",
  RingofProtection5 = "rde4",
  RingofRegeneration = "rlif",
  RingofSuperiority = "rnsp",
  RingoftheArchmagi1 = "ram1",
  RingoftheArchmagi2 = "ram2",
  RingoftheArchmagi3 = "ram3",
  RingoftheArchmagi4 = "ram4",
  RitualDagger = "ritd",
  RobeoftheMagi6 = "ciri",
  RodofNecromancy = "rnec",
  RunedBracers = "brac",
  RunedGauntlets = "rugt",
  RuneofDispelMagic = "rdis",
  RuneofGreaterHealing = "rhe3",
  RuneofGreaterMana = "rma2",
  RuneofGreaterResurrection = "rre2",
  RuneofHealing = "rhe2",
  RuneofLesserHealing = "rhe1",
  RuneofLesserResurrection = "rre1",
  RuneofMana = "rman",
  RuneofRebirth = "rreb",
  RuneofRestoration = "rres",
  RuneofShielding = "rsps",
  RuneofSpeed = "rspd",
  RuneofSpiritLink = "rspl",
  RuneoftheWatcher = "rwat",
  RustyMiningPick = "rump",
  SacredRelic = "horl",
  SacrificialSkull = "skul",
  ScepterofHealing = "schl",
  ScepterofMastery = "ccmd",
  ScepteroftheSea = "rots",
  ScourgeBoneChimes = "sbch",
  ScrollofAnimateDead = "sand",
  ScrollofHealing = "shea",
  ScrollofMana = "sman",
  ScrollofProtection = "spro",
  ScrollofRegeneration = "sreg",
  ScrollofRestoration = "sres",
  ScrollofResurrection = "srrc",
  ScrollofSpeed = "shas",
  ScrolloftheBeast = "sror",
  ScrolloftheUnholyLegion = "scul",
  ScrollofTownPortal = "stwp",
  SearingBlade = "srbd",
  SecretLevelPowerup = "sclp",
  SentryWards = "wswd",
  Serathil = "srtl",
  ShadowOrb1 = "sor1",
  ShadowOrb10 = "sora",
  ShadowOrb2 = "sor2",
  ShadowOrb3 = "sor3",
  ShadowOrb4 = "sor4",
  ShadowOrb5 = "sor5",
  ShadowOrb6 = "sor6",
  ShadowOrb7 = "sor7",
  ShadowOrb8 = "sor8",
  ShadowOrb9 = "sor9",
  ShadowOrbFragment = "sorf",
  ShamanClaws = "shcw",
  ShamanicTotem = "shtm",
  ShieldofHonor = "shhn",
  ShieldoftheDeathlord = "shdt",
  ShimmerglazeRoast = "shrs",
  Shimmerweed = "shwd",
  SkeletalArtifact = "skrt",
  SkullofGuldan = "glsk",
  SkullShield = "sksh",
  SlippersofAgility3 = "rag1",
  SobiMask = "rwiz",
  Soul = "soul",
  SoulGem = "gsou",
  SpellBook = "sbok",
  SpiderRing = "sprn",
  SpiderSilkBroach = "silk",
  SpikedCollar = "fgfh",
  StaffofNegation = "sneg",
  StaffofPreservation = "spre",
  StaffofReanimation = "stre",
  StaffofSanctuary = "ssan",
  StaffofSilence = "ssil",
  StaffofTeleportation = "stel",
  StoneToken = "fgrg",
  SturdyWarAxe = "stwa",
  SunKey = "kysn",
  TalismanofEvasion = "evtl",
  TalismanoftheWild = "totw",
  TheHeartofSearinox = "sehr",
  TheLionHornofStormwind = "lhst",
  ThunderbloomBulb = "dthb",
  ThunderlizardDiamond = "thdm",
  ThunderLizardEgg = "thle",
  ThunderPhoenixEgg = "dphe",
  TinyAltarofKings = "tbak",
  TinyBarracks = "tbar",
  TinyBlacksmith = "tbsm",
  TinyCastle = "tcas",
  TinyFarm = "tfar",
  TinyGreatHall = "tgrh",
  TinyLumberMill = "tlum",
  TomeofAgility = "tdex",
  TomeofAgility2 = "tdx2",
  TomeofExperience = "texp",
  TomeofGreaterExperience = "tgxp",
  TomeofIntelligence = "tint",
  TomeofIntelligence2 = "tin2",
  TomeofKnowledge = "tpow",
  TomeofPower = "tkno",
  TomeofRetraining = "tret",
  TomeofSacrifices = "tmsc",
  TomeofStrength = "tstr",
  TomeofStrength2 = "tst2",
  TotemofMight = "tmmt",
  UndeadFlag = "uflg",
  UrnofKingTerenas = "ktrm",
  VampiricPotion = "vamp",
  VoodooDoll = "vddl",
  WandofIllusion = "will",
  WandofLightningShield = "wlsd",
  WandofManaStealing = "woms",
  WandofNegation = "wneg",
  WandofNeutralization = "wneu",
  WandofShadowsight = "wshs",
  WandoftheWind = "wcyc",
  WarsongBattleDrums = "ward",
  WarsongBattleDrums2 = "war2", // (Rexxar campaign item)
  WirtsLeg = "wtlg",
  WirtsOtherLeg = "wolg",
}

export const enum DestructibleFour {
  MassiveRuinedGateVertical = "ZTsg",
  IcyGate = "ITg3",
  ElvenGate = "LTe3",
}

export const enum UnitFour {
  // Default Units
  Abomination = "uabo", // model: Abomination	 scale: 0,9	 selectScale: 2,1
  Abominationcinematic = "uabc", // model: AbominationCIN	 scale: 0,9	 selectScale: 2,1
  Acolyte = "uaco", // model: Acolyte
  Admiralproudmoore = "Hapm", // model: Proudmoore	 scale: 1,1	 selectScale: 1,1
  Airbarge = "uarb", // model: UndeadAirBarge	 selectScale: 2
  Akama = "Naka", // model: DranaiAkama	 scale: 1,5	 selectScale: 1,75
  Albatross = "nalb", // model: Albatross	 scale: 1,2	 selectScale: 0,8
  Alchemist = "Nalc", // model: HeroGoblinAlchemist	 selectScale: 2
  Alchemistmorph = "Nalm", // model: HeroGoblinAlchemist	 selectScale: 2
  Alchemistmorph2 = "Nal2", // model: HeroGoblinAlchemist	 selectScale: 2
  Alchemistmorph3 = "Nal3", // model: HeroGoblinAlchemist	 selectScale: 2
  Altarofdarkness = "uaod", // model: AltarOfDarkness	 selectScale: 4,25
  Altarofelders = "eate", // model: AltarOfElders	 selectScale: 4
  Altarofkings = "halt", // model: AltarofKings	 selectScale: 4
  Altarofstorms = "oalt", // model: AltarofStorms	 selectScale: 4,5
  Altarofthedepths = "nnad", // model: AltarOfDepths	 selectScale: 4
  Amphibioussheep = "nsha", // model: Sheep	 scale: 1,2	 selectScale: 0,9
  Ancienthydra = "nahy", // model: Hydra	 scale: 1,55	 selectScale: 3
  Ancientoflore = "eaoe", // model: AncientOfLore	 selectScale: 4
  Ancientofwar = "eaom", // model: AncientOfWar	 selectScale: 4
  Ancientofwind = "eaow", // model: AncientOfWind	 selectScale: 4
  Ancientofwonders = "eden", // model: AncientOfWonder	 selectScale: 4,5
  Ancientprotector = "etrp", // model: AncientProtector	 selectScale: 3
  Ancientsasquatch = "nsqa", // model: Sasquatch	 scale: 1,6	 selectScale: 1,45
  Ancientwendigo = "nwna", // model: Wendigo	 scale: 1,65	 selectScale: 1,5
  Antonidus = "Hant", // model: HeroArchMage	 selectScale: 1,5
  Anubarak = "Uanb", // model: Anubarak	 selectScale: 1,85
  Apprenticewizard = "nwiz", // model: HumanMage
  Arcaneobservatory = "haro", // model: ArcaneObservatory	 selectScale: 6,3
  Arcanesanctum = "hars", // model: ArcaneSanctum	 selectScale: 3,75
  Arcanevault = "hvlt", // model: ArcaneVault	 selectScale: 4,5
  Archer = "earc", // model: Archer
  Archimonde = "Uwar", // model: Warlock	 scale: 1,4	 selectScale: 2,1
  Archmage = "Hamg", // model: HeroArchMage	 selectScale: 1,5
  Arthas = "Hart", // model: Arthas	 scale: 1,1	 selectScale: 1,1
  Arthaswithfrostmourne = "Harf", // model: ArthaswithSword	 scale: 1,1	 selectScale: 1,1
  Assassin = "nass", // model: BanditSpearThrower	 scale: 1,3
  Azuredragon = "nadr", // model: AzureDragon	 scale: 1,75	 selectScale: 2,25
  Azuredragonwhelp = "nadw", // model: AzureDragonWelp	 scale: 0,7	 selectScale: 1,75
  Azuredrake = "nadk", // model: AzureDragon	 scale: 1,2	 selectScale: 2
  Azurelordfrostwyrm = "ubdd", // model: FrostWyrm	 scale: 2	 selectScale: 2,5
  Azureloredragon = "ubdr", // model: AzureDragon	 scale: 2,25	 selectScale: 2,7
  Balnazzar = "Ubal", // model: Tichondrius	 scale: 1,6	 selectScale: 1,9
  Bandit = "nban", // model: Bandit
  Banditlord = "nbld", // model: BanditLord	 scale: 1,3	 selectScale: 1,25
  Banshee = "uban", // model: Banshee
  Barbedarachnathid = "nanb", // model: Archnathid	 scale: 0,65	 selectScale: 1,4
  Barbedarachnathidburrowed = "nbnb", // model: Archnathid	 scale: 0,65	 selectScale: 1,4
  Barbedarachnathidmerc = "nanm", // model: Archnathid	 scale: 0,65	 selectScale: 1,4
  Barrowden = "nbwd", // model: BarrowDens	 selectScale: 4,2
  Battlegolem = "narg", // model: GolemStatue	 scale: 0,8	 selectScale: 1,5
  Battleship = "nbsp", // model: Battleship	 selectScale: 4
  Beastiary = "obea", // model: Beastiary	 selectScale: 4,5
  Beastmaster = "Nbst", // model: Beastmaster	 selectScale: 2
  Bereserkelemental = "nelb", // model: WaterElemental	 scale: 1,4	 selectScale: 1,6
  Berserker = "otbk", // model: HeadHunter	 scale: 1,15	 selectScale: 1,1
  Berserkowlbear = "nowk", // model: Owlbear	 scale: 1,6	 selectScale: 2,3
  Bindstonese = "nbse", // model: RessurectionStoneSE	 selectScale: 3,5
  Bindstonesw = "nbsw", // model: RessurectionStoneSW	 selectScale: 3,5
  Blackdragon = "nbwm", // model: BlackDragon	 scale: 1,75	 selectScale: 2,25
  Blackdragonroost = "ndrk", // model: DragonBuildingBlack	 scale: 1,5	 selectScale: 6,6
  Blackdragonwhelp = "nbdr", // model: BlackDragonWelp	 scale: 0,7	 selectScale: 1,75
  Blackdrake = "nbdk", // model: BlackDragon	 selectScale: 2
  Blackrockblademaster = "Nbbc", // model: HeroChaosBladeMaster	 selectScale: 1,15
  Blacksmith = "hbla", // model: Blacksmith	 selectScale: 4
  Blademaster = "Obla", // model: HeroBladeMaster	 selectScale: 1,25
  Bloodelfengineer = "nbee", // model: HighElfPeasant
  Bloodelflieutenant = "nbel", // model: BloodElfLieutenant	 selectScale: 1,2
  Bloodelfwagon = "hbew", // model: BloodElfWagon	 selectScale: 2,5
  Bloodelfworker = "nhew", // model: HighElfPeasant
  Bloodfiend = "nfgb", // model: Felgaurd	 scale: 1,35	 selectScale: 1,35
  Bloodfountain = "nbfl", // model: FountainOfLifeBlood	 selectScale: 5
  Bloodmage = "Hblm", // model: HeroBloodElf	 selectScale: 1,5
  Bluedragonroost = "ndru", // model: DragonBuildingBlue	 scale: 1,5	 selectScale: 6,6
  Bluedragonspawnapprentice = "nbda", // model: DragonSpawnGreen	 scale: 0,9	 selectScale: 1,8
  Bluedragonspawnmeddler = "nbdm", // model: DragonSpawnBlue	 scale: 0,9	 selectScale: 1,8
  Bluedragonspawnoverseer = "nbdo", // model: DragonSpawnBlue	 scale: 1,4	 selectScale: 2,5
  Bluedragonspawnsorceror = "nbds", // model: DragonSpawnGreen	 scale: 1,3	 selectScale: 2,4
  Bluedragonspawnwarrior = "nbdw", // model: DragonSpawnPurple	 scale: 1,15	 selectScale: 2,2
  Boneyard = "ubon", // model: BoneYard	 selectScale: 5
  Bookofsummoning = "nbsm", // model: BookOfSummoning	 selectScale: 2,5
  Bouldertower = "nbt1", // model: TowerDefenseTower	 selectScale: 2,5
  Bouldertowerupgrade = "nbt2", // model: TowerDefenseTower	 selectScale: 2,5
  Brigand = "nbrg", // model: BanditSpearThrower	 scale: 1,1
  Bronzedragon = "nbzd", // model: BronzeDragon	 scale: 1,75	 selectScale: 2,25
  Bronzedragonroost = "ndrz", // model: DragonRoost	 scale: 1,5	 selectScale: 6,6
  Bronzedragonwhelp = "nbzw", // model: BronzeDragonWelp	 scale: 0,7	 selectScale: 1,75
  Bronzedrake = "nbzk", // model: BronzeDragon	 scale: 1,2	 selectScale: 2
  Broodmother = "nsbm", // model: SpiderBlue	 scale: 1,5	 selectScale: 1,5
  Burningarcher = "nskf", // model: SkeletonArcher	 scale: 1,3
  Cairnebloodhoof = "Ocbh", // model: HeroTaurenChieftainCIN	 selectScale: 2
  Cairnebloodhoofcinematic = "Otcc", // model: HeroTaurenChieftainCIN	 selectScale: 2
  Cairnebloodhoofexp = "Ocb2", // model: HeroTaurenChieftainCIN	 selectScale: 2
  Campaignturtle = "nhyc", // model: DragonSeaTurtleRange	 scale: 0,8	 selectScale: 2,5
  Cannontower = "hctw", // model: HumanTower	 selectScale: 2,5
  Cantina = "ntav", // model: Tavern	 selectScale: 6
  Carrionscarab1 = "ucs1", // model: scarab	 scale: 0,9	 selectScale: 1,25
  Carrionscarab2 = "ucs2", // model: scarab	 scale: 1,1	 selectScale: 1,5
  Carrionscarab3 = "ucs3", // model: scarab	 scale: 1,3	 selectScale: 1,75
  Carrionscarabburrowed2 = "ucsB", // model: scarab	 scale: 1,1	 selectScale: 1,5
  Carrionscarabburrowed3 = "ucsC", // model: scarab	 scale: 1,3	 selectScale: 1,75
  Castle = "hcas", // model: TownHall	 selectScale: 6,3
  Cenarius = "Ecen", // model: HeroKeeperoftheGrove	 scale: 1,4	 selectScale: 3
  Centaurarcher = "ncea", // model: CentaurArcher	 selectScale: 1,25
  Centaurdrudge = "ncer", // model: Centaur	 scale: 1,1
  Centaurimpaler = "ncim", // model: CentaurArcher	 scale: 1,35	 selectScale: 1,25
  Centaurkhan = "ncnk", // model: CentaurKhan	 scale: 1,75	 selectScale: 1,85
  Centauroutrunner = "ncen", // model: Centaur	 scale: 1,45	 selectScale: 1,25
  Centaursorceror = "ncks", // model: CentaurKhan	 scale: 1,3	 selectScale: 1,4
  Centaurtent = "ncnt", // model: CentaurTent	 selectScale: 3,5
  Centaurtent1 = "nct1", // model: CentaurTent1	 selectScale: 3,5
  Centaurtent2 = "nct2", // model: CentaurTent2	 selectScale: 3,5
  Chaosgrunt = "nchg", // model: ChaosGrunt	 scale: 1,2
  Chaoskotobeast = "nckb", // model: ChaosKotoBeast	 selectScale: 2,25
  Chaosorcburrow = "ocbw", // model: TrollBurrow	 selectScale: 2,75
  Chaospeon = "ncpn", // model: ChaosPeon
  Chaosspaceorc = "zcso", // model: ChaosSpaceOrc
  Chaoswarlock = "nchw", // model: ChaosWarlock	 selectScale: 1,15
  Chaoswarlord = "owar", // model: ChaosWarlord
  Chaoswolfrider = "nchr", // model: ChaosWolfRider	 scale: 1,2	 selectScale: 1,6
  Chaplain = "nchp", // model: HumanMage
  Chicken = "nech", // model: EasterChicken	 selectScale: 0,9
  Chieftainhut = "ndch", // model: ChieftainHut	 selectScale: 2,5
  Chimaera = "echm", // model: Chimaera	 selectScale: 2
  Chimaeraroost = "edos", // model: ChimaeraRoost	 selectScale: 4
  Circleofpower = "ncop", // model: CircleOfPower	 selectScale: 3,5
  Circleofpowerlarge = "ncp3", // model: CircleOfPower	 scale: 2	 selectScale: 4,5
  Circleofpowermedium = "ncp2", // model: CircleOfPower	 scale: 1,5	 selectScale: 4
  CityBuildingLarge0 = "ncbc", // model: CityBuildingLarge_0	 selectScale: 4
  CityBuildingLarge1 = "ncbd", // model: CityBuildingLarge_45	 selectScale: 4
  CityBuildingLarge2 = "ncbe", // model: CityBuildingLarge_90	 selectScale: 4
  CityBuildingLarge3 = "ncbf", // model: CityBuildingLarge_135	 selectScale: 4
  CitybuildingSmall0 = "ncb0", // model: CityBuildingSmall45_0	 selectScale: 4
  CitybuildingSmall1 = "ncb1", // model: CityBuildingSmall45_1	 selectScale: 4
  CitybuildingSmall2 = "ncb2", // model: CityBuildingSmall45_2	 selectScale: 4
  CitybuildingSmall3 = "ncb3", // model: CityBuildingSmall90_0	 selectScale: 4
  CitybuildingSmall4 = "ncb4", // model: CityBuildingSmall90_1	 selectScale: 4
  CitybuildingSmall5 = "ncb5", // model: CityBuildingSmall90_2	 selectScale: 4
  CitybuildingSmall6 = "ncb6", // model: CityBuildingSmall135_0	 selectScale: 4
  CitybuildingSmall7 = "ncb7", // model: CityBuildingSmall135_1	 selectScale: 4
  CitybuildingSmall8 = "ncb8", // model: CityBuildingSmall135_2	 selectScale: 4
  CitybuildingSmall9 = "ncb9", // model: CityBuildingSmall0_0	 selectScale: 4
  CitybuildingSmall10 = "ncba", // model: CityBuildingSmall0_1	 selectScale: 4
  CitybuildingSmall11 = "ncbb", // model: CityBuildingSmall0_2	 selectScale: 4
  Clockwerkgoblin1 = "ncgb", // model: HeroTinkerRobot	 selectScale: 1,15
  Clockwerkgoblin2 = "ncg1", // model: HeroTinkerRobot	 selectScale: 1,15
  Clockwerkgoblin3 = "ncg2", // model: HeroTinkerRobot	 selectScale: 1,15
  Clockwerkgoblin4 = "ncg3", // model: HeroTinkerRobot	 selectScale: 1,15
  Coldtower = "ndt1", // model: TowerDefenseTower	 selectScale: 2,5
  Coldtowerupgrade = "ndt2", // model: TowerDefenseTower	 selectScale: 2,5
  Coralbed = "nnfm", // model: CoralBed	 selectScale: 3
  Corruptedancientofwar = "ncaw", // model: CorruptedAncientofWar	 selectScale: 4
  Corruptedancientprotector = "ncap", // model: CorruptedAncientProtector	 selectScale: 4
  Corruptedent = "nenc", // model: CorruptedEnt	 scale: 0,9
  Corruptedmoonwell = "ncmw", // model: CorruptedMoonWell	 selectScale: 3
  Corruptedtreeofages = "ncta", // model: CorruptedTreeofLife	 scale: 1,15	 selectScale: 4,75
  Corruptedtreeofeternity = "ncte", // model: CorruptedTreeofLife	 scale: 1,3	 selectScale: 4,75
  Corruptedtreeoflife = "nctl", // model: CorruptedTreeofLife	 selectScale: 4,75
  Crab = "ncrb", // model: SpiderCrab	 selectScale: 0,9
  Crypt = "usep", // model: Crypt	 selectScale: 5
  Cryptfiend = "ucry", // model: CryptFiend	 scale: 0,9	 selectScale: 1,85
  Cryptfiendmorph = "ucrm", // model: CryptFiend	 scale: 0,9	 selectScale: 1,85
  Cryptlord = "Ucrl", // model: HeroCryptLord	 selectScale: 1,85
  Crystalarachnathid = "nanc", // model: ArchnathidGreen	 scale: 0,65	 selectScale: 1,2
  Dagren = "Hdgo", // model: HeroPaladinBoss2	 selectScale: 1,1
  Dalaranguardtower = "ndgt", // model: DalaranGuardTower	 selectScale: 2,5
  Dalaranmutant = "ndmu", // model: DalaranMutant	 scale: 1,75	 selectScale: 1,1
  Dalaranreject = "ndrj", // model: DalaranReject	 scale: 1,15	 selectScale: 1,45
  Darkminion1 = "ndr1", // model: Skeleton
  Darkminion2 = "ndr2", // model: Skeleton	 scale: 1,2	 selectScale: 1,2
  Darkminion3 = "ndr3", // model: Skeleton	 scale: 1,4	 selectScale: 1,4
  Darkportalse = "ndke", // model: DarkPortal2	 selectScale: 8,5
  Darkportalsw = "ndkw", // model: DarkPortal	 selectScale: 8,5
  Darkranger = "Nbrn", // model: BansheeRanger	 selectScale: 1,5
  Darktroll = "ndtr", // model: DarkTroll	 scale: 0,85
  Darktrollberserker = "ndtb", // model: DarkTroll	 scale: 1,3	 selectScale: 1,5
  Darktrollhighpriest = "ndth", // model: DarkTrollShadowPriest	 scale: 1,25	 selectScale: 1,5
  Darktrollshadowpriest = "ndtp", // model: DarkTrollShadowPriest	 scale: 0,9	 selectScale: 1,5
  Darktrolltrapper = "ndtt", // model: DarkTrollTrapper	 scale: 1,15
  Darktrollwarlord = "ndtw", // model: DarkTrollTrapper	 scale: 1,6	 selectScale: 2
  Darkwizard = "nwzd", // model: BanditMage	 scale: 1,2	 selectScale: 1,5
  Deathknight = "Udea", // model: HeroDeathKnight	 selectScale: 1,85
  Deathrevenant = "nrvd", // model: Revenant	 scale: 1,5	 selectScale: 1,2
  Deathtower = "ntt1", // model: TowerDefenseTower	 selectScale: 2,5
  Deathtowerupgrade = "ntx2", // model: TowerDefenseTower	 selectScale: 2,5
  Deceiver = "nhdc", // model: Acolyte	 scale: 1,2	 selectScale: 1,1
  Deeplordrevenant = "nlrv", // model: RevenantOfTheWaves	 scale: 1,6
  Deer = "nder", // model: BlackStagMale	 scale: 1,5	 selectScale: 1,1
  Defiledfountainoflife = "ndfl", // model: FountainOfLifeDefiled	 selectScale: 5
  Demolisher = "ocat", // model: catapult	 selectScale: 2,75
  DraeneiDemolisher = "ncat", // model: catapult	 selectScale: 2,75
  Demongate = "ndmg", // model: DemonGate	 selectScale: 5
  Demonhunter = "Edem", // model: HeroDemonHunter	 selectScale: 1,5
  Demonhuntermorphed = "Edmm", // model: HeroDemonHunter	 selectScale: 2
  Detheroc = "Udth", // model: HeroDreadLord	 scale: 1,4	 selectScale: 1,75
  Diremammoth = "nmdr", // model: MammothBlack	 scale: 1,25	 selectScale: 2,5
  Direwolf = "nwld", // model: DireWolf	 scale: 1,2	 selectScale: 1,3
  Dog = "ndog", // model: BrownWolf
  Doomguard = "nbal", // model: DoomGuard	 scale: 1,3	 selectScale: 2
  Doomguardsummoned = "nba2", // model: DoomGuard	 scale: 1,3	 selectScale: 2
  DraeneiDarkslayer = "ndrd", // model: DranaiWhite	 scale: 1,15	 selectScale: 1,25
  Draeneidisciple = "ndrm", // model: DranaiMage	 scale: 0,8	 selectScale: 0,85
  DraeneiGuardian = "ndrf", // model: Dranai	 scale: 0,8	 selectScale: 0,85
  Draeneiharbinger = "ndrh", // model: DranaiMage	 selectScale: 1,05
  Draeneihaven = "ndh2", // model: ChieftainHut	 scale: 1,2	 selectScale: 4,25
  Draeneilaborer = "ndrl", // model: Dranai	 scale: 0,8	 selectScale: 0,8
  Draeneiprotector = "ndrp", // model: DranaiWhite	 scale: 0,9	 selectScale: 0,95
  Draeneisalamander = "ndsa", // model: ThunderLizardVizier	 scale: 0,9	 selectScale: 2
  DraeneiSeer = "ndrs", // model: DranaiMage	 scale: 1,1	 selectScale: 1,25
  Draeneiseerden = "ndh4", // model: DraneiHut1	 scale: 1,2	 selectScale: 4,25
  Draeneistalker = "ndrt", // model: Dranai	 selectScale: 1,2
  Draeneivindicator = "ndrn", // model: DranaiWhite	 scale: 1,15	 selectScale: 1,25
  Draeneiwarriorshall = "ndh3", // model: DraneiHut0	 scale: 1,2	 selectScale: 4,25
  Draeneiwatcher = "ndrw", // model: Dranai	 selectScale: 1,05
  Dragonbuilding = "ndrb", // model: DragonBuilding	 selectScale: 3,5
  Dragonhawk = "hdhw", // model: BloodElfDragonHawk	 selectScale: 1,5
  Dragonturtle = "nhyc", // model: DragonSeaTurtle	 scale: 1,2	 selectScale: 4
  Drakthul = "odkt", // model: OrcWarlockRed	 scale: 1,2	 selectScale: 1,25
  Draneihut0 = "ndh0", // model: DraneiHut0	 selectScale: 2,5
  Draneihut1 = "ndh1", // model: DraneiHut1	 selectScale: 2,5
  Dreadlord = "Udre", // model: HeroDreadLord	 selectScale: 1,5
  Drekthar = "Odrt", // model: HeroFarSeer	 selectScale: 2
  Druidoftheclaw = "edoc", // model: DruidoftheClaw	 selectScale: 2
  Druidoftheclawmorphed = "edcm", // model: DruidoftheClaw	 selectScale: 2,5
  Druidofthetalon = "edot", // model: DruidoftheTalon	 selectScale: 1,25
  Druidofthetalonmorphed = "edtm", // model: DruidoftheTalon	 selectScale: 1,25
  Dryad = "edry", // model: Dryad	 selectScale: 1,25
  Duneworm = "ndwm", // model: DuneWorm	 selectScale: 0,9
  Earthborerarachnathid = "nane", // model: Archnathid	 selectScale: 1,7
  Earthfurytower = "negf", // model: ElvenGuardFireTower	 selectScale: 2,5
  Elderhydra = "nehy", // model: Hydra	 scale: 1,2	 selectScale: 2,5
  Elderjunglestalker = "njga", // model: JungleBeast	 scale: 1,2	 selectScale: 1,45
  Eldersasquatch = "nsqe", // model: SasquatchShaman	 selectScale: 1,2
  Eldervoidwalker = "nvde", // model: VoidWalker	 scale: 1,5	 selectScale: 1,5
  AncientOfWarCreep = "nwnr", // model: Wendigo	 scale: 1,3
  Elvenfarm = "nefm", // model: ElvenFarm	 selectScale: 3,5
  Elvenfarm0 = "nef0", // model: ElvenVillageBuilding0	 selectScale: 3,5
  Elvenfarm1 = "nef1", // model: ElvenVillageBuilding1	 selectScale: 3,5
  Elvenfarm2 = "nef2", // model: ElvenVillageBuilding2	 selectScale: 3,5
  Elvenfarm3 = "nef3", // model: ElvenVillageBuilding3	 selectScale: 3,5
  Elvenfarm4 = "nef4", // model: ElvenVillageBuilding4	 selectScale: 3,5
  Elvenfarm5 = "nef5", // model: ElvenVillageBuilding5	 selectScale: 3,5
  Elvenfarm6 = "nef6", // model: ElvenVillageBuilding6	 selectScale: 3,5
  Elvenfarm7 = "nef7", // model: ElvenVillageBuilding7	 selectScale: 3,5
  Elvenfishingvillage0 = "nfv0", // model: ElvenFishVillageBuilding0	 selectScale: 3,5
  Elvenfishingvillage1 = "nfv1", // model: ElvenFishVillageBuilding1	 selectScale: 3,5
  Elvenfishingvillage2 = "nfv2", // model: ElvenFishVillageBuilding2	 selectScale: 3,5
  Elvenfishingvillage3 = "nfv3", // model: ElvenFishVillageBuilding3	 selectScale: 3,5
  Elvenfishingvillage4 = "nfv4", // model: ElvenFishVillageBuilding4	 selectScale: 3,5
  Elvenguardtower = "negt", // model: ElvenGuardTower	 selectScale: 2,5
  Emissary = "nemi", // model: HumanMage	 scale: 1,1
  Energytower = "net1", // model: TowerDefenseTower	 selectScale: 2,5
  Energytowerupgrade = "net2", // model: TowerDefenseTower	 selectScale: 2,5
  Enforcer = "nenf", // model: Bandit	 scale: 1,45
  Engineergazlowe = "negz", // model: GoblinSapper
  Enragedelemental = "nele", // model: WaterElemental	 scale: 1,2	 selectScale: 1,6
  Enragedowlbear = "nowe", // model: Owlbear	 scale: 1,4	 selectScale: 1,8
  Enrangedjunglestalker = "njgb", // model: JungleBeast	 scale: 1,5	 selectScale: 1,7
  Entangledgoldmine = "egol", // model: EntangledGoldMine	 selectScale: 5,5
  Eredardiabolist = "nerd", // model: EredarWarlockPurple	 scale: 1,65	 selectScale: 2
  Eredarsorceror = "ners", // model: EredarWarlock	 scale: 1,4	 selectScale: 2
  Eredarwarlock = "nerw", // model: EredarWarlock	 scale: 1,75	 selectScale: 2
  Evilarthas = "Uear", // model: UndeadArthas	 selectScale: 1,85
  Evilillidan = "Eevi", // model: IllidanEvil	 selectScale: 1,5
  Evilillidandemonform = "Eevm", // model: IllidanEvil	 selectScale: 2
  Evilsylvanas = "Usyl", // model: EvilSylvanas	 selectScale: 1,5
  Facelessonedeathbringer = "nfod", // model: FacelessOne	 scale: 2,3	 selectScale: 2,4
  Facelessoneterror = "nfot", // model: FacelessOne	 scale: 1,85	 selectScale: 2
  Facelessonetrickster = "nfor", // model: FacelessOne	 scale: 1,4	 selectScale: 1,4
  Faeriedragon = "efdr", // model: FaerieDragon	 selectScale: 1,5
  Fallenpriest = "nhfp", // model: Acolyte	 scale: 1,1
  Farm = "hhou", // model: Farm	 selectScale: 2,5
  Farseer = "Ofar", // model: HeroFarSeer	 selectScale: 2
  Felboar = "nfbr", // model: Felboar	 selectScale: 0,9
  Felguard = "nfgu", // model: Felgaurd
  Felravager = "npfm", // model: FelstalkerPurple	 scale: 1,5	 selectScale: 2,5
  Felstalker = "nfel", // model: felhound	 selectScale: 1,5
  Firelord = "Nfir", // model: HeroFlameLord	 scale: 1,15	 selectScale: 2
  Firerevenant = "nrvf", // model: Revenant	 scale: 0,9
  Flametower = "nft1", // model: TowerDefenseTower	 selectScale: 2,5
  Flametowerupgrade = "nft2", // model: TowerDefenseTower	 selectScale: 2,5
  Fleshgolem = "nfgl", // model: FleshGolem	 scale: 1,75	 selectScale: 3
  Flyingmachine = "hgyr", // model: Gyrocopter	 selectScale: 1,5
  Flyingsheep = "nshf", // model: FlyingSheep	 scale: 1,2	 selectScale: 0,8
  Footman = "hfoo", // model: Footman
  Forceofnature = "efon", // model: Ent	 selectScale: 1,5
  Forestspider = "nspg", // model: SpiderGreen	 scale: 0,6	 selectScale: 1,5
  Foresttroll = "nftr", // model: ForestTroll
  Foresttrollberserker = "nftb", // model: ForestTroll	 scale: 1,25	 selectScale: 1,5
  Foresttrollhighpriest = "nfsh", // model: ForestTrollShadowPriest	 scale: 1,25	 selectScale: 1,5
  Foresttrollhut0 = "nfh0", // model: ForestTrollHut0	 selectScale: 3,5
  Foresttrollhut1 = "nfh1", // model: ForestTrollHut1	 selectScale: 3,5
  Foresttrollking = "nftk", // model: ForestTrollTrapper	 scale: 1,55	 selectScale: 2
  Foresttrollshadowpriest = "nfsp", // model: ForestTrollShadowPriest	 scale: 1,05	 selectScale: 1,5
  Foresttrolltrapper = "nftt", // model: ForestTrollTrapper
  Forgottenone = "nfgo", // model: ForgottenOne	 scale: 0,9	 selectScale: 4,3
  Fortress = "ofrt", // model: GreatHall	 selectScale: 6,6
  Fountainofhealth = "nfoh", // model: FountainOfHealth	 selectScale: 5
  Fountainofmana = "nmoo", // model: FountainOfMana	 selectScale: 5
  Frog = "nfro", // model: Frog	 selectScale: 0,9
  Frostmourne = "nfrm", // model: Frostmourne	 selectScale: 2,5
  Frostrevenant = "nrvs", // model: Revenant
  Frosttower = "uzg2", // model: Ziggurat	 selectScale: 4,25
  Frostwyrm = "ufro", // model: FrostWyrm	 selectScale: 2,25
  Fruitstand = "nfrt", // model: FruitStand	 selectScale: 4
  Furbolg = "nfrl", // model: Furbolg	 scale: 1,15
  Furbolgancient = "nfra", // model: FurbolgElder	 scale: 1,4	 selectScale: 1,75
  Furbolgchampion = "nfrg", // model: Furbolg	 scale: 1,3	 selectScale: 1,5
  Furbolgeldershaman = "nfre", // model: FurbolgShaman	 scale: 1,25	 selectScale: 1,5
  Furbolghut1 = "nfr1", // model: FurbolgHut	 selectScale: 3,5
  Furbolghut2 = "nfr2", // model: FurbolgHut2	 selectScale: 3,5
  Furbolgpanda = "nfrp", // model: FurbolgPanda
  Furbolgshaman = "nfrs", // model: FurbolgShaman	 scale: 0,9
  Furbolgtracker = "nfrb", // model: FurbolgTracker	 scale: 1,2
  Furion = "Efur", // model: Furion	 scale: 1,1	 selectScale: 1,25
  Gargantuanseaturtle = "ntrg", // model: GiantSeaTurtle	 selectScale: 3
  Gargoyle = "ugar", // model: Gargoyle	 selectScale: 1,25
  Gargoylemorphed = "ugrm", // model: Gargoyle	 selectScale: 1,25
  Garthok = "ogrk", // model: Grunt	 scale: 1,1
  Gemstoneobelisk = "ngob", // model: BridgeObelisk	 selectScale: 2,5
  Ghost = "ngh1", // model: BansheeGhost	 scale: 1,05
  Ghostlyarchmage = "Hgam", // model: HeroArchMageGhost	 selectScale: 1,5
  Ghoul = "ugho", // model: Ghoul	 selectScale: 1,1
  Giantpolarbear = "nplg", // model: PolarBear	 scale: 1,3	 selectScale: 2,4
  Giantseaturtle = "ntrt", // model: GiantSeaTurtleRange	 scale: 0,8	 selectScale: 2,5
  Giantskeleton = "nskg", // model: Skeleton	 scale: 1,35
  Giantspider = "nsgt", // model: Spider	 scale: 1,25	 selectScale: 1,5
  Giantwhitewolf = "nwwg", // model: WhiteWolf	 scale: 1,2	 selectScale: 1,5
  Giantwolf = "nwlg", // model: TimberWolf	 scale: 1,1	 selectScale: 1,2
  Glaivethrower = "ebal", // model: Ballista	 selectScale: 3
  Gnoll1 = "ngno", // model: Gnoll
  Gnoll3 = "ngnw", // model: GnollWarden	 scale: 1,5
  Gnollassassin = "ngns", // model: GnollArcher	 scale: 1,3
  Gnollbrute = "ngnb", // model: Gnoll	 scale: 1,3
  Gnollhut = "ngnh", // model: GnollHut	 selectScale: 3,5
  Gnollhut2 = "ngt2", // model: GnollHut2	 selectScale: 3,5
  Gnollking = "ngnv", // model: GnollOverseer	 scale: 1,75
  Gnollpoacher = "ngna", // model: GnollArcher	 scale: 0,9
  Goblinammodump = "ngad", // model: AmmoDump	 selectScale: 4,75
  Goblinblaster = "ngbl", // model: IronGolem	 selectScale: 1,75
  Goblinlandmine = "nglm", // model: GoblinLandMine	 selectScale: 0,75
  Goblinmerchant = "ngme", // model: Merchant	 selectScale: 4,5
  Goblinsapper = "ngsp", // model: GoblinSapper
  Goblinshipyard = "nshp", // model: GoblinShipyard	 selectScale: 4,75
  Goblinshredder = "ngir", // model: IronGolem	 selectScale: 1,75
  Goblinzeppelin = "nzep", // model: GoblinZeppelin	 selectScale: 1,5
  Goldmine = "ngol", // model: GoldMine	 selectScale: 5
  Grainwarehouse = "ngwr", // model: GrainWarehouse	 selectScale: 4
  Granaryinfected = "ngni", // model: GranaryInfected	 selectScale: 3,5
  Granitegolem = "nggr", // model: RockGolem	 scale: 1,5	 selectScale: 3
  Graveyard = "ugrv", // model: Graveyard	 selectScale: 5
  Greatervoidwalker = "nvdg", // model: VoidWalker	 scale: 1,3	 selectScale: 1,3
  Greathall = "ogre", // model: GreatHall	 selectScale: 6,6
  Greendragon = "ngrd", // model: GreenDragon	 scale: 1,75	 selectScale: 2,25
  Greendragonroost = "ndrg", // model: DragonBuildingGreen	 scale: 1,5	 selectScale: 6,6
  Greendragonwhelp = "ngrw", // model: GreenDragonWelp	 scale: 0,7	 selectScale: 1,75
  Greendrake = "ngdk", // model: GreenDragon	 scale: 1,2	 selectScale: 2
  Grizzlybear1 = "ngz1", // model: GrizzlyBear	 scale: 0,9	 selectScale: 1,25
  Grizzlybear2 = "ngz2", // model: GrizzlyBear	 scale: 1,1	 selectScale: 1,5
  Grizzlybear3 = "ngz3", // model: GrizzlyBear	 scale: 1,25	 selectScale: 1,75
  Gromhellscream = "Ogrh", // model: Hellscream	 selectScale: 1,15
  Grunt = "ogru", // model: Grunt	 scale: 1,1
  Gryphonaviary = "hgra", // model: GryphonAviary	 selectScale: 4
  Gryphonrider = "hgry", // model: GryphonRider	 scale: 1,2	 selectScale: 1,5
  Guardtower = "hgtw", // model: HumanTower	 selectScale: 2,5
  Guldan = "Ogld", // model: OrcWarlockGuldan	 selectScale: 1,4
  Halahk = "Hhkl", // model: HeroPaladinBoss	 selectScale: 1,1
  Harpyhag = "nhrh", // model: HarpyWitch	 scale: 1,7	 selectScale: 1,5
  Harpynest = "nhns", // model: HarpyNest	 selectScale: 3,5
  Harpyqueen = "nhrq", // model: HarpyQueen	 scale: 2,1	 selectScale: 2
  Harpyrogue = "nhrr", // model: Harpy	 scale: 1,7	 selectScale: 1,2
  Harpyscout = "nhar", // model: Harpy	 selectScale: 1,2
  Harpywitch = "nhrw", // model: HarpyWitch	 selectScale: 1,2
  Headhunter = "ohun", // model: HeadHunter	 selectScale: 1,1
  Healingward = "ohwd", // model: HealingWard	 selectScale: 0,75
  Heretic = "nhhr", // model: Acolyte	 scale: 1,5	 selectScale: 1,25
  Hermitcrab = "nhmc", // model: HermitCrab	 selectScale: 0,9
  Highelfbarracks = "nheb", // model: MageTower	 selectScale: 4
  Highelvenarcher = "nhea", // model: HighElfArcher
  Highelvenfemale = "nhef", // model: ElfVillagerWoman
  Highelvenmale = "nhem", // model: HighElfPeasant
  Highelvenswordsman = "hhes", // model: TheCaptain	 scale: 0,9	 selectScale: 1,2
  Hippogryph = "ehip", // model: Hippogryph	 selectScale: 1,5
  Hornofcenarius = "nhcn", // model: HornOfCenarius	 selectScale: 2,5
  Humanarcanetower = "hatw", // model: HumanTower	 selectScale: 2,5
  Humanbarracks = "hbar", // model: HumanBarracks	 selectScale: 5
  Humanbattleship = "hbsh", // model: HumanBattleship	 selectScale: 4
  Humandestroyer = "hdes", // model: HumanDestroyerShip	 selectScale: 3
  Humanlumbermill = "hlum", // model: HumanLumbermill	 selectScale: 4,25
  Humanshipyard = "hshy", // model: HumanShipyard	 selectScale: 5
  Humantransportship = "hbot", // model: HumanTransportShip	 selectScale: 3
  Huntershall = "edob", // model: HuntersHall	 selectScale: 4,2
  Huntress = "esen", // model: Huntress	 selectScale: 1,5
  Hydra = "nhyd", // model: Hydra	 scale: 1,1	 selectScale: 2,5
  Hydrahatchling = "nhyh", // model: Hydra	 scale: 0,75	 selectScale: 1,5
  Hydralisk = "zhyd", // model: Hydralisk	 selectScale: 1,2
  Hydromancer = "nhym", // model: BanditMage	 scale: 0,9	 selectScale: 1,5
  Icecrownobelisk = "nico", // model: IcecrownObelisk	 selectScale: 3,5
  Icerevenant = "nrvi", // model: Revenant	 scale: 1,3	 selectScale: 1,1
  Icetroll = "nitr", // model: IceTroll
  Icetrollberserker = "nits", // model: IceTroll	 scale: 1,3
  Icetrollhighpriest = "nith", // model: IceTrollShadowPriest	 scale: 1,25
  Icetrollhut0 = "nth0", // model: IceTrollHut0	 selectScale: 3,5
  Icetrollhut1 = "nth1", // model: IceTrollHut1	 selectScale: 3,5
  Icetrollshadowpriest = "nitp", // model: IceTrollShadowPriest	 scale: 1,05
  Icetrolltrapper = "nitt", // model: IceTroll
  Icetrollwarlord = "nitw", // model: IceTroll	 scale: 1,55
  Icetuskmammoth = "nmit", // model: Mammoth	 scale: 1,05	 selectScale: 2,1
  Illidan = "Eill", // model: HeroDemonHunter	 selectScale: 1,5
  Illidandemonform = "Eidm", // model: HeroDemonHunter	 selectScale: 2
  Illidanmorphed = "Eilm", // model: HeroDemonHunter	 selectScale: 2
  Illidanwagon = "eilw", // model: IllidanEvilCaged	 selectScale: 2,5
  Infernal = "ninf", // model: Infernal	 selectScale: 2,5
  Infernalcontraption = "ninc", // model: InfernalCannonCannon	 scale: 0,75	 selectScale: 2,25
  Infernaljuggernaut = "nina", // model: InfernalCannonFlame	 scale: 1,5	 selectScale: 3,5
  Infernalmachine = "ninm", // model: InfernalCannonCannon	 selectScale: 2,75
  Jailorkassan = "njks", // model: Bandit	 scale: 1,5	 selectScale: 1,25
  Jaina = "Hjai", // model: Jaina	 selectScale: 1,5
  Juggernaut = "ojgn", // model: OrcJuggernaught	 selectScale: 4
  Junglestalker = "njg1", // model: JungleBeast	 selectScale: 1,1
  Kael = "Hkal", // model: Kael	 selectScale: 1,5
  Keep = "hkee", // model: TownHall	 selectScale: 6,3
  Keeperofthegrove = "Ekee", // model: HeroKeeperoftheGrove	 selectScale: 2,25
  Keeperofthegroveghost = "Ekgg", // model: HeroKeeperoftheGroveGhost	 selectScale: 2,25
  Kelthuzadghost = "uktg", // model: KelThuzadGhost	 scale: 1,15	 selectScale: 1,25
  Kelthuzadlich = "Uktl", // model: HeroLich	 selectScale: 1,25
  Kelthuzadlichcinematic = "Uclc", // model: HeroLichCIN	 selectScale: 1,25
  Kelthuzadnecro = "uktn", // model: Kelthuzad	 scale: 1,15	 selectScale: 1,25
  Kiljaeden = "Nklj", // model: Kiljaeden	 selectScale: 1,7
  Kiljaedencinematic = "Nkjx", // model: KiljaedenCinema	 selectScale: 3
  Knight = "hkni", // model: Knight	 selectScale: 1,4
  Kobold = "nkob", // model: Kobold	 scale: 0,85
  Koboldgeomancer = "nkog", // model: KoboldGeomancer	 scale: 1,4
  Koboldtaskmaster = "nkol", // model: Kobold	 scale: 1,6
  Kobolttunneler = "nkot", // model: Kobold	 scale: 1,25
  Kotobeast = "okod", // model: KotoBeast	 selectScale: 2,25
  Kotobeastnorider = "oosc", // model: KotoBeastNoRider	 selectScale: 2,5
  Ladyvashj = "Hvsh", // model: LadyVashj	 selectScale: 1,5
  Lavaspawn = "nlv1", // model: LavaSpawn	 scale: 0,8	 selectScale: 1,6
  Lavaspawn2 = "nlv2", // model: LavaSpawn	 selectScale: 1,6
  Lavaspawn3 = "nlv3", // model: LavaSpawn	 scale: 1,2	 selectScale: 1,6
  Lesservoidwalker = "nvdl", // model: VoidWalker	 scale: 0,75
  Lich = "Ulic", // model: HeroLich	 selectScale: 1,25
  Lichking = "nzlc", // model: lichking	 selectScale: 4
  Lightninglizard = "nltl", // model: ThunderLizard	 scale: 0,85	 selectScale: 2,5
  Lightningrevenant = "nrvl", // model: Revenant	 scale: 1,1
  Lobstrokkdeepseer = "nlds", // model: Lobstrokkblue	 scale: 0,8	 selectScale: 1,75
  Lobstrokkpooldweller = "nlpd", // model: Lobstrokkred	 scale: 0,6	 selectScale: 1,65
  Lobstrokkprawn = "nlpr", // model: Lobstrokkred	 scale: 0,55	 selectScale: 1,4
  Lobstrokkprawnsummoned = "nlps", // model: Lobstrokkred	 scale: 0,55	 selectScale: 1,4
  Lobstrokksnapper = "nlsn", // model: Lobstrokkred	 scale: 0,8	 selectScale: 1,9
  Lobstrokktidallord = "nlkl", // model: Lobstrokkgreen	 selectScale: 2,5
  Lobstrokktidecaller = "nltc", // model: Lobstrokkblue	 scale: 0,57	 selectScale: 1,5
  Locust = "uloc", // model: Locust
  Lordgarithos = "Hlgr", // model: LordGarithos	 scale: 1,2	 selectScale: 1,6
  Magicvault = "nmgv", // model: MagicVault	 selectScale: 3,3
  Magnataurdestroyer = "nmgd", // model: MagnataurBlue	 scale: 1,45	 selectScale: 3
  Magnataurreaver = "nmgr", // model: Magnataur	 scale: 1,325	 selectScale: 2,75
  Magnataurwarrior = "nmgw", // model: MagnataurBrown	 scale: 1,125	 selectScale: 2,25
  Magtheridon = "Nmag", // model: HeroPitLord	 scale: 1,35	 selectScale: 3
  Maidenofpain = "ndqp", // model: DemonessBlue	 scale: 1,4	 selectScale: 1,4
  Maiev = "Ewrd", // model: Maiev	 selectScale: 1,5
  Malfurion = "Emfr", // model: MalFurion	 scale: 1,2	 selectScale: 2,25
  Malfurionnostag = "Emns", // model: MalFurionNoStag	 scale: 1,2	 selectScale: 2,25
  Malganis = "Umal", // model: HeroDreadLord	 selectScale: 1,5
  Mammoth = "nmam", // model: Mammoth	 scale: 0,85	 selectScale: 1,75
  Mannoroth = "Nman", // model: Mannoroth	 scale: 1,7	 selectScale: 3
  Margoth = "Hmgd", // model: HeroPaladin	 selectScale: 1,1
  Marine = "zmar", // model: Marine
  Marketplace = "nmrk", // model: Marketplace	 selectScale: 6
  Mathog = "omtg", // model: ChaosWarlord
  Meatwagon = "umtw", // model: MeatWagon	 selectScale: 2,5
  Medivh = "nmed", // model: Medivh	 selectScale: 1,25
  Medivhmorphed = "nmdm", // model: Medivh	 selectScale: 1,25
  Mercenarycampa = "nmr5", // model: Mercenary	 scale: 0,8	 selectScale: 6
  Mercenarycampb = "nmr4", // model: Mercenary	 scale: 0,8	 selectScale: 6
  Mercenarycampc = "nmr6", // model: Mercenary	 scale: 0,8	 selectScale: 6
  Mercenarycampd = "nmra", // model: Mercenary	 scale: 0,8	 selectScale: 6
  Mercenarycampf = "nmr2", // model: Mercenary	 scale: 0,8	 selectScale: 6
  Mercenarycampg = "nmrb", // model: Mercenary	 scale: 0,8	 selectScale: 6
  Mercenarycampi = "nmrd", // model: Mercenary	 scale: 0,8	 selectScale: 6
  Mercenarycampk = "nmrf", // model: Mercenary	 scale: 0,8	 selectScale: 6
  Mercenarycampl = "nmer", // model: Mercenary	 scale: 0,8	 selectScale: 6
  Mercenarycampn = "nmr7", // model: Mercenary	 scale: 0,8	 selectScale: 6
  Mercenarycampo = "nmre", // model: Mercenary	 scale: 0,8	 selectScale: 6
  Mercenarycampv = "nmr0", // model: Mercenary	 scale: 0,8	 selectScale: 6
  Mercenarycampw = "nmr3", // model: Mercenary	 scale: 0,8	 selectScale: 6
  Mercenarycampx = "nmr9", // model: Mercenary	 scale: 0,8	 selectScale: 6
  Mercenarycampy = "nmr8", // model: Mercenary	 scale: 0,8	 selectScale: 6
  Mercenarycampz = "nmrc", // model: Mercenary	 scale: 0,8	 selectScale: 6
  Militia = "hmil", // model: Militia
  Misha = "nmsh", // model: GrizzlyBear	 selectScale: 1,4
  Misha1 = "ngzc", // model: GrizzlyBear	 scale: 0,9	 selectScale: 1,75
  Misha2 = "ngzd", // model: GrizzlyBear	 scale: 1,1	 selectScale: 2
  Misha3 = "ngza", // model: GrizzlyBear	 scale: 1,2	 selectScale: 2,2
  Misha4 = "ngz4", // model: GrizzlyBear	 scale: 1,3	 selectScale: 2,4
  Monsterlure = "nlur", // model: MonsterLure	 selectScale: 0,75
  Moonwell = "emow", // model: MoonWell	 selectScale: 3
  Mortarteam = "hmtm", // model: MortarTeam	 selectScale: 1,3
  Mountaingiant = "emtg", // model: MountainGiant	 selectScale: 3
  Mountainking = "Hmkg", // model: HeroMountainKing	 selectScale: 1,25
  Mudgolem = "ngrk", // model: RockGolem	 scale: 0,6	 selectScale: 1,75
  Muradinbronzebeard = "Hmbr", // model: Muradin
  Murgulbloodgill = "nmbg", // model: MurgulBloodGill	 scale: 0,9	 selectScale: 0,9
  Murgulcliffrunner = "nmcf", // model: MurgulTideWarrior	 scale: 0,8	 selectScale: 0,8
  Murgulhut0 = "nmg0", // model: MurlocHut0	 selectScale: 3,5
  Murgulhut1 = "nmg1", // model: MurlocHut1	 selectScale: 3,5
  Murgulreaver = "nnmg", // model: MurgulReaver	 scale: 1,5	 selectScale: 1,45
  Murgulshadowcaster = "nmsc", // model: MurgulShadowCaster	 scale: 1,55	 selectScale: 1,5
  Murgulslave = "nmpe", // model: MurgulSlave
  Murgulsnarecaster = "nmsn", // model: MurgulShadowCaster	 scale: 1,1	 selectScale: 1,1
  Murgultidewarrior = "nmtw", // model: MurgulTideWarrior
  Murlocflesheater = "nmfs", // model: MurlocFlesheater	 scale: 1,55
  Murlochuntsman = "nmrr", // model: MurlocWarrior	 scale: 1,3
  Murlochut0 = "nmh0", // model: MurlocHut0	 selectScale: 3,5
  Murlochut1 = "nmh1", // model: MurlocHut1	 selectScale: 3,5
  Murlocmutant = "nmmu", // model: MurlocMutant	 scale: 2
  Murlocnightcrawler = "nmrm", // model: MurlocNightcrawler	 scale: 1,6
  Murlocplaguebearer = "nmpg", // model: MurlocMutant
  Murloctiderunner = "nmrl", // model: Murloc
  Nagacoutl = "nwgs", // model: WindSerpent	 scale: 0,7	 selectScale: 1,75
  Nagamurgul = "nnmg", // model: MurgulReaver	 scale: 1,1	 selectScale: 1,15
  Nagamyrmidon = "nmyr", // model: NagaMyrmidon	 selectScale: 1,75
  Nagamyrmidonmorph = "nmys", // model: NagaMyrmidon	 selectScale: 1,75
  Nagaroyalguard = "nnrg", // model: NagaRoyalGuard	 scale: 1,25	 selectScale: 2,25
  Nagaroyalguardmorph = "nnrs", // model: NagaRoyalGuard	 scale: 1,25	 selectScale: 2,25
  Naisha = "ensh", // model: Huntress	 scale: 1,2	 selectScale: 1,5
  Nazgrel = "onzg", // model: WolfRider	 selectScale: 1,6
  Necromancer = "unec", // model: Necromancer	 selectScale: 1,25
  Necropolis = "unpl", // model: Necropolis	 selectScale: 6,6
  Necropolis1 = "unp1", // model: Necropolis	 selectScale: 6,6
  Necropolis2 = "unp2", // model: Necropolis	 selectScale: 6,6
  Nerubianqueen = "nnwq", // model: NerubianQueen	 scale: 1,6	 selectScale: 2
  Nerubianseer = "nnwr", // model: NerubianQueen	 scale: 1,4	 selectScale: 1,8
  Nerubianspiderlord = "nnws", // model: NerubianSpiderLord	 scale: 1,55	 selectScale: 1,8
  Nerubianwarrior = "nnwa", // model: Nerubian	 scale: 1,2	 selectScale: 1,75
  Nerubianwebspinner = "nnwl", // model: NerubianSpiderLord	 selectScale: 2
  Nerubianziggurat = "nnzg", // model: NerubianZiggurat	 selectScale: 3,5
  Netherdragon = "nndr", // model: NetherDragon	 scale: 1,35	 selectScale: 2
  Netherdragonhatchling = "nnht", // model: NetherDragon	 scale: 0,65	 selectScale: 1,65
  Netherdrake = "nndk", // model: NetherDragon	 scale: 1,05	 selectScale: 1,75
  Nightelfassassin = "nssn", // model: assassin	 selectScale: 1,15
  Nightelfbattleship = "ebsh", // model: NightElfBattleship	 selectScale: 4
  Nightelfdestroyer = "edes", // model: NightElfDestroyerShip	 selectScale: 3
  Nightelfrunner = "enec", // model: Runner
  Nightelfshipyard = "eshy", // model: NightElfShipyard	 selectScale: 5
  Nightelftransportship = "etrs", // model: NightElfTransportShip	 selectScale: 3
  Obsidiandestroyer = "ubsp", // model: ObsidianStatue	 scale: 0,85	 selectScale: 1,5
  Obsidianstatue = "uobs", // model: ObsidianStatue	 scale: 0,85	 selectScale: 2,1
  Ogre1 = "nogr", // model: Ogre	 scale: 1,25	 selectScale: 1,2
  Ogre2 = "nogm", // model: Ogre	 scale: 1,6	 selectScale: 1,2
  Ogrelord = "nogl", // model: OgreLord	 scale: 1,7	 selectScale: 2
  Ogremagi = "nomg", // model: OgreMagi	 scale: 1,4	 selectScale: 1,2
  Oldpitlord = "Npld", // model: PitLord	 scale: 1,35	 selectScale: 3
  Orcbarracks = "obar", // model: OrcBarracks	 selectScale: 4,5
  Orcishdestroyer = "odes", // model: OrcishDestroyerShip	 selectScale: 3
  Orcishtransportship = "obot", // model: OrcishTransportShip	 selectScale: 3
  Orcjuggernaut = "zjug", // model: OrcJuggernaught
  Orcshipyard = "oshy", // model: GoblinShipyard	 selectScale: 5
  OrcWarlord = "owad",
  Outlanddragonroost = "ndro", // model: DragonBuildingBlack	 scale: 1,5	 selectScale: 6,6
  Overlord = "nfov", // model: FelgaurdBlue	 scale: 1,5	 selectScale: 1,5
  Overlordarachnathid = "nano", // model: Archnathidpurple	 scale: 1,2	 selectScale: 1,8
  Owl = "nowl", // model: OwlSCOUT	 scale: 1,2	 selectScale: 1,2
  Owl2 = "now2", // model: OwlSCOUT	 scale: 1,2	 selectScale: 1,2
  Owl3 = "now3", // model: OwlSCOUT	 scale: 1,2	 selectScale: 1,2
  Owlbear = "nowb", // model: Owlbear	 scale: 1,2	 selectScale: 1,6
  Packhorse = "hrdh", // model: PackHorse	 selectScale: 1,4
  Paladin = "Hpal", // model: HeroPaladin	 selectScale: 1,25
  Paladinboss1 = "Hpb1", // model: HeroPaladinBoss	 selectScale: 1,1
  Paladinboss2 = "Hpb2", // model: HeroPaladinBoss2	 selectScale: 1,1
  Panda1 = "npn1", // model: FirePandarenBrewmaster	 scale: 0,8	 selectScale: 1,4
  Panda2 = "npn2", // model: StormPandarenBrewmaster	 scale: 0,8	 selectScale: 1,4
  Panda3 = "npn3", // model: EarthPandarenBrewmaster	 scale: 0,9	 selectScale: 1,4
  Panda4 = "npn4", // model: FirePandarenBrewmaster	 scale: 1,1	 selectScale: 1,7
  Panda5 = "npn5", // model: StormPandarenBrewmaster	 scale: 1,1	 selectScale: 1,7
  Panda6 = "npn6", // model: EarthPandarenBrewmaster	 scale: 1,2	 selectScale: 1,7
  Pandarenbrewmaster = "Npbm", // model: PandarenBrewmaster	 selectScale: 2
  Peasant = "hpea", // model: Peasant
  Penguin = "npng", // model: Penguin	 selectScale: 0,9
  Peon = "opeo", // model: Peon
  Phoenix = "hphx", // model: phoenix	 selectScale: 1,5
  Phoenixegg = "hpxe", // model: phoenix	 scale: 1,25
  Pig = "npig", // model: Pig	 selectScale: 0,9
  Pigfarm = "npgf", // model: PigFarm	 selectScale: 2,75
  Pitlord = "Nplh", // model: HeroPitLord	 selectScale: 2,5
  Plagueent = "nepl", // model: CorruptedEnt	 scale: 1,4	 selectScale: 1,45
  Plagueward = "uplg", // model: PlagueCloud	 selectScale: 0,75
  Pocketfactory = "nfac", // model: HeroTinkerFactory	 scale: 0,9	 selectScale: 3,3
  Pocketfactory2 = "nfa1", // model: HeroTinkerFactory	 scale: 0,9	 selectScale: 3,3
  Pocketfactory3 = "nfa2", // model: HeroTinkerFactory	 scale: 0,9	 selectScale: 3,3
  Poisonent = "nenp", // model: CorruptedEnt	 scale: 1,25	 selectScale: 1,35
  Polarbear = "nplb", // model: PolarBear	 scale: 0,95	 selectScale: 1,8
  Polarfurbolg = "nfpl", // model: PolarFurbolg	 scale: 0,9
  Polarfurbolgchampion = "nfpc", // model: PolarFurbolg	 scale: 1,3	 selectScale: 1,5
  Polarfurbolgeldershaman = "nfpe", // model: PolarFurbolgTracker	 scale: 1,25	 selectScale: 1,5
  Polarfurbolgshaman = "nfps", // model: PolarFurbolgTracker	 scale: 0,9
  Polarfurbolgtracker = "nfpt", // model: PolarFurbolgTracker	 scale: 1,2	 selectScale: 1,5
  Polarfurbolgursawarrior = "nfpu", // model: PolarFurbolg	 scale: 1,4	 selectScale: 1,75
  Possessedgromhellscream = "Opgh", // model: ChaosHellscream	 scale: 1,2	 selectScale: 1,15
  Powergenerator = "npgr", // model: PowerGenerator	 selectScale: 3,5
  Priest = "hmpr", // model: Priest
  Priestessofthemoon = "Emoo", // model: HeroMoonPriestess	 selectScale: 2,25
  Purplefelstalker = "npfl", // model: FelstalkerPurple	 scale: 0,8	 selectScale: 1,2
  Purplefountain = "nfnp", // model: FountainOfPower	 selectScale: 5
  Queenofsuffering = "ndqs", // model: DemonessBlue	 scale: 1,5	 selectScale: 1,5
  Quillbeast1 = "nqb1", // model: QuillBeast	 scale: 1,2	 selectScale: 1,4
  Quillbeast2 = "nqb2", // model: QuillBeast	 scale: 1,4	 selectScale: 1,6
  Quillbeast3 = "nqb3", // model: QuillBeast	 scale: 1,6	 selectScale: 1,8
  Quillbeast4 = "nqb4", // model: QuillBeast	 scale: 1,75	 selectScale: 2
  Quillboar = "nrzt", // model: Bristleback	 scale: 1,1
  Quillboarhunter = "nqbh", // model: Bristleback	 scale: 1,4
  Rabbit = "necr", // model: EasterRabbit	 selectScale: 0,9
  Raccoon = "nrac", // model: Raccoon	 selectScale: 0,9
  Rat = "nrat", // model: Rat	 selectScale: 0,9
  Razormanebrute = "nrzb", // model: RazorMane	 scale: 1,6
  Razormanechieftain = "nrzg", // model: RazorManeChief	 scale: 1,8
  Razormanemedicineman = "nrzm", // model: RazorManeChief	 scale: 1,3
  Razormanescout = "nrzs", // model: RazorMane	 scale: 1,2
  Reddragon = "nrwm", // model: RedDragon	 scale: 1,75	 selectScale: 2,25
  Reddragonroost = "ndrr", // model: DragonBuilding	 scale: 1,5	 selectScale: 6,6
  Reddragonwhelp = "nrdk", // model: RedDragonWelp	 scale: 0,7	 selectScale: 1,75
  Reddrake = "nrdr", // model: RedDragon	 scale: 1,2	 selectScale: 2
  Reefelemental = "nrel", // model: SeaElemental	 scale: 0,7	 selectScale: 1,6
  Renegadewizard = "nwzg", // model: BanditMage	 scale: 1,1	 selectScale: 1,5
  Revenantofthedepths = "ndrv", // model: RevenantOfTheWaves	 scale: 1,4
  Revenantoftheseas = "nsrv", // model: RevenantOfTheWaves	 scale: 1,05
  Revenantofthetides = "ntrv", // model: RevenantOfTheWaves	 scale: 0,9
  Rexxar = "Orex", // model: Rexxar	 selectScale: 2
  Riddenhippogryph = "ehpr", // model: RiddenHippogryph	 selectScale: 1,5
  Riderlesshorse = "hhdl", // model: KnightNoRider	 selectScale: 1,4
  Riderlesswyvern = "ownr", // model: RiderlessWyvern	 selectScale: 1,75
  Rifleman = "hrif", // model: Rifleman
  Robogoblintinker = "Nrob", // model: HeroTinker	 selectScale: 3,2
  Rocketengine = "hrtt", // model: WarWagon	 selectScale: 2,5
  Rockgolem = "ngst", // model: RockGolem	 scale: 1,05	 selectScale: 1,85
  Rogue = "nrog", // model: Bandit	 scale: 1,3
  Roguewizard = "nwzr", // model: BanditMage	 scale: 0,9	 selectScale: 1,5
  Rokhan = "Orkn", // model: HeroShadowHunter	 selectScale: 1,2
  Ruinedelvenfishingvillage0 = "nvr0", // model: ElvenFishVillageBuildingRuined0	 selectScale: 3,5
  Ruinedelvenfishingvillage1 = "nvr1", // model: ElvenFishVillageBuildingRuined1	 selectScale: 3,5
  Ruinedelvenfishingvillage2 = "nvr2", // model: ElvenFishVillageBuildingRuined2	 selectScale: 3,5
  Sacrificialpit = "usap", // model: SacrificialPit	 selectScale: 4,5
  Salamander = "nslr", // model: ThunderLizardSalamander	 scale: 0,95	 selectScale: 2,5
  Salamanderhatchling = "nslh", // model: ThunderLizardSalamander	 scale: 0,6	 selectScale: 2,5
  Salamanderlord = "nsll", // model: ThunderLizardSalamander	 scale: 1,25	 selectScale: 2,5
  Salamandervizier = "nslv", // model: ThunderLizardVizier	 scale: 1,1	 selectScale: 2,5
  Sammycube = "zsmc", // model: SammyCube	 selectScale: 1,2
  Samuro = "Osam", // model: HeroBladeMaster	 selectScale: 1,25
  Sasquatch = "nsqt", // model: Sasquatch	 selectScale: 1,2
  Sasquatchoracle = "nsqo", // model: Sasquatch	 scale: 1,35	 selectScale: 1,25
  Satyr = "nsty", // model: Satyr	 scale: 1,15
  Satyrhellcaller = "nsth", // model: satyrhellcaller	 scale: 1,05	 selectScale: 1,25
  Satyrshadowdancer = "nsts", // model: SatyrTrickster	 scale: 1,6
  Satyrsoulstealer = "nstl", // model: Satyr	 scale: 1,8
  Satyrtrickster = "nsat", // model: SatyrTrickster
  Scouttower = "hwtw", // model: HumanTower	 selectScale: 2,5
  Seaelemental = "nsel", // model: SeaElemental	 scale: 1,1	 selectScale: 1,6
  Seagiant = "nsgn", // model: SeaGiant	 scale: 0,8	 selectScale: 2
  Seagiantbehemoth = "nsgb", // model: SeaGiant	 scale: 1,2	 selectScale: 3
  Seagianthunter = "nsgh", // model: SeaGiantGreen	 selectScale: 2,4
  Seal = "nsea", // model: Seal
  Searinox = "nser", // model: BlackDragon	 scale: 1,4	 selectScale: 2,25
  Seaturtle = "ntrs", // model: SeaTurtle	 scale: 0,5	 selectScale: 2
  Seaturtlehatchling = "ntrh", // model: SeaTurtleRange	 scale: 0,4	 selectScale: 1,5
  Seawitch = "Nngs", // model: HeroNagaSeawitch	 selectScale: 2
  Sentryward = "oeye", // model: SentryWard	 selectScale: 0,75
  Serpentward1 = "osp1", // model: SerpentWard	 selectScale: 0,75
  Serpentward2 = "osp2", // model: SerpentWard	 selectScale: 0,75
  Serpentward3 = "osp3", // model: SerpentWard	 selectScale: 0,75
  Serpentward4 = "osp4", // model: SerpentWard	 selectScale: 0,75
  Shade = "ushd", // model: Shade
  Shadowhunter = "Oshd", // model: HeroShadowHunter	 selectScale: 1,2
  Shaman = "oshm", // model: Shaman	 selectScale: 1,15
  Shandris = "eshd", // model: Shandris	 scale: 1,1
  Sheep = "nshe", // model: Sheep	 scale: 1,2	 selectScale: 0,9
  Shimmeringportal = "hprt", // model: ShimmeringPortal	 selectScale: 3,5
  Shrine = "nshr", // model: SacrificialAltar	 selectScale: 4
  Shrineofazshara = "nnsa", // model: ShrineOfAshjara	 scale: 0,9	 selectScale: 4,5
  Siegeengine = "hmtt", // model: WarWagon	 selectScale: 2,5
  Siegegolem = "nsgg", // model: GolemStatue	 scale: 1,5	 selectScale: 2,3
  Sinjostormstout = "Nsjs", // model: PandarenBrewmaster	 selectScale: 2
  Siren = "nnsw", // model: NagaSiren
  Skeletalarcher = "nska", // model: SkeletonArcher
  Skeletalarchersummoned = "nsca", // model: SkeletonArcher
  Skeletalmage = "uskm", // model: SkeletonMage
  Skeletalmarksman = "nskm", // model: SkeletonArcher	 scale: 1,3
  Skeletalorc = "nsko", // model: SkeletonOrc	 scale: 1,1
  Skeletalorcchampion = "nsoc", // model: SkeletonOrc	 scale: 1,5	 selectScale: 1,25
  Skeletalorcgrunt = "nsog", // model: SkeletonOrc	 scale: 1,3
  Skeleton = "nske", // model: Skeleton
  Skeletonsummoned = "nsce", // model: Skeleton
  Skeletonwarrior = "uske", // model: Skeleton
  Skink = "nskk", // model: Skink	 selectScale: 0,9
  Skyfurytower = "negm", // model: ElvenGuardMagicTower	 selectScale: 2,5
  Slaughterhouse = "uslh", // model: Slaughterhouse	 selectScale: 4,25
  Sludgeflinger = "nslf", // model: SludgeMonster	 scale: 1,3	 selectScale: 2
  Sludgeminion = "nslm", // model: SludgeMonster	 scale: 0,75
  Sludgemonstrosity = "nsln", // model: SludgeMonster	 scale: 1,8	 selectScale: 3
  Snapdragon = "nsnp", // model: SnapDragon	 selectScale: 2
  Snapdragonmorph = "nsbs", // model: SnapDragon	 selectScale: 1,75
  Snowyowl = "nsno", // model: SnowOwl	 scale: 1,2	 selectScale: 0,8
  Sorceress = "hsor", // model: Sorceress
  Spawninggrounds = "nnsg", // model: SpawningGrounds	 selectScale: 5
  Spellbreaker = "hspt", // model: BloodElfSpellThief	 scale: 0,8	 selectScale: 1,2
  Spider = "nspr", // model: Spider	 scale: 0,5	 selectScale: 1,1
  Spiderblack = "nspb", // model: SpiderBlack	 selectScale: 1,1
  Spidercrab = "nscb", // model: SpiderCrabCreep	 selectScale: 1,2
  Spidercrab2 = "nsc2", // model: SpiderCrabCreep	 scale: 1,2	 selectScale: 1,5
  Spidercrab3 = "nsc3", // model: SpiderCrabCreep	 scale: 1,35	 selectScale: 1,72
  Spiderling = "nspd", // model: Nerubian	 scale: 0,6	 selectScale: 1,5
  Spiritbeast = "nsw1", // model: FelstalkerPurple	 scale: 0,8
  Spiritbeast2 = "nsw2", // model: FelstalkerPurple	 scale: 1,15	 selectScale: 1,7
  Spiritbeast3 = "nsw3", // model: FelstalkerPurple	 scale: 1,4	 selectScale: 2,5
  Spiritlodge = "osld", // model: SpiritLodge	 selectScale: 3,5
  Spiritofvengeance = "espv", // model: SpiritOfVengeance	 selectScale: 2
  Spiritpig = "nspp", // model: SpiritPig	 selectScale: 1,25
  Spiritwalker = "ospw", // model: spiritwalker	 selectScale: 1,15
  Spiritwalkermorph = "ospm", // model: spiritwalker	 selectScale: 1,15
  Spiritwolf1 = "osw1", // model: Spiritwolf	 scale: 0,9	 selectScale: 1,25
  Spiritwolf2 = "osw2", // model: Spiritwolf	 scale: 1,1	 selectScale: 1,5
  Spiritwolf3 = "osw3", // model: Spiritwolf	 scale: 1,3	 selectScale: 1,75
  Spiritwyvern = "oswy", // model: SpiritWyvern	 selectScale: 1,75
  Spittingspider = "nssp", // model: SpiderBlue	 selectScale: 1,5
  Stasistraptotem = "otot", // model: StasisTotem	 selectScale: 0,75
  Stonemaulmagi = "nogn", // model: OgreMagi	 scale: 1,6	 selectScale: 1,75
  Stonemaulogre = "nogo", // model: OgreOneHeaded	 scale: 1,6	 selectScale: 1,75
  Stonemaulwarchief = "noga", // model: OgreOneHeadedArmored	 scale: 2,1	 selectScale: 2,2
  Stormreaverapprentice = "nsra", // model: OrcWarlock	 scale: 0,9	 selectScale: 1,1
  Stormreaverhermit = "nsrh", // model: OrcWarlock	 selectScale: 1,25
  Stormreavernecrolyte = "nsrn", // model: OrcWarlock	 scale: 1,25	 selectScale: 1,25
  Stormreaverwarlock = "nsrw", // model: OrcWarlock	 scale: 1,5	 selectScale: 1,25
  Stormwyrm = "nstw", // model: ThunderLizard	 scale: 1,4	 selectScale: 3
  Stronghold = "ostr", // model: GreatHall	 selectScale: 6,6
  Succubus = "ndqn", // model: Demoness
  Summoner = "nnsu", // model: NagaSummoner
  Supportcolumn = "nspc", // model: SupportBeam	 selectScale: 3
  Sylvanusbanshee = "uswb", // model: BansheeGhost	 scale: 1,3	 selectScale: 1,3
  Sylvanuswindrunner = "Hvwd", // model: SylvanusWindrunner	 scale: 1,1	 selectScale: 1,5
  Tauren = "otau", // model: Tauren	 scale: 1,1	 selectScale: 1,6
  Taurenchieftain = "Otch", // model: HeroTaurenChieftain	 scale: 1,1	 selectScale: 2
  Taurentent = "ntnt", // model: TaurenTent	 selectScale: 2,5
  Taurentent2 = "ntt2", // model: TaurenTent2	 selectScale: 2,5
  Taurentotem = "otto", // model: TaurenTotem	 selectScale: 3,25
  Templeofthedamned = "utod", // model: TempleOfTheDamned	 selectScale: 4,25
  Templeoftides = "nntt", // model: TempleofTides	 selectScale: 5,5
  Tent = "nten", // model: Tent	 selectScale: 3
  Tent2 = "ntn2", // model: Tent1	 selectScale: 3
  Tentacle = "nfgt", // model: ForgottenOneTent	 selectScale: 0,75
  Tharifas = "nthr", // model: GreenDragon	 scale: 1,4	 selectScale: 2,25
  Thecaptain = "hcth", // model: TheCaptain	 scale: 1,15	 selectScale: 1,2
  Theshoveler = "zshv", // model: Shoveler	 scale: 0,85	 selectScale: 1,2
  Thrall = "Othr", // model: Thrall	 selectScale: 2
  Thunderlizard = "nthl", // model: ThunderLizard	 scale: 1,15	 selectScale: 2,5
  Tichondrius = "Utic", // model: Tichondrius	 scale: 1,15	 selectScale: 2
  Tidalguardian = "nntg", // model: TidalGuardian	 selectScale: 3,25
  Timberwolf = "nwlt", // model: TimberWolf	 scale: 0,75	 selectScale: 1,1
  Tinker = "Ntin", // model: HeroTinker	 selectScale: 2
  Tombofrelics = "utom", // model: TombOfRelics	 selectScale: 5,5
  Tornado = "ntor", // model: TornadoElemental
  Townhall = "htow", // model: TownHall	 selectScale: 6,3
  Transportship = "nbot", // model: HumanTransportShip	 selectScale: 3,5
  Treasurebox = "nitb", // model: IceCrownTreasureBox	 selectScale: 3,3
  Treeofages = "etoa", // model: TreeofLife	 scale: 1,15	 selectScale: 4,75
  Treeofeternity = "etoe", // model: TreeofLife	 scale: 1,3	 selectScale: 4,75
  Treeoflife = "etol", // model: TreeofLife	 selectScale: 4,75
  Trollbatrider = "otbr", // model: BatTroll	 selectScale: 1,75
  Trollburrow = "otrb", // model: TrollBurrow	 selectScale: 2,75
  Tuskarrchieftain = "ntkc", // model: tuskarLord	 scale: 1,25	 selectScale: 2
  Tuskarrfighter = "ntkf", // model: tuskar	 scale: 0,75	 selectScale: 1,25
  Tuskarrhealer = "ntkh", // model: tuskarLord	 scale: 0,75	 selectScale: 1,25
  Tuskarrsorceror = "ntks", // model: tuskarRanged	 selectScale: 1,66
  Tuskarrspearman = "ntka", // model: tuskarRanged	 scale: 0,75	 selectScale: 1,25
  Tuskarrtrapper = "ntkt", // model: tuskarRanged	 selectScale: 1,66
  Tuskarrwarrior = "ntkw", // model: tuskarLord	 selectScale: 1,66
  Tyrande = "Etyr", // model: HeroMoonPriestess	 selectScale: 2,25
  Unbrokendarkhunter = "nubk", // model: Unbroken	 scale: 0,55	 selectScale: 1,25
  Unbrokendarkweaver = "nubw", // model: Unbroken	 scale: 0,7	 selectScale: 1,75
  Unbrokenrager = "nubr", // model: Unbroken	 scale: 0,65	 selectScale: 1,5
  Undeadbattleship = "uubs", // model: UndeadShipBattleShip	 selectScale: 4
  Undeaddestroyer = "udes", // model: UndeadDestroyerShip	 selectScale: 3
  Undeadgoldmine2 = "ugol", // model: HauntedMine	 selectScale: 5,5
  Undeadshipyard = "ushp", // model: UndeadShipyard	 selectScale: 4,75
  Undeadtransportship = "ubot", // model: UndeadTransportShip	 selectScale: 3
  Uther = "Huth", // model: Uther	 scale: 1,1	 selectScale: 1,1
  Varimathras = "Uvar", // model: Tichondrius	 scale: 1,2	 selectScale: 1,75
  Vengeance = "even", // model: Vengeance
  Vengyr = "Uvng", // model: HeroDreadLord	 scale: 1,15	 selectScale: 2
  Viletemptress = "ndqt", // model: Demoness	 scale: 1,4	 selectScale: 1,4
  Viletormentor = "ndqv", // model: DemonessBlue	 scale: 1,2	 selectScale: 1,2
  Villagerkid = "nvlk", // model: VillagerKid	 scale: 1,2	 selectScale: 0,75
  Villagerkid2 = "nvk2", // model: VillagerKid1	 scale: 1,2	 selectScale: 0,75
  Villagerman = "nvil", // model: VillagerMan	 scale: 1,2
  Villagerman2 = "nvl2", // model: VillagerMan1	 scale: 1,2
  Villagerwoman = "nvlw", // model: VillagerWoman	 scale: 1,05
  Voidwalker = "nvdw", // model: VoidWalker	 scale: 1,15	 selectScale: 1,2
  Voljin = "ovlj", // model: WitchDoctor
  Voodoolounge = "ovln", // model: VoodooLounge	 selectScale: 4,5
  Vulture = "nvul", // model: Vulture
  War2warlock = "nw2w", // model: ChaosWarlockGreen	 selectScale: 1,15
  Warden = "Ewar", // model: herowarden	 selectScale: 1,5
  Wareagle1 = "nwe1", // model: WarEagle	 scale: 0,9	 selectScale: 1,25
  Wareagle2 = "nwe2", // model: WarEagle	 scale: 1,1	 selectScale: 1,5
  Wareagle3 = "nwe3", // model: WarEagle	 scale: 1,3	 selectScale: 1,75
  Wargolem = "nwrg", // model: GolemStatue	 scale: 1,25	 selectScale: 1,9
  Warmill = "ofor", // model: WarMill	 selectScale: 3,5
  Warriorarachnathid = "nanw", // model: ArchnathidGreen	 scale: 0,9	 selectScale: 1,6
  Watcher = "nwat", // model: watcher
  Watcherward = "nwad", // model: WatcherWard	 selectScale: 0,75
  Watchtower = "owtw", // model: WatchTower	 selectScale: 2,5
  Waterelemental1 = "hwat", // model: WaterElemental	 scale: 0,9	 selectScale: 1,6
  Waterelemental2 = "hwt2", // model: WaterElemental	 scale: 1,1	 selectScale: 1,6
  Waterelemental3 = "hwt3", // model: WaterElemental	 scale: 1,3	 selectScale: 1,6
  Waterpenguin = "npnw", // model: Penguin	 selectScale: 0,9
  Watersheep = "nshw", // model: Sheep	 scale: 1,2	 selectScale: 0,9
  Wateryminioncliffrunner = "ncfs", // model: MurgulTideWarrior	 scale: 0,8	 selectScale: 0,8
  Wateryminionsnarecaster = "nsns", // model: MurgulShadowCaster	 scale: 1,1	 selectScale: 1,1
  Wateryminiontidewarrior = "ntws", // model: MurgulTideWarrior
  Waygate = "nwgt", // model: Waygate	 selectScale: 3,5
  Wendigo1 = "nwen", // model: Wendigo	 scale: 0,9	 selectScale: 1,2
  Wendigoshaman = "nwns", // model: WendigoShaman	 scale: 1,2	 selectScale: 1,2
  Whitedirewolf = "nwwd", // model: WhiteWolf	 scale: 1,45	 selectScale: 2
  Whitewolf = "nwwf", // model: WhiteWolf	 selectScale: 1,25
  Windrider = "owyv", // model: WyvernRider	 selectScale: 1,75
  Windserpent = "nws1", // model: WindSerpent	 scale: 1,2	 selectScale: 1,25
  Wisp = "ewsp", // model: Wisp
  Witchdoctor = "odoc", // model: WitchDoctor
  Wolfrider = "orai", // model: WolfRider	 selectScale: 1,6
  Workshop = "harm", // model: Workshop	 selectScale: 4,25
  Wraith = "ngh2", // model: BansheeGhost	 scale: 1,4
  Wyverncage1 = "nwc1", // model: WyvernCage	 selectScale: 3,3
  Wyverncage2 = "nwc2", // model: WyvernCage2	 selectScale: 3,3
  Zergling = "zzrg", // model: zergling
  Ziggurat = "uzig", // model: Ziggurat	 selectScale: 4,25
  Ziggurat1 = "uzg1", // model: Ziggurat	 selectScale: 4,25
  Zombie = "nzom", // model: Zombie	 scale: 1,15
  Zoneindicator = "nzin", // model: IntentionallyLeftBlank
}
