/** @format */

/** These are the default base frame types, to be used as typeName for createFrameByType(..) [BlzCreateFrameByType]
		  or inside of the frame definition files (fdf) */
export const enum FrameType {
  /** The frame type BUTTON is used for normal clickable button */
  buttonframe = "BUTTON",
  /** The frame type GLUEBUTTON is used for clickable button, mouse hovering glows. */
  gluebutton = "GLUEBUTTON",
  /** The frame type TEXTBUTTON is used for clickable TextButtons with text */
  textbutton = "TEXTBUTTON",
  /** The frame type GLUETEXTBUTTON is used for clickable TextButtons, mouse hovering glows. */
  gluetextbutton = "GLUETEXTBUTTON",
  /** The frame type TEXT is used for visible text. */
  text = "TEXT",
  /** The frame type BACKDROP is used for backgrounds, borders or images. */
  backdrop = "BACKDROP",
  /** The frame type EDITBOX is used for text input by user. */
  editbox = "EDITBOX",
  /** The frame type SLIDER is used for user can select a value between an upper and a lower Value. */
  slider = "SLIDER",
  /** The frame type TEXTAREA is used for ui-Frames for big Texts also include scrollbars on default. */
  textarea = "TEXTAREA",
  /** The frame type CHECKBOX is used for checkable checkbox */
  checkbox = "CHECKBOX",
  /** The frame type GLUECHECKBOX is used for checkable checkbox, mouse hovering glows. */
  gluecheckbox = "GLUECHECKBOX",
  /** The frame type POPUPMENU is used for used for menus that is designed for hovering over other frames */
  popupmenu = "POPUPMENU",
  /** The frame type MENU is used for general menu frame designed to be displayed behind popupmenus */
  menu = "MENU",
  /** The frame type SCROLLBAR is used for scrollbar that can be added to backdrops do change content (e.g. for textareas) */
  scrollbar = "SCROLLBAR",
  /** The frame type CONTROL is used for special frame that is designed for handling several control elements like buttons, checkboxes etc. */
  control = "CONTROL",
  /** The frame type SIMPLEFRAME is used for a less complex definition for frames, that does not allow different inherit types */
  simpleframe = "SIMPLEFRAME",
  /** The frame type DIALOG is used for nothing special, (origin SuspendDialogs will pause the game in singleplayer) */
  dialogframe = "DIALOG",
  /** The frame type HIGHLIGHT is used for frame template to define how buttons/texts are highlight on hovering/click/enter/focus of the mouse */
  highlight = "HIGHLIGHT",
  frame = "FRAME",
}

export interface IFrames {
  name: string
  context: number[]
}

export const FramePoint = {
  C: FRAMEPOINT_CENTER,
  T: FRAMEPOINT_TOP,
  B: FRAMEPOINT_BOTTOM,
  TL: FRAMEPOINT_TOPLEFT,
  TR: FRAMEPOINT_TOPRIGHT,
  BL: FRAMEPOINT_BOTTOMLEFT,
  BR: FRAMEPOINT_BOTTOMRIGHT,
  L: FRAMEPOINT_LEFT,
  R: FRAMEPOINT_RIGHT,
}

export const Frames = {
  AllianceAcceptButton: { name: "AllianceAcceptButton", context: [0] },
  AllianceAcceptButtonText: { name: "AllianceAcceptButtonText", context: [0] },
  AllianceBackdrop: { name: "AllianceBackdrop", context: [0] },
  AllianceCancelButton: { name: "AllianceCancelButton", context: [0] },
  AllianceCancelButtonText: { name: "AllianceCancelButtonText", context: [0] },
  AllianceDialog: { name: "AllianceDialog", context: [0] },
  AllianceDialogScrollBar: { name: "AllianceDialogScrollBar", context: [0] },
  AllianceSlot: { name: "AllianceSlot", context: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23] },
  AllianceTitle: { name: "AllianceTitle", context: [0] },
  AlliedVictoryCheckBox: { name: "AlliedVictoryCheckBox", context: [0] },
  AlliedVictoryLabel: { name: "AlliedVictoryLabel", context: [0] },
  AllyCheckBox: { name: "AllyCheckBox", context: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23] },
  AllyHeader: { name: "AllyHeader", context: [0] },
  AmbientCheckBox: { name: "AmbientCheckBox", context: [0] },
  AmbientLabel: { name: "AmbientLabel", context: [0] },
  AnimQualityLabel: { name: "AnimQualityLabel", context: [0] },
  AnimQualityValue: { name: "AnimQualityValue", context: [0] },
  BottomButtonPanel: { name: "BottomButtonPanel", context: [0] },
  ButtonBackdropTemplate: { name: "ButtonBackdropTemplate", context: [0] },
  ButtonDisabledBackdropTemplate: { name: "ButtonDisabledBackdropTemplate", context: [0] },
  ButtonDisabledPushedBackdropTemplate: { name: "ButtonDisabledPushedBackdropTemplate", context: [0] },
  ButtonPushedBackdropTemplate: { name: "ButtonPushedBackdropTemplate", context: [0] },
  CancelButtonText: { name: "CancelButtonText", context: [0] },
  ChatDialog: { name: "ChatDialog", context: [0] },
  ChatBackdrop: { name: "ChatBackdrop", context: [0] },
  ChatTitle: { name: "ChatTitle", context: [0] },
  ChatPlayerRadioButton: { name: "ChatPlayerRadioButton", context: [0] },
  ChatAlliesRadioButton: { name: "ChatAlliesRadioButton", context: [0] },
  ChatObserversRadioButton: { name: "ChatObserversRadioButton", context: [0] },
  ChatEveryoneRadioButton: { name: "ChatEveryoneRadioButton", context: [0] },
  ChatPlayerLabel: { name: "ChatPlayerLabel", context: [0] },
  ChatAlliesLabel: { name: "ChatAlliesLabel", context: [0] },
  ChatObserversLabel: { name: "ChatObserversLabel", context: [0] },
  ChatEveryoneLabel: { name: "ChatEveryoneLabel", context: [0] },
  ChatPlayerMenu: { name: "ChatPlayerMenu", context: [0] },
  ChatAcceptButton: { name: "ChatAcceptButton", context: [0] },
  ChatAcceptButtonText: { name: "ChatAcceptButtonText", context: [0] },
  ChatHistoryDisplayBackdrop: { name: "ChatHistoryDisplayBackdrop", context: [0] },
  ChatHistoryDisplay: { name: "ChatHistoryDisplay", context: [0] },
  ChatHistoryScrollBar: { name: "ChatHistoryScrollBar", context: [0] },
  ChatHistoryLabel: { name: "ChatHistoryLabel", context: [0] },
  ChatInfoText: { name: "ChatInfoText", context: [0] },
  CinematicBottomBorder: { name: "CinematicBottomBorder", context: [0] },
  CinematicDialogueText: { name: "CinematicDialogueText", context: [0] },
  CinematicPanel: { name: "CinematicPanel", context: [0] },
  CinematicPortrait: { name: "CinematicPortrait", context: [0] },
  CinematicPortraitBackground: { name: "CinematicPortraitBackground", context: [0] },
  CinematicPortraitCover: { name: "CinematicPortraitCover", context: [0] },
  CinematicScenePanel: { name: "CinematicScenePanel", context: [0] },
  CinematicSpeakerText: { name: "CinematicSpeakerText", context: [0] },
  CinematicTopBorder: { name: "CinematicTopBorder", context: [0] },
  ColorBackdrop: { name: "ColorBackdrop", context: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23] },
  ColorBorder: { name: "ColorBorder", context: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23] },
  CommandButton0: { name: "CommandButton_0", context: [0] },
  CommandButton1: { name: "CommandButton_1", context: [0] },
  CommandButton2: { name: "CommandButton_2", context: [0] },
  CommandButton3: { name: "CommandButton_3", context: [0] },
  CommandButton4: { name: "CommandButton_4", context: [0] },
  CommandButton5: { name: "CommandButton_5", context: [0] },
  CommandButton6: { name: "CommandButton_6", context: [0] },
  CommandButton7: { name: "CommandButton_7", context: [0] },
  CommandButton8: { name: "CommandButton_8", context: [0] },
  CommandButton9: { name: "CommandButton_9", context: [0] },
  CommandButton10: { name: "CommandButton_10", context: [0] },
  CommandButton11: { name: "CommandButton_11", context: [0] },
  ConfirmQuitCancelButton: { name: "ConfirmQuitCancelButton", context: [0] },
  ConfirmQuitCancelButtonText: { name: "ConfirmQuitCancelButtonText", context: [0] },
  ConfirmQuitMessageText: { name: "ConfirmQuitMessageText", context: [0] },
  ConfirmQuitPanel: { name: "ConfirmQuitPanel", context: [0] },
  ConfirmQuitQuitButton: { name: "ConfirmQuitQuitButton", context: [0] },
  ConfirmQuitQuitButtonText: { name: "ConfirmQuitQuitButtonText", context: [0] },
  ConfirmQuitTitleText: { name: "ConfirmQuitTitleText", context: [0] },
  ConsoleUI: { name: "ConsoleUI", context: [0] },
  consoleUIBackdrop: { name: "ConsoleUIBackdrop", context: [0] },
  CustomKeysLabel: { name: "CustomKeysLabel", context: [0] },
  CustomKeysValue: { name: "CustomKeysValue", context: [0] },
  DecoratedMapListBox: { name: "DecoratedMapListBox", context: [0] },
  DeleteCancelButton: { name: "DeleteCancelButton", context: [0] },
  DeleteCancelButtonText: { name: "DeleteCancelButtonText", context: [0] },
  DeleteDeleteButton: { name: "DeleteDeleteButton", context: [0] },
  DeleteDeleteButtonText: { name: "DeleteDeleteButtonText", context: [0] },
  DeleteMessageText: { name: "DeleteMessageText", context: [0] },
  DeleteOnly: { name: "DeleteOnly", context: [0] },
  DeleteTitleText: { name: "DeleteTitleText", context: [0] },
  DifficultyLabel: { name: "DifficultyLabel", context: [0] },
  DifficultyValue: { name: "DifficultyValue", context: [0] },
  EndGameButton: { name: "EndGameButton", context: [0] },
  EndGameButtonText: { name: "EndGameButtonText", context: [0] },
  EndGamePanel: { name: "EndGamePanel", context: [0] },
  EndGameTitleText: { name: "EndGameTitleText", context: [0] },
  EnviroCheckBox: { name: "EnviroCheckBox", context: [0] },
  EnviroLabel: { name: "EnviroLabel", context: [0] },
  EscMenuBackdrop: { name: "EscMenuBackdrop", context: [0] },
  EscMenuDeleteContainer: { name: "EscMenuDeleteContainer", context: [0] },
  EscMenuMainPanel: { name: "EscMenuMainPanel", context: [0] },
  EscMenuOptionsPanel: { name: "EscMenuOptionsPanel", context: [0] },
  EscMenuOverwriteContainer: { name: "EscMenuOverwriteContainer", context: [0] },
  EscMenuSaveGamePanel: { name: "EscMenuSaveGamePanel", context: [0] },
  EscMenuSaveLoadContainer: { name: "EscMenuSaveLoadContainer", context: [0] },
  EscOptionsLightsMenu: { name: "EscOptionsLightsMenu", context: [0] },
  EscOptionsLightsPopupMenuArrow: { name: "EscOptionsLightsPopupMenuArrow", context: [0] },
  EscOptionsLightsPopupMenuBackdrop: { name: "EscOptionsLightsPopupMenuBackdrop", context: [0] },
  EscOptionsLightsPopupMenuDisabledBackdrop: { name: "EscOptionsLightsPopupMenuDisabledBackdrop", context: [0] },
  EscOptionsLightsPopupMenuMenu: { name: "EscOptionsLightsPopupMenuMenu", context: [0] },
  EscOptionsLightsPopupMenuTitle: { name: "EscOptionsLightsPopupMenuTitle", context: [0] },
  EscOptionsOcclusionMenu: { name: "EscOptionsOcclusionMenu", context: [0] },
  EscOptionsOcclusionPopupMenuArrow: { name: "EscOptionsOcclusionPopupMenuArrow", context: [0] },
  EscOptionsOcclusionPopupMenuBackdrop: { name: "EscOptionsOcclusionPopupMenuBackdrop", context: [0] },
  EscOptionsOcclusionPopupMenuDisabledBackdrop: { name: "EscOptionsOcclusionPopupMenuDisabledBackdrop", context: [0] },
  EscOptionsOcclusionPopupMenuMenu: { name: "EscOptionsOcclusionPopupMenuMenu", context: [0] },
  EscOptionsOcclusionPopupMenuTitle: { name: "EscOptionsOcclusionPopupMenuTitle", context: [0] },
  EscOptionsParticlesMenu: { name: "EscOptionsParticlesMenu", context: [0] },
  EscOptionsParticlesPopupMenuArrow: { name: "EscOptionsParticlesPopupMenuArrow", context: [0] },
  EscOptionsParticlesPopupMenuBackdrop: { name: "EscOptionsParticlesPopupMenuBackdrop", context: [0] },
  EscOptionsParticlesPopupMenuDisabledBackdrop: { name: "EscOptionsParticlesPopupMenuDisabledBackdrop", context: [0] },
  EscOptionsParticlesPopupMenuMenu: { name: "EscOptionsParticlesPopupMenuMenu", context: [0] },
  EscOptionsParticlesPopupMenuTitle: { name: "EscOptionsParticlesPopupMenuTitle", context: [0] },
  EscOptionsResolutionMenu: { name: "EscOptionsResolutionMenu", context: [0] },
  EscOptionsResolutionPopupMenuArrow: { name: "EscOptionsResolutionPopupMenuArrow", context: [0] },
  EscOptionsResolutionPopupMenuBackdrop: { name: "EscOptionsResolutionPopupMenuBackdrop", context: [0] },
  EscOptionsResolutionPopupMenuDisabledBackdrop: { name: "EscOptionsResolutionPopupMenuDisabledBackdrop", context: [0] },
  EscOptionsResolutionPopupMenuMenu: { name: "EscOptionsResolutionPopupMenuMenu", context: [0] },
  EscOptionsResolutionPopupMenuTitle: { name: "EscOptionsResolutionPopupMenuTitle", context: [0] },
  EscOptionsShadowsMenu: { name: "EscOptionsShadowsMenu", context: [0] },
  EscOptionsShadowsPopupMenuArrow: { name: "EscOptionsShadowsPopupMenuArrow", context: [0] },
  EscOptionsShadowsPopupMenuBackdrop: { name: "EscOptionsShadowsPopupMenuBackdrop", context: [0] },
  EscOptionsShadowsPopupMenuDisabledBackdrop: { name: "EscOptionsShadowsPopupMenuDisabledBackdrop", context: [0] },
  EscOptionsShadowsPopupMenuMenu: { name: "EscOptionsShadowsPopupMenuMenu", context: [0] },
  EscOptionsShadowsPopupMenuTitle: { name: "EscOptionsShadowsPopupMenuTitle", context: [0] },
  EscOptionsWindowModeMenu: { name: "EscOptionsWindowModeMenu", context: [0] },
  EscOptionsWindowModePopupMenuArrow: { name: "EscOptionsWindowModePopupMenuArrow", context: [0] },
  EscOptionsWindowModePopupMenuBackdrop: { name: "EscOptionsWindowModePopupMenuBackdrop", context: [0] },
  EscOptionsWindowModePopupMenuDisabledBackdrop: { name: "EscOptionsWindowModePopupMenuDisabledBackdrop", context: [0] },
  EscOptionsWindowModePopupMenuMenu: { name: "EscOptionsWindowModePopupMenuMenu", context: [0] },
  EscOptionsWindowModePopupMenuTitle: { name: "EscOptionsWindowModePopupMenuTitle", context: [0] },
  ExitButton: { name: "ExitButton", context: [0] },
  ExitButtonText: { name: "ExitButtonText", context: [0] },
  ExtraHighLatencyLabel: { name: "ExtraHighLatencyLabel", context: [0] },
  ExtraHighLatencyRadio: { name: "ExtraHighLatencyRadio", context: [0] },
  FileListFrame: { name: "FileListFrame", context: [0] },
  ForamtionButton: { name: "FormationButton", context: [0] },
  FormationToggleCheckBox: { name: "FormationToggleCheckBox", context: [0] },
  FormationToggleLabel: { name: "FormationToggleLabel", context: [0] },
  GameplayButton: { name: "GameplayButton", context: [0] },
  GameplayButtonText: { name: "GameplayButtonText", context: [0] },
  GameplayPanel: { name: "GameplayPanel", context: [0] },
  GameplayTitleText: { name: "GameplayTitleText", context: [0] },
  GameSpeedLabel: { name: "GameSpeedLabel", context: [0] },
  GameSpeedSlider: { name: "GameSpeedSlider", context: [0] },
  GameSpeedValue: { name: "GameSpeedValue", context: [0] },
  GammaBrightLabel: { name: "GammaBrightLabel", context: [0] },
  GammaDarkLabel: { name: "GammaDarkLabel", context: [0] },
  GammaLabel: { name: "GammaLabel", context: [0] },
  GammaSlider: { name: "GammaSlider", context: [0] },
  GoldBackdrop: { name: "GoldBackdrop", context: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23] },
  GoldHeader: { name: "GoldHeader", context: [0] },
  GoldText: { name: "GoldText", context: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23] },
  HealthBarsCheckBox: { name: "HealthBarsCheckBox", context: [0] },
  HealthBarsLabel: { name: "HealthBarsLabel", context: [0] },
  HelpButton: { name: "HelpButton", context: [0] },
  HelpButtonText: { name: "HelpButtonText", context: [0] },
  HelpOKButton: { name: "HelpOKButton", context: [0] },
  HelpOKButtonText: { name: "HelpOKButtonText", context: [0] },
  HelpPanel: { name: "HelpPanel", context: [0] },
  HelpTextArea: { name: "HelpTextArea", context: [0] },
  HelpTitleText: { name: "HelpTitleText", context: [0] },
  HighLatencyLabel: { name: "HighLatencyLabel", context: [0] },
  HighLatencyRadio: { name: "HighLatencyRadio", context: [0] },
  InfoPanelIconAllyFoodIcon: { name: "InfoPanelIconAllyFoodIcon", context: [7] },
  InfoPanelIconAllyFoodValue: { name: "InfoPanelIconAllyFoodValue", context: [7] },
  InfoPanelIconAllyGoldIcon: { name: "InfoPanelIconAllyGoldIcon", context: [7] },
  InfoPanelIconAllyGoldValue: { name: "InfoPanelIconAllyGoldValue", context: [7] },
  InfoPanelIconAllyTitle: { name: "InfoPanelIconAllyTitle", context: [7] },
  InfoPanelIconAllyUpkeep: { name: "InfoPanelIconAllyUpkeep", context: [7] },
  InfoPanelIconAllyWoodIcon: { name: "InfoPanelIconAllyWoodIcon", context: [7] },
  InfoPanelIconAllyWoodValue: { name: "InfoPanelIconAllyWoodValue", context: [7] },
  InfoPanelIconBackdrop: { name: "InfoPanelIconBackdrop", context: [0, 1, 2, 3, 4, 5] },
  InfoPanelIconHeroAgilityLabel: { name: "InfoPanelIconHeroAgilityLabel", context: [6] },
  InfoPanelIconHeroAgilityValue: { name: "InfoPanelIconHeroAgilityValue", context: [6] },
  InfoPanelIconHeroIcon: { name: "InfoPanelIconHeroIcon", context: [6] },
  InfoPanelIconHeroIntellectLabel: { name: "InfoPanelIconHeroIntellectLabel", context: [6] },
  InfoPanelIconHeroIntellectValue: { name: "InfoPanelIconHeroIntellectValue", context: [6] },
  InfoPanelIconHeroStrengthLabel: { name: "InfoPanelIconHeroStrengthLabel", context: [6] },
  InfoPanelIconHeroStrengthValue: { name: "InfoPanelIconHeroStrengthValue", context: [6] },
  InfoPanelIconLabel: { name: "InfoPanelIconLabel", context: [0, 1, 2, 3, 4, 5] },
  InfoPanelIconLevel: { name: "InfoPanelIconLevel", context: [0, 1, 2, 3, 4, 5] },
  InfoPanelIconValue: { name: "InfoPanelIconValue", context: [0, 1, 2, 3, 4, 5] },
  InsideConfirmQuitPanel: { name: "InsideConfirmQuitPanel", context: [0] },
  InsideEndGamePanel: { name: "InsideEndGamePanel", context: [0] },
  InsideHelpPanel: { name: "InsideHelpPanel", context: [0] },
  InsideMainPanel: { name: "InsideMainPanel", context: [0] },
  InsideTipsPanel: { name: "InsideTipsPanel", context: [0] },
  InventoryButton0: { name: "InventoryButton_0", context: [0] },
  InventoryButton1: { name: "InventoryButton_1", context: [0] },
  InventoryButton2: { name: "InventoryButton_2", context: [0] },
  InventoryButton3: { name: "InventoryButton_3", context: [0] },
  InventoryButton4: { name: "InventoryButton_4", context: [0] },
  InventoryButton5: { name: "InventoryButton_5", context: [0] },
  InventoryText: { name: "InventoryText", context: [0] },
  simpleInventoryBar: { name: "SimpleInventoryBar", context: [0] },
  KeyScrollFastLabel: { name: "KeyScrollFastLabel", context: [0] },
  KeyScrollLabel: { name: "KeyScrollLabel", context: [0] },
  KeyScrollSlider: { name: "KeyScrollSlider", context: [0] },
  KeyScrollSlowLabel: { name: "KeyScrollSlowLabel", context: [0] },
  LatencyInfo1: { name: "LatencyInfo", context: [1] },
  LatencyInfo2: { name: "LatencyInfo", context: [2] },
  Leaderboard: { name: "Leaderboard", context: [0] },
  LeaderboardBackdrop: { name: "LeaderboardBackdrop", context: [0] },
  LeaderboardListContainer: { name: "LeaderboardListContainer", context: [0] },
  LeaderboardTitle: { name: "LeaderboardTitle", context: [0] },
  LightsLabel: { name: "LightsLabel", context: [0] },
  LoadGameButton: { name: "LoadGameButton", context: [0] },
  LoadGameButtonText: { name: "LoadGameButtonText", context: [0] },
  LoadGameCancelButton: { name: "LoadGameCancelButton", context: [0] },
  LoadGameCancelButtonText: { name: "LoadGameCancelButtonText", context: [0] },
  LoadGameLoadButton: { name: "LoadGameLoadButton", context: [0] },
  LoadGameLoadButtonText: { name: "LoadGameLoadButtonText", context: [0] },
  LoadGameTitleText: { name: "LoadGameTitleText", context: [0] },
  LoadOnly: { name: "LoadOnly", context: [0] },
  LogArea: { name: "LogArea", context: [0] },
  LogAreaBackdrop: { name: "LogAreaBackdrop", context: [0] },
  LogAreaScrollBar: { name: "LogAreaScrollBar", context: [0] },
  LogBackdrop: { name: "LogBackdrop", context: [0] },
  LogDialog: { name: "LogDialog", context: [0] },
  LogOkButton: { name: "LogOkButton", context: [0] },
  LogOkButtonText: { name: "LogOkButtonText", context: [0] },
  LogTitle: { name: "LogTitle", context: [0] },
  LowLatencyLabel: { name: "LowLatencyLabel", context: [0] },
  LowLatencyRadio: { name: "LowLatencyRadio", context: [0] },
  LumberBackdrop: { name: "LumberBackdrop", context: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23] },
  LumberHeader: { name: "LumberHeader", context: [0] },
  LumberText: { name: "LumberText", context: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23] },
  MainPanel: { name: "MainPanel", context: [0] },
  MapListBoxBackdrop: { name: "MapListBoxBackdrop", context: [0] },
  MapListScrollBar: { name: "MapListScrollBar", context: [0] },
  MiniMapAllyButton: { name: "MiniMapAllyButton", context: [0] },
  MinimapButtonBar: { name: "MinimapButtonBar", context: [0] },
  MiniMapCreepButton: { name: "MiniMapCreepButton", context: [0] },
  MiniMapFrame: { name: "MiniMapFrame", context: [0] },
  MinimapSignalButton: { name: "MinimapSignalButton", context: [0] },
  MiniMapTerrainButton: { name: "MiniMapTerrainButton", context: [0] },
  ModelDetailLabel: { name: "ModelDetailLabel", context: [0] },
  ModelDetailValue: { name: "ModelDetailValue", context: [0] },
  MouseScrollDisable: { name: "MouseScrollDisable", context: [0] },
  MouseScrollDisableLabel: { name: "MouseScrollDisableLabel", context: [0] },
  MouseScrollFastLabel: { name: "MouseScrollFastLabel", context: [0] },
  MouseScrollLabel: { name: "MouseScrollLabel", context: [0] },
  MouseScrollSlider: { name: "MouseScrollSlider", context: [0] },
  MouseScrollSlowLabel: { name: "MouseScrollSlowLabel", context: [0] },
  MovementCheckBox: { name: "MovementCheckBox", context: [0] },
  MovementLabel: { name: "MovementLabel", context: [0] },
  Multiboard: { name: "Multiboard", context: [0] },
  MultiboardBackdrop: { name: "MultiboardBackdrop", context: [0] },
  MultiboardListContainer: { name: "MultiboardListContainer", context: [0] },
  MultiboardMinimizeButton: { name: "MultiboardMinimizeButton", context: [0] },
  MultiboardTitle: { name: "MultiboardTitle", context: [0] },
  MultiboardTitleBackdrop: { name: "MultiboardTitleBackdrop", context: [0] },
  MusicCheckBox: { name: "MusicCheckBox", context: [0] },
  MusicVolumeHighLabel: { name: "MusicVolumeHighLabel", context: [0] },
  MusicVolumeLabel: { name: "MusicVolumeLabel", context: [0] },
  MusicVolumeLowLabel: { name: "MusicVolumeLowLabel", context: [0] },
  MusicVolumeSlider: { name: "MusicVolumeSlider", context: [0] },
  NetworkButton: { name: "NetworkButton", context: [0] },
  NetworkButtonText: { name: "NetworkButtonText", context: [0] },
  NetworkLabel: { name: "NetworkLabel", context: [0] },
  NetworkPanel: { name: "NetworkPanel", context: [0] },
  NetworkTitleText: { name: "NetworkTitleText", context: [0] },
  ObserverCameraCheckBox: { name: "ObserverCameraCheckBox", context: [0] },
  ObserverCameraString: { name: "ObserverCameraString", context: [0] },
  ObserverFogCheckBox: { name: "ObserverFogCheckBox", context: [0] },
  ObserverFogString: { name: "ObserverFogString", context: [0] },
  ObserverVisionMenu: { name: "ObserverVisionMenu", context: [0] },
  ObserverVisionMenuArrow: { name: "ObserverVisionMenuArrow", context: [0] },
  ObserverVisionMenuBackdrop: { name: "ObserverVisionMenuBackdrop", context: [0] },
  ObserverVisionMenuDisabledBackdrop: { name: "ObserverVisionMenuDisabledBackdrop", context: [0] },
  ObserverVisionMenuTitle: { name: "ObserverVisionMenuTitle", context: [0] },
  ObserverVisionPopupMenu: { name: "ObserverVisionPopupMenu", context: [0] },
  ObserverVisionPopupMenuMenuBackdropTemplate: { name: "ObserverVisionPopupMenuMenuBackdropTemplate", context: [0] },
  OcclusionLabel: { name: "OcclusionLabel", context: [0] },
  OKButtonText: { name: "OKButtonText", context: [0] },
  OptionsButton: { name: "OptionsButton", context: [0] },
  OptionsButtonText: { name: "OptionsButtonText", context: [0] },
  OptionsCancelButton: { name: "OptionsCancelButton", context: [0] },
  OptionsOKButton: { name: "OptionsOKButton", context: [0] },
  OptionsPanel: { name: "OptionsPanel", context: [0] },
  OptionsPreviousButton: { name: "OptionsPreviousButton", context: [0] },
  OptionsPreviousButtonText: { name: "OptionsPreviousButtonText", context: [0] },
  OptionsTitleText: { name: "OptionsTitleText", context: [0] },
  OverwriteCancelButton: { name: "OverwriteCancelButton", context: [0] },
  OverwriteCancelButtonText: { name: "OverwriteCancelButtonText", context: [0] },
  OverwriteMessageText: { name: "OverwriteMessageText", context: [0] },
  OverwriteOnly: { name: "OverwriteOnly", context: [0] },
  OverwriteOverwriteButton: { name: "OverwriteOverwriteButton", context: [0] },
  OverwriteOverwriteButtonText: { name: "OverwriteOverwriteButtonText", context: [0] },
  OverwriteTitleText: { name: "OverwriteTitleText", context: [0] },
  ParticlesLabel: { name: "ParticlesLabel", context: [0] },
  PauseButton: { name: "PauseButton", context: [0] },
  PauseButtonText: { name: "PauseButtonText", context: [0] },
  PlayerNameLabel: { name: "PlayerNameLabel", context: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23] },
  PlayersHeader: { name: "PlayersHeader", context: [0] },
  PositionalCheckBox: { name: "PositionalCheckBox", context: [0] },
  PositionalLabel: { name: "PositionalLabel", context: [0] },
  PreviousButton: { name: "PreviousButton", context: [0] },
  PreviousButtonText: { name: "PreviousButtonText", context: [0] },
  ProviderLabel: { name: "ProviderLabel", context: [0] },
  ProviderValue: { name: "ProviderValue", context: [0] },
  QuestAcceptButton: { name: "QuestAcceptButton", context: [0] },
  QuestAcceptButtonText: { name: "QuestAcceptButtonText", context: [0] },
  QuestBackdrop: { name: "QuestBackdrop", context: [0] },
  QuestDetailsTitle: { name: "QuestDetailsTitle", context: [0] },
  QuestDialog: { name: "QuestDialog", context: [0] },
  QuestDisplay: { name: "QuestDisplay", context: [0] },
  QuestDisplayBackdrop: { name: "QuestDisplayBackdrop", context: [0] },
  QuestDisplayScrollBar: { name: "QuestDisplayScrollBar", context: [0] },
  QuestItemListContainer: { name: "QuestItemListContainer", context: [0] },
  QuestItemListItem: { name: "QuestItemListItem", context: [6, 7, 8, 9] },
  QuestItemListItemTitle: { name: "QuestItemListItemTitle", context: [6, 7, 8, 9, 0] },
  QuestListItem: { name: "QuestListItem", context: [0, 1, 2, 3, 4, 5] },
  QuestListItemBorder: { name: "QuestListItemBorder", context: [0, 1, 2, 3, 4, 5] },
  QuestListItemButton: { name: "QuestListItemButton", context: [0, 1, 2, 3, 4, 5] },
  QuestListItemComplete: { name: "QuestListItemComplete", context: [0, 1, 2, 3, 4, 5] },
  QuestListItemCompletedHighlight: { name: "QuestListItemCompletedHighlight", context: [0, 1, 2, 3, 4, 5] },
  QuestListItemFailedHighlight: { name: "QuestListItemFailedHighlight", context: [0, 1, 2, 3, 4, 5] },
  QuestListItemIconContainer: { name: "QuestListItemIconContainer", context: [0, 1, 2, 3, 4, 5] },
  QuestListItemSelectedHighlight: { name: "QuestListItemSelectedHighlight", context: [0, 1, 2, 3, 4, 5] },
  QuestListItemTitle: { name: "QuestListItemTitle", context: [0, 1, 2, 3, 4, 5] },
  QuestMainContainer: { name: "QuestMainContainer", context: [0] },
  QuestMainListScrollBar: { name: "QuestMainListScrollBar", context: [0] },
  QuestMainTitle: { name: "QuestMainTitle", context: [0] },
  QuestOptionalContainer: { name: "QuestOptionalContainer", context: [0] },
  QuestOptionalListScrollBar: { name: "QuestOptionalListScrollBar", context: [0] },
  QuestOptionalTitle: { name: "QuestOptionalTitle", context: [0] },
  QuestSubtitleValue: { name: "QuestSubtitleValue", context: [0] },
  QuestTitleValue: { name: "QuestTitleValue", context: [0] },
  QuitButton: { name: "QuitButton", context: [0] },
  QuitButtonText: { name: "QuitButtonText", context: [0] },
  ResolutionLabel: { name: "ResolutionLabel", context: [0] },
  ResourceBarFrame: { name: "ResourceBarFrame", context: [0] },
  ResourceBarGoldText: { name: "ResourceBarGoldText", context: [0] },
  ResourceBarLumberText: { name: "ResourceBarLumberText", context: [0] },
  ResourceBarSupplyText: { name: "ResourceBarSupplyText", context: [0] },
  ResourceBarUpkeepText: { name: "ResourceBarUpkeepText", context: [0] },
  ResourceTradingTitle: { name: "ResourceTradingTitle", context: [0] },
  RestartButton: { name: "RestartButton", context: [0] },
  RestartButtonText: { name: "RestartButtonText", context: [0] },
  ReturnButton: { name: "ReturnButton", context: [0] },
  ReturnButtonText: { name: "ReturnButtonText", context: [0] },
  SaveAndLoad: { name: "SaveAndLoad", context: [0] },
  SaveGameButton: { name: "SaveGameButton", context: [0] },
  SaveGameButtonText: { name: "SaveGameButtonText", context: [0] },
  SaveGameCancelButton: { name: "SaveGameCancelButton", context: [0] },
  SaveGameCancelButtonText: { name: "SaveGameCancelButtonText", context: [0] },
  SaveGameDeleteButton: { name: "SaveGameDeleteButton", context: [0] },
  SaveGameDeleteButtonText: { name: "SaveGameDeleteButtonText", context: [0] },
  SaveGameFileEditBox: { name: "SaveGameFileEditBox", context: [0] },
  SaveGameFileEditBoxText: { name: "SaveGameFileEditBoxText", context: [0] },
  SaveGameSaveButton: { name: "SaveGameSaveButton", context: [0] },
  SaveGameSaveButtonText: { name: "SaveGameSaveButtonText", context: [0] },
  SaveGameTitleText: { name: "SaveGameTitleText", context: [0] },
  SaveOnly: { name: "SaveOnly", context: [0] },
  ShadowsLabel: { name: "ShadowsLabel", context: [0] },
  SimpleBuildingActionLabel: { name: "SimpleBuildingActionLabel", context: [0, 1] },
  SimpleBuildingDescriptionValue: { name: "SimpleBuildingDescriptionValue", context: [1] },
  SimpleBuildingNameValue: { name: "SimpleBuildingNameValue", context: [1] },
  SimpleBuildQueueBackdrop: { name: "SimpleBuildQueueBackdrop", context: [1] },
  SimpleBuildTimeIndicator: { name: "SimpleBuildTimeIndicator", context: [0, 1] },
  SimpleClassValue: { name: "SimpleClassValue", context: [0] },
  SimpleDestructableNameValue: { name: "SimpleDestructableNameValue", context: [4] },
  SimpleHeroLevelBar: { name: "SimpleHeroLevelBar", context: [0] },
  SimpleHoldDescriptionValue: { name: "SimpleHoldDescriptionValue", context: [2] },
  SimpleHoldNameValue: { name: "SimpleHoldNameValue", context: [2] },
  SimpleInfoPanelBuildingDetail: { name: "SimpleInfoPanelBuildingDetail", context: [1] },
  SimpleInfoPanelCargoDetail: { name: "SimpleInfoPanelCargoDetail", context: [2] },
  SimpleInfoPanelDestructableDetail: { name: "SimpleInfoPanelDestructableDetail", context: [4] },
  SimpleInfoPanelIconAlly: { name: "SimpleInfoPanelIconAlly", context: [7] },
  SimpleInfoPanelIconArmor: { name: "SimpleInfoPanelIconArmor", context: [2] },
  SimpleInfoPanelIconDamage: { name: "SimpleInfoPanelIconDamage", context: [0, 1] },
  SimpleInfoPanelIconFood: { name: "SimpleInfoPanelIconFood", context: [4] },
  SimpleInfoPanelIconGold: { name: "SimpleInfoPanelIconGold", context: [5] },
  SimpleInfoPanelIconHero: { name: "SimpleInfoPanelIconHero", context: [6] },
  SimpleInfoPanelIconHeroText: { name: "SimpleInfoPanelIconHeroText", context: [6] },
  SimpleInfoPanelIconRank: { name: "SimpleInfoPanelIconRank", context: [3] },
  SimpleInfoPanelItemDetail: { name: "SimpleInfoPanelItemDetail", context: [3] },
  SimpleInfoPanelUnitDetail: { name: "SimpleInfoPanelUnitDetail", context: [0] },
  SimpleItemDescriptionValue: { name: "SimpleItemDescriptionValue", context: [3] },
  SimpleItemNameValue: { name: "SimpleItemNameValue", context: [3] },
  SimpleNameValue: { name: "SimpleNameValue", context: [0] },
  SimpleObserverPanel: { name: "SimpleObserverPanel", context: [0] },
  SimpleProgressIndicator: { name: "SimpleProgressIndicator", context: [0] },
  SimpleUnitStatsPanel: { name: "SimpleUnitStatsPanel", context: [0] },
  SoundButton: { name: "SoundButton", context: [0] },
  SoundButtonText: { name: "SoundButtonText", context: [0] },
  SoundCheckBox: { name: "SoundCheckBox", context: [0] },
  SoundPanel: { name: "SoundPanel", context: [0] },
  SoundTitleText: { name: "SoundTitleText", context: [0] },
  SoundVolumeHighLabel: { name: "SoundVolumeHighLabel", context: [0] },
  SoundVolumeLabel: { name: "SoundVolumeLabel", context: [0] },
  SoundVolumeLowLabel: { name: "SoundVolumeLowLabel", context: [0] },
  SoundVolumeSlider: { name: "SoundVolumeSlider", context: [0] },
  SubgroupCheckBox: { name: "SubgroupCheckBox", context: [0] },
  SubgroupLabel: { name: "SubgroupLabel", context: [0] },
  SubtitlesCheckBox: { name: "SubtitlesCheckBox", context: [0] },
  SubtitlesLabel: { name: "SubtitlesLabel", context: [0] },
  TextureQualityLabel: { name: "TextureQualityLabel", context: [0] },
  TextureQualityValue: { name: "TextureQualityValue", context: [0] },
  TimerDialog: { name: "TimerDialog", context: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23] },
  TimerDialogBackdrop: { name: "TimerDialogBackdrop", context: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23] },
  TimerDialogValue: { name: "TimerDialogValue", context: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23] },
  TimerDialogTitle: { name: "TimerDialogTitle", context: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23] },
  TipsBackButton: { name: "TipsBackButton", context: [0] },
  TipsBackButtonText: { name: "TipsBackButtonText", context: [0] },
  TipsButton: { name: "TipsButton", context: [0] },
  TipsButtonText: { name: "TipsButtonText", context: [0] },
  TipsNextButton: { name: "TipsNextButton", context: [0] },
  TipsNextButtonText: { name: "TipsNextButtonText", context: [0] },
  TipsOKButton: { name: "TipsOKButton", context: [0] },
  TipsOKButtonText: { name: "TipsOKButtonText", context: [0] },
  TipsPanel: { name: "TipsPanel", context: [0] },
  TipsTextArea: { name: "TipsTextArea", context: [0] },
  TipsTitleText: { name: "TipsTitleText", context: [0] },
  TooltipsCheckBox: { name: "TooltipsCheckBox", context: [0] },
  TooltipsLabel: { name: "TooltipsLabel", context: [0] },
  UnitCheckBox: { name: "UnitCheckBox", context: [0] },
  UnitLabel: { name: "UnitLabel", context: [0] },
  UnitsCheckBox: { name: "UnitsCheckBox", context: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23] },
  UnitsHeader: { name: "UnitsHeader", context: [0] },
  UpperButtonBarAlliesButton: { name: "UpperButtonBarAlliesButton", context: [0] },
  UpperButtonBarChatButton: { name: "UpperButtonBarChatButton", context: [0] },
  UpperButtonBarFrame: { name: "UpperButtonBarFrame", context: [0] },
  UpperButtonBarMenuButton: { name: "UpperButtonBarMenuButton", context: [0] },
  UpperButtonBarQuestsButton: { name: "UpperButtonBarQuestsButton", context: [0] },
  VideoButton: { name: "VideoButton", context: [0] },
  VideoButtonText: { name: "VideoButtonText", context: [0] },
  VideoPanel: { name: "VideoPanel", context: [0] },
  VideoTitleText: { name: "VideoTitleText", context: [0] },
  VisionCheckBox: { name: "VisionCheckBox", context: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23] },
  VisionHeader: { name: "VisionHeader", context: [0] },
  VSyncCheckBox: { name: "VSyncCheckBox", context: [0] },
  VSyncLabel: { name: "VSyncLabel", context: [0] },
  WindowModeLabel: { name: "WindowModeLabel", context: [0] },
  WouldTheRealOptionsTitleTextPleaseStandUp: { name: "WouldTheRealOptionsTitleTextPleaseStandUp", context: [0] },
}

/** These default frames can be obtained with getFrameByName(..) [BlzGetFrameByName]
		(the createContext (subframe-id) parameter is by default 0, some frames does contain subframes) */
export enum FrameName {
  commandButton0 = "CommandButton_0",
  commandButton1 = "CommandButton_1",
  commandButton2 = "CommandButton_2",
  commandButton3 = "CommandButton_3",
  commandButton4 = "CommandButton_4",
  commandButton5 = "CommandButton_5",
  commandButton6 = "CommandButton_6",
  commandButton7 = "CommandButton_7",
  commandButton8 = "CommandButton_8",
  commandButton9 = "CommandButton_9",
  commandButton10 = "CommandButton_10",
  commandButton11 = "CommandButton_11",
  inventoryButton0 = "InventoryButton_0",
  inventoryButton1 = "InventoryButton_1",
  inventoryButton2 = "InventoryButton_2",
  inventoryButton3 = "InventoryButton_3",
  inventoryButton4 = "InventoryButton_4",
  inventoryButton5 = "InventoryButton_5",
  inventoryText = "InventoryText",
  simpleInventoryBar = "SimpleInventoryBar",

  inventoryCoverTexture = "InventoryCoverTexture",
  allianceAcceptButton = "AllianceAcceptButton",
  allianceAcceptButtonText = "AllianceAcceptButtonText",
  allianceBackdrop = "AllianceBackdrop",
  allianceCancelButton = "AllianceCancelButton",
  allianceCancelButtonText = "AllianceCancelButtonText",
  allianceDialog = "AllianceDialog",
  allianceDialogScrollBar = "AllianceDialogScrollBar",
  /** The framehandle name allianceSlot has the subframes [0 to 23] */
  allianceSlot = "AllianceSlot",
  allianceTitle = "AllianceTitle",
  alliedVictoryCheckBox = "AlliedVictoryCheckBox",
  alliedVictoryLabel = "AlliedVictoryLabel",
  /** The framehandle name allyCheckBox has the subframes [0 to 23] */
  allyCheckBox = "AllyCheckBox",
  allyHeader = "AllyHeader",
  ambientCheckBox = "AmbientCheckBox",
  ambientLabel = "AmbientLabel",
  animQualityLabel = "AnimQualityLabel",
  animQualityValue = "AnimQualityValue",
  bottomButtonPanel = "BottomButtonPanel",
  buttonBackdropTemplate = "ButtonBackdropTemplate",
  buttonDisabledBackdropTemplate = "ButtonDisabledBackdropTemplate",
  buttonDisabledPushedBackdropTemplate = "ButtonDisabledPushedBackdropTemplate",
  buttonPushedBackdropTemplate = "ButtonPushedBackdropTemplate",
  cancelButtonText = "CancelButtonText",
  cinematicBottomBorder = "CinematicBottomBorder",
  cinematicDialogueText = "CinematicDialogueText",
  cinematicPanel = "CinematicPanel",
  cinematicPortrait = "CinematicPortrait",
  cinematicPortraitBackground = "CinematicPortraitBackground",
  cinematicPortraitCover = "CinematicPortraitCover",
  cinematicScenePanel = "CinematicScenePanel",
  cinematicSpeakerText = "CinematicSpeakerText",
  cinematicTopBorder = "CinematicTopBorder",
  /** The framehandle name colorBackdrop has the subframes [0 to 23] */
  colorBackdrop = "ColorBackdrop",
  /** The framehandle name colorBorder has the subframes [0 to 23] */
  colorBorder = "ColorBorder",
  confirmQuitCancelButton = "ConfirmQuitCancelButton",
  confirmQuitCancelButtonText = "ConfirmQuitCancelButtonText",
  confirmQuitMessageText = "ConfirmQuitMessageText",
  confirmQuitPanel = "ConfirmQuitPanel",
  confirmQuitQuitButton = "ConfirmQuitQuitButton",
  confirmQuitQuitButtonText = "ConfirmQuitQuitButtonText",
  confirmQuitTitleText = "ConfirmQuitTitleText",
  consoleUI = "ConsoleUI",
  consoleUIBackdrop = "ConsoleUIBackdrop",
  customKeysLabel = "CustomKeysLabel",
  customKeysValue = "CustomKeysValue",
  decoratedMapListBox = "DecoratedMapListBox",
  deleteCancelButton = "DeleteCancelButton",
  deleteCancelButtonText = "DeleteCancelButtonText",
  deleteDeleteButton = "DeleteDeleteButton",
  deleteDeleteButtonText = "DeleteDeleteButtonText",
  deleteMessageText = "DeleteMessageText",
  deleteOnly = "DeleteOnly",
  deleteTitleText = "DeleteTitleText",
  difficultyLabel = "DifficultyLabel",
  difficultyValue = "DifficultyValue",
  endGameButton = "EndGameButton",
  endGameButtonText = "EndGameButtonText",
  endGamePanel = "EndGamePanel",
  endGameTitleText = "EndGameTitleText",
  enviroCheckBox = "EnviroCheckBox",
  enviroLabel = "EnviroLabel",
  escMenuBackdrop = "EscMenuBackdrop",
  escMenuDeleteContainer = "EscMenuDeleteContainer",
  escMenuMainPanel = "EscMenuMainPanel",
  escMenuOptionsPanel = "EscMenuOptionsPanel",
  escMenuOverwriteContainer = "EscMenuOverwriteContainer",
  escMenuSaveGamePanel = "EscMenuSaveGamePanel",
  escMenuSaveLoadContainer = "EscMenuSaveLoadContainer",
  escOptionsLightsMenu = "EscOptionsLightsMenu",
  escOptionsLightsPopupMenuArrow = "EscOptionsLightsPopupMenuArrow",
  escOptionsLightsPopupMenuBackdrop = "EscOptionsLightsPopupMenuBackdrop",
  escOptionsLightsPopupMenuDisabledBackdrop = "EscOptionsLightsPopupMenuDisabledBackdrop",
  escOptionsLightsPopupMenuMenu = "EscOptionsLightsPopupMenuMenu",
  escOptionsLightsPopupMenuTitle = "EscOptionsLightsPopupMenuTitle",
  escOptionsOcclusionMenu = "EscOptionsOcclusionMenu",
  escOptionsOcclusionPopupMenuArrow = "EscOptionsOcclusionPopupMenuArrow",
  escOptionsOcclusionPopupMenuBackdrop = "EscOptionsOcclusionPopupMenuBackdrop",
  escOptionsOcclusionPopupMenuDisabledBackdrop = "EscOptionsOcclusionPopupMenuDisabledBackdrop",
  escOptionsOcclusionPopupMenuMenu = "EscOptionsOcclusionPopupMenuMenu",
  escOptionsOcclusionPopupMenuTitle = "EscOptionsOcclusionPopupMenuTitle",
  escOptionsParticlesMenu = "EscOptionsParticlesMenu",
  escOptionsParticlesPopupMenuArrow = "EscOptionsParticlesPopupMenuArrow",
  escOptionsParticlesPopupMenuBackdrop = "EscOptionsParticlesPopupMenuBackdrop",
  escOptionsParticlesPopupMenuDisabledBackdrop = "EscOptionsParticlesPopupMenuDisabledBackdrop",
  escOptionsParticlesPopupMenuMenu = "EscOptionsParticlesPopupMenuMenu",
  escOptionsParticlesPopupMenuTitle = "EscOptionsParticlesPopupMenuTitle",
  escOptionsResolutionMenu = "EscOptionsResolutionMenu",
  escOptionsResolutionPopupMenuArrow = "EscOptionsResolutionPopupMenuArrow",
  escOptionsResolutionPopupMenuBackdrop = "EscOptionsResolutionPopupMenuBackdrop",
  escOptionsResolutionPopupMenuDisabledBackdrop = "EscOptionsResolutionPopupMenuDisabledBackdrop",
  escOptionsResolutionPopupMenuMenu = "EscOptionsResolutionPopupMenuMenu",
  escOptionsResolutionPopupMenuTitle = "EscOptionsResolutionPopupMenuTitle",
  escOptionsShadowsMenu = "EscOptionsShadowsMenu",
  escOptionsShadowsPopupMenuArrow = "EscOptionsShadowsPopupMenuArrow",
  escOptionsShadowsPopupMenuBackdrop = "EscOptionsShadowsPopupMenuBackdrop",
  escOptionsShadowsPopupMenuDisabledBackdrop = "EscOptionsShadowsPopupMenuDisabledBackdrop",
  escOptionsShadowsPopupMenuMenu = "EscOptionsShadowsPopupMenuMenu",
  escOptionsShadowsPopupMenuTitle = "EscOptionsShadowsPopupMenuTitle",
  escOptionsWindowModeMenu = "EscOptionsWindowModeMenu",
  escOptionsWindowModePopupMenuArrow = "EscOptionsWindowModePopupMenuArrow",
  escOptionsWindowModePopupMenuBackdrop = "EscOptionsWindowModePopupMenuBackdrop",
  escOptionsWindowModePopupMenuDisabledBackdrop = "EscOptionsWindowModePopupMenuDisabledBackdrop",
  escOptionsWindowModePopupMenuMenu = "EscOptionsWindowModePopupMenuMenu",
  escOptionsWindowModePopupMenuTitle = "EscOptionsWindowModePopupMenuTitle",
  exitButton = "ExitButton",
  exitButtonText = "ExitButtonText",
  extraHighLatencyLabel = "ExtraHighLatencyLabel",
  extraHighLatencyRadio = "ExtraHighLatencyRadio",
  fileListFrame = "FileListFrame",
  formationToggleCheckBox = "FormationToggleCheckBox",
  formationToggleLabel = "FormationToggleLabel",
  gameplayButton = "GameplayButton",
  gameplayButtonText = "GameplayButtonText",
  gameplayPanel = "GameplayPanel",
  gameplayTitleText = "GameplayTitleText",
  gameSpeedLabel = "GameSpeedLabel",
  gameSpeedSlider = "GameSpeedSlider",
  gameSpeedValue = "GameSpeedValue",
  gammaBrightLabel = "GammaBrightLabel",
  gammaDarkLabel = "GammaDarkLabel",
  gammaLabel = "GammaLabel",
  gammaSlider = "GammaSlider",
  /** The framehandle name goldBackdrop has the subframes [0 to 23] */
  goldBackdrop = "GoldBackdrop",
  goldHeader = "GoldHeader",
  /** The framehandle name goldText has the subframes [0 to 23] */
  goldText = "GoldText",
  healthBarsCheckBox = "HealthBarsCheckBox",
  healthBarsLabel = "HealthBarsLabel",
  helpButton = "HelpButton",
  helpButtonText = "HelpButtonText",
  helpOKButton = "HelpOKButton",
  helpOKButtonText = "HelpOKButtonText",
  helpPanel = "HelpPanel",
  helpTextArea = "HelpTextArea",
  helpTitleText = "HelpTitleText",
  highLatencyLabel = "HighLatencyLabel",
  highLatencyRadio = "HighLatencyRadio",
  /** The framehandle name infoPanelIconAllyFoodIcon has the subframe [7] */
  infoPanelIconAllyFoodIcon = "InfoPanelIconAllyFoodIcon",
  /** The framehandle name infoPanelIconAllyFoodValue has the subframe [7] */
  infoPanelIconAllyFoodValue = "InfoPanelIconAllyFoodValue",
  /** The framehandle name infoPanelIconAllyGoldIcon has the subframe [7] */
  infoPanelIconAllyGoldIcon = "InfoPanelIconAllyGoldIcon",
  /** The framehandle name infoPanelIconAllyGoldValue has the subframe [7] */
  infoPanelIconAllyGoldValue = "InfoPanelIconAllyGoldValue",
  /** The framehandle name infoPanelIconAllyTitle has the subframe [7] */
  infoPanelIconAllyTitle = "InfoPanelIconAllyTitle",
  /** The framehandle name infoPanelIconAllyUpkeep has the subframe [7] */
  infoPanelIconAllyUpkeep = "InfoPanelIconAllyUpkeep",
  /** The framehandle name infoPanelIconAllyWoodIcon has the subframe [7] */
  infoPanelIconAllyWoodIcon = "InfoPanelIconAllyWoodIcon",
  /** The framehandle name infoPanelIconAllyWoodValue has the subframe [7] */
  infoPanelIconAllyWoodValue = "InfoPanelIconAllyWoodValue",
  /** The framehandle name infoPanelIconBackdrop has the subframes [0 to 5] */
  infoPanelIconBackdrop = "InfoPanelIconBackdrop",
  /** The framehandle name infoPanelIconHeroAgilityLabel has the subframe [6] */
  infoPanelIconHeroAgilityLabel = "InfoPanelIconHeroAgilityLabel",
  /** The framehandle name infoPanelIconHeroAgilityValue has the subframe [6] */
  infoPanelIconHeroAgilityValue = "InfoPanelIconHeroAgilityValue",
  /** The framehandle name infoPanelIconHeroIcon has the subframe [6] */
  infoPanelIconHeroIcon = "InfoPanelIconHeroIcon",
  /** The framehandle name infoPanelIconHeroIntellectLabel has the subframe [6] */
  infoPanelIconHeroIntellectLabel = "InfoPanelIconHeroIntellectLabel",
  /** The framehandle name infoPanelIconHeroIntellectValue has the subframe [6] */
  infoPanelIconHeroIntellectValue = "InfoPanelIconHeroIntellectValue",
  /** The framehandle name infoPanelIconHeroStrengthLabel has the subframe [6] */
  infoPanelIconHeroStrengthLabel = "InfoPanelIconHeroStrengthLabel",
  /** The framehandle name infoPanelIconHeroStrengthValue has the subframe [6] */
  infoPanelIconHeroStrengthValue = "InfoPanelIconHeroStrengthValue",
  /** The framehandle name infoPanelIconLabel has the subframes [0 to 5] */
  infoPanelIconLabel = "InfoPanelIconLabel",
  /** The framehandle name infoPanelIconLevel has the subframes [0 to 5] */
  infoPanelIconLevel = "InfoPanelIconLevel",
  /** The framehandle name infoPanelIconValue has the subframes [0 to 5] */
  infoPanelIconValue = "InfoPanelIconValue",
  insideConfirmQuitPanel = "InsideConfirmQuitPanel",
  insideEndGamePanel = "InsideEndGamePanel",
  insideHelpPanel = "InsideHelpPanel",
  insideMainPanel = "InsideMainPanel",
  insideTipsPanel = "InsideTipsPanel",
  keyScrollFastLabel = "KeyScrollFastLabel",
  keyScrollLabel = "KeyScrollLabel",
  keyScrollSlider = "KeyScrollSlider",
  keyScrollSlowLabel = "KeyScrollSlowLabel",
  latencyInfo1 = "LatencyInfo1",
  latencyInfo2 = "LatencyInfo2",
  leaderboardFrame = "Leaderboard",
  leaderboardBackdrop = "LeaderboardBackdrop",
  leaderboardListContainer = "LeaderboardListContainer",
  leaderboardTitle = "LeaderboardTitle",
  lightsLabel = "LightsLabel",
  loadGameButton = "LoadGameButton",
  loadGameButtonText = "LoadGameButtonText",
  loadGameCancelButton = "LoadGameCancelButton",
  loadGameCancelButtonText = "LoadGameCancelButtonText",
  loadGameLoadButton = "LoadGameLoadButton",
  loadGameLoadButtonText = "LoadGameLoadButtonText",
  loadGameTitleText = "LoadGameTitleText",
  loadOnly = "LoadOnly",
  logArea = "LogArea",
  logAreaBackdrop = "LogAreaBackdrop",
  logAreaScrollBar = "LogAreaScrollBar",
  logBackdrop = "LogBackdrop",
  logDialog = "LogDialog",
  logOkButton = "LogOkButton",
  logOkButtonText = "LogOkButtonText",
  logTitle = "LogTitle",
  lowLatencyLabel = "LowLatencyLabel",
  lowLatencyRadio = "LowLatencyRadio",
  /** The framehandle name lumberBackdrop has the subframes [0 to 23] */
  lumberBackdrop = "LumberBackdrop",
  lumberHeader = "LumberHeader",
  /** The framehandle name lumberText has the subframes [0 to 23] */
  lumberText = "LumberText",
  mainPanel = "MainPanel",
  mapListBoxBackdrop = "MapListBoxBackdrop",
  mapListScrollBar = "MapListScrollBar",
  modelDetailLabel = "ModelDetailLabel",
  modelDetailValue = "ModelDetailValue",
  mouseScrollDisable = "MouseScrollDisable",
  mouseScrollDisableLabel = "MouseScrollDisableLabel",
  mouseScrollFastLabel = "MouseScrollFastLabel",
  mouseScrollLabel = "MouseScrollLabel",
  mouseScrollSlider = "MouseScrollSlider",
  mouseScrollSlowLabel = "MouseScrollSlowLabel",
  movementCheckBox = "MovementCheckBox",
  movementLabel = "MovementLabel",
  multiboardFrame = "Multiboard",
  multiboardBackdrop = "MultiboardBackdrop",
  multiboardListContainer = "MultiboardListContainer",
  multiboardMinimizeButton = "MultiboardMinimizeButton",
  multiboardTitle = "MultiboardTitle",
  multiboardTitleBackdrop = "MultiboardTitleBackdrop",
  musicCheckBox = "MusicCheckBox",
  musicVolumeHighLabel = "MusicVolumeHighLabel",
  musicVolumeLabel = "MusicVolumeLabel",
  musicVolumeLowLabel = "MusicVolumeLowLabel",
  musicVolumeSlider = "MusicVolumeSlider",
  networkButton = "NetworkButton",
  networkButtonText = "NetworkButtonText",
  networkLabel = "NetworkLabel",
  networkPanel = "NetworkPanel",
  networkTitleText = "NetworkTitleText",
  observerCameraCheckBox = "ObserverCameraCheckBox",
  observerCameraString = "ObserverCameraString",
  observerFogCheckBox = "ObserverFogCheckBox",
  observerFogString = "ObserverFogString",
  observerVisionMenu = "ObserverVisionMenu",
  observerVisionMenuArrow = "ObserverVisionMenuArrow",
  observerVisionMenuBackdrop = "ObserverVisionMenuBackdrop",
  observerVisionMenuDisabledBackdrop = "ObserverVisionMenuDisabledBackdrop",
  observerVisionMenuTitle = "ObserverVisionMenuTitle",
  observerVisionPopupMenu = "ObserverVisionPopupMenu",
  observerVisionPopupMenuMenuBackdropTemplate = "ObserverVisionPopupMenuMenuBackdropTemplate",
  occlusionLabel = "OcclusionLabel",
  oKButtonText = "OKButtonText",
  optionsButton = "OptionsButton",
  optionsButtonText = "OptionsButtonText",
  optionsCancelButton = "OptionsCancelButton",
  optionsOKButton = "OptionsOKButton",
  optionsPanel = "OptionsPanel",
  optionsPreviousButton = "OptionsPreviousButton",
  optionsPreviousButtonText = "OptionsPreviousButtonText",
  optionsTitleText = "OptionsTitleText",
  overwriteCancelButton = "OverwriteCancelButton",
  overwriteCancelButtonText = "OverwriteCancelButtonText",
  overwriteMessageText = "OverwriteMessageText",
  overwriteOnly = "OverwriteOnly",
  overwriteOverwriteButton = "OverwriteOverwriteButton",
  overwriteOverwriteButtonText = "OverwriteOverwriteButtonText",
  overwriteTitleText = "OverwriteTitleText",
  particlesLabel = "ParticlesLabel",
  pauseButton = "PauseButton",
  pauseButtonText = "PauseButtonText",
  /** The framehandle name playerNameLabel has the subframes [0 to 23] */
  playerNameLabel = "PlayerNameLabel",
  playersHeader = "PlayersHeader",
  positionalCheckBox = "PositionalCheckBox",
  positionalLabel = "PositionalLabel",
  previousButton = "PreviousButton",
  previousButtonText = "PreviousButtonText",
  providerLabel = "ProviderLabel",
  providerValue = "ProviderValue",
  quitButton = "QuitButton",
  quitButtonText = "QuitButtonText",
  resolutionLabel = "ResolutionLabel",
  resourceBarFrame = "ResourceBarFrame",
  resourceBarGoldText = "ResourceBarGoldText",
  resourceBarLumberText = "ResourceBarLumberText",
  resourceBarSupplyText = "ResourceBarSupplyText",
  resourceBarUpkeepText = "ResourceBarUpkeepText",
  resourceTradingTitle = "ResourceTradingTitle",
  restartButton = "RestartButton",
  restartButtonText = "RestartButtonText",
  returnButton = "ReturnButton",
  returnButtonText = "ReturnButtonText",
  saveAndLoad = "SaveAndLoad",
  saveGameButton = "SaveGameButton",
  saveGameButtonText = "SaveGameButtonText",
  saveGameCancelButton = "SaveGameCancelButton",
  saveGameCancelButtonText = "SaveGameCancelButtonText",
  saveGameDeleteButton = "SaveGameDeleteButton",
  saveGameDeleteButtonText = "SaveGameDeleteButtonText",
  saveGameFileEditBox = "SaveGameFileEditBox",
  saveGameFileEditBoxText = "SaveGameFileEditBoxText",
  saveGameSaveButton = "SaveGameSaveButton",
  saveGameSaveButtonText = "SaveGameSaveButtonText",
  saveGameTitleText = "SaveGameTitleText",
  saveOnly = "SaveOnly",
  shadowsLabel = "ShadowsLabel",
  /** The framehandle name simpleBuildingActionLabel has the subframes [0, 1] */
  simpleBuildingActionLabel = "SimpleBuildingActionLabel",
  /** The framehandle name simpleBuildingDescriptionValue has the subframe [1] */
  simpleBuildingDescriptionValue = "SimpleBuildingDescriptionValue",
  /** The framehandle name simpleBuildingNameValue has the subframe [1] */
  simpleBuildingNameValue = "SimpleBuildingNameValue",
  /** The framehandle name simpleBuildQueueBackdrop has the subframe [1] */
  simpleBuildQueueBackdrop = "SimpleBuildQueueBackdrop",
  /** The framehandle name simpleBuildTimeIndicator has the subframes [0, 1] */
  simpleBuildTimeIndicator = "SimpleBuildTimeIndicator",
  simpleClassValue = "SimpleClassValue",
  simpleDestructableNameValue = "SimpleDestructableNameValue",
  /** The framehandle name simpleHeroLevelBar has the subframe [4] */
  simpleHeroLevelBar = "SimpleHeroLevelBar",
  /** The framehandle name simpleHoldDescriptionValue has the subframe [2] */
  simpleHoldDescriptionValue = "SimpleHoldDescriptionValue",
  /** The framehandle name simpleHoldNameValue has the subframe [2] */
  simpleHoldNameValue = "SimpleHoldNameValue",
  /** The framehandle name simpleInfoPanelBuildingDetail has the subframe [1] */
  simpleInfoPanelBuildingDetail = "SimpleInfoPanelBuildingDetail",
  /** The framehandle name simpleInfoPanelCargoDetail has the subframe [2] */
  simpleInfoPanelCargoDetail = "SimpleInfoPanelCargoDetail",
  /** The framehandle name simpleInfoPanelDestructableDetail has the subframe [4] */
  simpleInfoPanelDestructableDetail = "SimpleInfoPanelDestructableDetail",
  /** The framehandle name simpleInfoPanelIconArmor has the subframe [7] */
  simpleInfoPanelIconAlly = "SimpleInfoPanelIconAlly",
  /** The framehandle name simpleInfoPanelIconArmor has the subframe [2] */
  simpleInfoPanelIconArmor = "SimpleInfoPanelIconArmor",
  /** The framehandle name SimpleInfoPanelIconDamage has the subframe [0, 1] */
  simpleInfoPanelIconDamage = "SimpleInfoPanelIconDamage",
  /** The framehandle name simpleInfoPanelIconFood has the subframe [4] */
  simpleInfoPanelIconFood = "SimpleInfoPanelIconFood",
  /** The framehandle name simpleInfoPanelIconGold has the subframe [5] */
  simpleInfoPanelIconGold = "SimpleInfoPanelIconGold",
  /** The framehandle name simpleInfoPanelIconHero has the subframe [6] */
  simpleInfoPanelIconHero = "SimpleInfoPanelIconHero",
  /** The framehandle name simpleInfoPanelIconHeroText has the subframe [6] */
  simpleInfoPanelIconHeroText = "SimpleInfoPanelIconHeroText",
  /** The framehandle name simpleInfoPanelIconRank has the subframe [3] */
  simpleInfoPanelIconRank = "SimpleInfoPanelIconRank",
  /** The framehandle name simpleInfoPanelItemDetail has the subframe [3] */
  simpleInfoPanelItemDetail = "SimpleInfoPanelItemDetail",
  simpleInfoPanelUnitDetail = "SimpleInfoPanelUnitDetail",
  /** The framehandle name simpleItemDescriptionValue has the subframe [3] */
  simpleItemDescriptionValue = "SimpleItemDescriptionValue",
  /** The framehandle name simpleItemNameValue has the subframe [3] */
  simpleItemNameValue = "SimpleItemNameValue",
  simpleNameValue = "SimpleNameValue",
  simpleObserverPanel = "SimpleObserverPanel",
  simpleProgressIndicator = "SimpleProgressIndicator",
  simpleUnitStatsPanel = "SimpleUnitStatsPanel",
  soundButton = "SoundButton",
  soundButtonText = "SoundButtonText",
  soundCheckBox = "SoundCheckBox",
  soundPanel = "SoundPanel",
  soundTitleText = "SoundTitleText",
  soundVolumeHighLabel = "SoundVolumeHighLabel",
  soundVolumeLabel = "SoundVolumeLabel",
  soundVolumeLowLabel = "SoundVolumeLowLabel",
  soundVolumeSlider = "SoundVolumeSlider",
  subgroupCheckBox = "SubgroupCheckBox",
  subgroupLabel = "SubgroupLabel",
  subtitlesCheckBox = "SubtitlesCheckBox",
  subtitlesLabel = "SubtitlesLabel",
  textureQualityLabel = "TextureQualityLabel",
  textureQualityValue = "TextureQualityValue",
  tipsBackButton = "TipsBackButton",
  tipsBackButtonText = "TipsBackButtonText",
  tipsButton = "TipsButton",
  tipsButtonText = "TipsButtonText",
  tipsNextButton = "TipsNextButton",
  tipsNextButtonText = "TipsNextButtonText",
  tipsOKButton = "TipsOKButton",
  tipsOKButtonText = "TipsOKButtonText",
  tipsPanel = "TipsPanel",
  tipsTextArea = "TipsTextArea",
  tipsTitleText = "TipsTitleText",
  tooltipsCheckBox = "TooltipsCheckBox",
  tooltipsLabel = "TooltipsLabel",
  unitCheckBox = "UnitCheckBox",
  unitLabel = "UnitLabel",
  /** The framehandle name unitsCheckBox has the subframes [o t 23] */
  unitsCheckBox = "UnitsCheckBox",
  unitsHeader = "UnitsHeader",
  upperButtonBarAlliesButton = "UpperButtonBarAlliesButton",
  upperButtonBarChatButton = "UpperButtonBarChatButton",
  upperButtonBarFrame = "UpperButtonBarFrame",
  upperButtonBarMenuButton = "UpperButtonBarMenuButton",
  upperButtonBarQuestsButton = "UpperButtonBarQuestsButton",
  videoButton = "VideoButton",
  videoButtonText = "VideoButtonText",
  videoPanel = "VideoPanel",
  videoTitleText = "VideoTitleText",
  /** The framehandle name VisionCheckBox has the subframes [o t 23] */
  visionCheckBox = "VisionCheckBox",
  visionHeader = "VisionHeader",
  vSyncCheckBox = "VSyncCheckBox",
  vSyncLabel = "VSyncLabel",
  windowModeLabel = "WindowModeLabel",
  wouldTheRealOptionsTitleTextPleaseStandUp = "WouldTheRealOptionsTitleTextPleaseStandUp",
}

/** These default frames templates can be created with createFrame(..) [BlzCreateFrame] */
export const enum FrameTemplate {
  adBanner = "AdBanner",
  advancedOptionsDisplay = "AdvancedOptionsDisplay",
  advancedOptionsPane = "AdvancedOptionsPane",
  advancedPopupMenuTemplate = "AdvancedPopupMenuTemplate",
  allianceDialog = "AllianceDialog",
  allianceSlot = "AllianceSlot",
  battleNetChatActionMenu = "BattleNetChatActionMenu",
  battleNetChatPanel = "BattleNetChatPanel",
  battleNetChatroom = "BattleNetChatroom",
  battleNetClanInvitation = "BattleNetClanInvitation",
  battleNetClanInviteDialog = "BattleNetClanInviteDialog",
  battleNetClanMateListBox = "BattleNetClanMateListBox",
  battleNetClanPane = "BattleNetClanPane",
  battleNetConnectDialog = "BattleNetConnectDialog",
  battleNetCustomCreatePanel = "BattleNetCustomCreatePanel",
  battleNetCustomFilterDialog = "BattleNetCustomFilterDialog",
  battleNetCustomJoinPanel = "BattleNetCustomJoinPanel",
  battleNetCustomLoadPanel = "BattleNetCustomLoadPanel",
  battleNetFriendsListBox = "BattleNetFriendsListBox",
  battleNetFriendsPane = "BattleNetFriendsPane",
  battleNetHelpDialog = "BattleNetHelpDialog",
  battleNetIconSelectBox = "BattleNetIconSelectBox",
  battleNetIconSelectDialog = "BattleNetIconSelectDialog",
  battleNetMainFrame = "BattleNetMainFrame",
  battleNetMatchmakerPanel = "BattleNetMatchmakerPanel",
  battleNetMatchmakerPendingInviteDialog = "BattleNetMatchmakerPendingInviteDialog",
  battleNetMatchmakerTeamInviteDialog = "BattleNetMatchmakerTeamInviteDialog",
  battleNetNewsBox = "BattleNetNewsBox",
  battleNetPatchDialog = "BattleNetPatchDialog",
  battleNetProfileListBox = "BattleNetProfileListBox",
  battleNetProfileListItem = "BattleNetProfileListItem",
  battleNetProfilePanel = "BattleNetProfilePanel",
  battleNetScheduledGame = "BattleNetScheduledGame",
  battleNetStandardPanel = "BattleNetStandardPanel",
  battleNetStatusBox = "BattleNetStatusBox",
  battleNetTeamInvitation = "BattleNetTeamInvitation",
  battleNetTeamInviteDialog = "BattleNetTeamInviteDialog",
  battleNetTeamPanel = "BattleNetTeamPanel",
  battleNetUserListBox = "BattleNetUserListBox",
  bNetPopupMenuBackdropTemplate = "BNetPopupMenuBackdropTemplate",
  bNetPopupMenuTemplate = "BNetPopupMenuTemplate",
  browserButton = "BrowserButton",
  browserFrame = "BrowserFrame",
  campaignListBox = "CampaignListBox",
  campaignMenu = "CampaignMenu",
  chatDialog = "ChatDialog",
  checkListBox = "CheckListBox",
  cinematicPanel = "CinematicPanel",
  clanButtonBackdropTemplate = "ClanButtonBackdropTemplate",
  clanButtonDisabledBackdropTemplate = "ClanButtonDisabledBackdropTemplate",
  clanButtonDisabledPushedBackdropTemplate = "ClanButtonDisabledPushedBackdropTemplate",
  clanButtonFocusHighlightBackdropTemplate = "ClanButtonFocusHighlightBackdropTemplate",
  clanButtonMouseOverHighlightBackdropTemplate = "ClanButtonMouseOverHighlightBackdropTemplate",
  clanButtonPushedBackdropTemplate = "ClanButtonPushedBackdropTemplate",
  clanButtonTemplate = "ClanButtonTemplate",
  customCampaignMenu = "CustomCampaignMenu",
  debugButton = "DebugButton",
  decoratedMapListBox = "DecoratedMapListBox",
  dialogWar3 = "DialogWar3",
  escMenuBackdrop = "EscMenuBackdrop",
  escMenuMainPanel = "EscMenuMainPanel",
  escMenuMainPanelDialogTextTemplate = "EscMenuMainPanelDialogTextTemplate",
  escMenuOptionsConfirmDialog = "EscMenuOptionsConfirmDialog",
  escMenuOptionsPanel = "EscMenuOptionsPanel",
  escMenuSaveDialogTextTemplate = "EscMenuSaveDialogTextTemplate",
  escMenuSaveGamePanel = "EscMenuSaveGamePanel",
  filterPopupMenuTemplate = "FilterPopupMenuTemplate",
  gameChatroom = "GameChatroom",
  gameResultDialog = "GameResultDialog",
  gameSaveSplashDialog = "GameSaveSplashDialog",
  iconButtonTemplate = "IconButtonTemplate",
  iconicButtonTemplate = "IconicButtonTemplate",
  ladderButtonBackdropTemplate = "LadderButtonBackdropTemplate",
  ladderButtonDisabledBackdropTemplate = "LadderButtonDisabledBackdropTemplate",
  ladderButtonDisabledPushedBackdropTemplate = "LadderButtonDisabledPushedBackdropTemplate",
  ladderButtonFocusHighlightBackdropTemplate = "LadderButtonFocusHighlightBackdropTemplate",
  ladderButtonMouseOverHighlightBackdropTemplate = "LadderButtonMouseOverHighlightBackdropTemplate",
  ladderButtonPushedBackdropTemplate = "LadderButtonPushedBackdropTemplate",
  ladderButtonTemplate = "LadderButtonTemplate",
  ladderNameTextTemplate = "LadderNameTextTemplate",
  leaderboardFrame = "Leaderboard",
  listBoxWar3 = "ListBoxWar3",
  loading = "Loading",
  loadingPlayerSlot = "LoadingPlayerSlot",
  loadSavedGameScreen = "LoadSavedGameScreen",
  localMultiplayerCreate = "LocalMultiplayerCreate",
  localMultiplayerJoin = "LocalMultiplayerJoin",
  localMultiplayerLoad = "LocalMultiplayerLoad",
  logDialog = "LogDialog",
  mainMenuFrame = "MainMenuFrame",
  mapInfoPane = "MapInfoPane",
  mapListBox = "MapListBox",
  mapPreferenceBox = "MapPreferenceBox",
  mapPreferenceBoxBackdrop = "MapPreferenceBoxBackdrop",
  mMPlayerSlot = "MMPlayerSlot",
  movieScreen = "MovieScreen",
  multiboardFrame = "Multiboard",
  optionsConfirmDialog = "OptionsConfirmDialog",
  optionsMenu = "OptionsMenu",
  optionsPopupMenuBackdropTemplate = "OptionsPopupMenuBackdropTemplate",
  optionsPopupMenuTemplate = "OptionsPopupMenuTemplate",
  playerSlot = "PlayerSlot",
  playerSlotPopupMenu = "PlayerSlotPopupMenu",
  questButtonBackdropTemplate = "QuestButtonBackdropTemplate",
  questButtonBaseTemplate = "QuestButtonBaseTemplate",
  questButtonDisabledBackdropTemplate = "QuestButtonDisabledBackdropTemplate",
  questButtonDisabledPushedBackdropTemplate = "QuestButtonDisabledPushedBackdropTemplate",
  questButtonMouseOverHighlightTemplate = "QuestButtonMouseOverHighlightTemplate",
  questButtonPushedBackdropTemplate = "QuestButtonPushedBackdropTemplate",
  questButtonTemplate = "QuestButtonTemplate",
  questCheckBox = "QuestCheckBox",
  questCheckBox2 = "QuestCheckBox2",
  questCheckBox3 = "QuestCheckBox3",
  questConditionListScrollBar = "QuestConditionListScrollBar",
  questDialog = "QuestDialog",
  questItemListItem = "QuestItemListItem",
  questItemListScrollBar = "QuestItemListScrollBar",
  questListItem = "QuestListItem",
  questMainListScrollBar = "QuestMainListScrollBar",
  quickReplayConfirmDialog = "QuickReplayConfirmDialog",
  quickReplayDialog = "QuickReplayDialog",
  replayButton = "ReplayButton",
  saveReplayPanel = "SaveReplayPanel",
  scoreScreen4ColumnButtonTemplate = "ScoreScreen4ColumnButtonTemplate",
  scoreScreen5ColumnButtonTemplate = "ScoreScreen5ColumnButtonTemplate",
  scoreScreenBottomButtonTemplate = "ScoreScreenBottomButtonTemplate",
  scoreScreenBottomCheckButtonTemplate = "ScoreScreenBottomCheckButtonTemplate",
  scoreScreenButtonBackdropTemplate = "ScoreScreenButtonBackdropTemplate",
  scoreScreenColumnHeaderTemplate = "ScoreScreenColumnHeaderTemplate",
  scoreScreenFrame = "ScoreScreenFrame",
  scoreScreenTabButtonTemplate = "ScoreScreenTabButtonTemplate",
  scoreScreenTabTextSelectedTemplate = "ScoreScreenTabTextSelectedTemplate",
  scoreScreenTabTextTemplate = "ScoreScreenTabTextTemplate",
  scriptDialog = "ScriptDialog",
  scriptDialogButton = "ScriptDialogButton",
  singlePlayerMenu = "SinglePlayerMenu",
  skirmish = "Skirmish",
  skirmishPopupMenuBackdropTemplate = "SkirmishPopupMenuBackdropTemplate",
  skirmishPopupMenuTemplate = "SkirmishPopupMenuTemplate",
  suspendDialog = "SuspendDialog",
  suspendPlayerSlot = "SuspendPlayerSlot",
  teamColorMenu = "TeamColorMenu",
  teamLabelTextTemplate = "TeamLabelTextTemplate",
  teamLadderRankValueTextTemplate = "TeamLadderRankValueTextTemplate",
  teamMemberPopupMenu = "TeamMemberPopupMenu",
  teamPopupMenuBackdropTemplate = "TeamPopupMenuBackdropTemplate",
  teamPopupMenuTemplate = "TeamPopupMenuTemplate",
  teamSetup = "TeamSetup",
  teamValueTextTemplate = "TeamValueTextTemplate",
  timerDialog = "TimerDialog",
  unresponsiveDialog = "UnresponsiveDialog",
  userDataMigrationDialog = "UserDataMigrationDialog",
  viewReplayScreen = "ViewReplayScreen",
}
