export const DamageType = {
	UNKNOWN: DAMAGE_TYPE_UNKNOWN,
	NORMAL: DAMAGE_TYPE_NORMAL,
	ENHANCED: DAMAGE_TYPE_ENHANCED,
	FIRE: DAMAGE_TYPE_FIRE,
	COLD: DAMAGE_TYPE_COLD,
	LIGHTNING: DAMAGE_TYPE_LIGHTNING,
	POISON: DAMAGE_TYPE_POISON,
	DISEASE: DAMAGE_TYPE_DISEASE,
	DIVINE: DAMAGE_TYPE_DIVINE,
	MAGIC: DAMAGE_TYPE_MAGIC,
	SONIC: DAMAGE_TYPE_SONIC,
	ACID: DAMAGE_TYPE_ACID,
	FORCE: DAMAGE_TYPE_FORCE,
	DEATH: DAMAGE_TYPE_DEATH,
	MIND: DAMAGE_TYPE_MIND,
	PLANT: DAMAGE_TYPE_PLANT,
	DEFENSIVE: DAMAGE_TYPE_DEFENSIVE,
	DEMOLITION: DAMAGE_TYPE_DEMOLITION,
	SLOW_POISON: DAMAGE_TYPE_SLOW_POISON,
	SPIRIT_LINK: DAMAGE_TYPE_SPIRIT_LINK,
	SHADOW_STRIKE: DAMAGE_TYPE_SHADOW_STRIKE,
	UNIVERSAL: DAMAGE_TYPE_UNIVERSAL
}

export const AttackType = {
	NORMAL: ATTACK_TYPE_NORMAL,
	MELEE: ATTACK_TYPE_MELEE,
	PIERCE: ATTACK_TYPE_PIERCE,
	SIEGE: ATTACK_TYPE_SIEGE,
	MAGIC: ATTACK_TYPE_MAGIC,
	CHAOS: ATTACK_TYPE_CHAOS,
	HERO: ATTACK_TYPE_HERO
}

export const WeaponType = {
	METAL_LIGHT_CHOP: WEAPON_TYPE_METAL_LIGHT_CHOP,
	METAL_MEDIUM_CHOP: WEAPON_TYPE_METAL_MEDIUM_CHOP,
	METAL_HEAVY_CHOP: WEAPON_TYPE_METAL_HEAVY_CHOP,
	METAL_LIGHT_SLICE: WEAPON_TYPE_METAL_LIGHT_SLICE,
	METAL_MEDIUM_SLICE: WEAPON_TYPE_METAL_MEDIUM_SLICE,
	METAL_HEAVY_SLICE: WEAPON_TYPE_METAL_HEAVY_SLICE,
	METAL_MEDIUM_BASH: WEAPON_TYPE_METAL_MEDIUM_BASH,
	METAL_HEAVY_BASH: WEAPON_TYPE_METAL_HEAVY_BASH,
	METAL_MEDIUM_STAB: WEAPON_TYPE_METAL_MEDIUM_STAB,
	METAL_HEAVY_STAB: WEAPON_TYPE_METAL_HEAVY_STAB,
	WOOD_LIGHT_SLICE: WEAPON_TYPE_WOOD_LIGHT_SLICE,
	WOOD_MEDIUM_SLICE: WEAPON_TYPE_WOOD_MEDIUM_SLICE,
	WOOD_HEAVY_SLICE: WEAPON_TYPE_WOOD_HEAVY_SLICE,
	WOOD_LIGHT_BASH: WEAPON_TYPE_WOOD_LIGHT_BASH,
	WOOD_MEDIUM_BASH: WEAPON_TYPE_WOOD_MEDIUM_BASH,
	WOOD_HEAVY_BASH: WEAPON_TYPE_WOOD_HEAVY_BASH,
	WOOD_LIGHT_STAB: WEAPON_TYPE_WOOD_LIGHT_STAB,
	WOOD_MEDIUM_STAB: WEAPON_TYPE_WOOD_MEDIUM_STAB,
	CLAW_LIGHT_SLICE: WEAPON_TYPE_CLAW_LIGHT_SLICE,
	CLAW_MEDIUM_SLICE: WEAPON_TYPE_CLAW_MEDIUM_SLICE,
	CLAW_HEAVY_SLICE: WEAPON_TYPE_CLAW_HEAVY_SLICE,
	AXE_MEDIUM_CHOP: WEAPON_TYPE_AXE_MEDIUM_CHOP,
	ROCK_HEAVY_BASH: WEAPON_TYPE_ROCK_HEAVY_BASH
}

export const PathingType = {
	ANY: PATHING_TYPE_ANY,
	WALKABILITY: PATHING_TYPE_WALKABILITY,
	FLYABILITY: PATHING_TYPE_FLYABILITY,
	BUILDABILITY: PATHING_TYPE_BUILDABILITY,
	PEONHARVESTPATHING: PATHING_TYPE_PEONHARVESTPATHING,
	BLIGHTPATHING: PATHING_TYPE_BLIGHTPATHING,
	FLOATABILITY: PATHING_TYPE_FLOATABILITY,
	AMPHIBIOUSPATHING: PATHING_TYPE_AMPHIBIOUSPATHING
}

export const PlayerState = {
	GAME_RESULT: PLAYER_STATE_GAME_RESULT,
	RESOURCE_GOLD: PLAYER_STATE_RESOURCE_GOLD,
	RESOURCE_LUMBER: PLAYER_STATE_RESOURCE_LUMBER,
	RESOURCE_HERO_TOKENS: PLAYER_STATE_RESOURCE_HERO_TOKENS,
	RESOURCE_FOOD_CAP: PLAYER_STATE_RESOURCE_FOOD_CAP,
	RESOURCE_FOOD_USED: PLAYER_STATE_RESOURCE_FOOD_USED,
	FOOD_CAP_CEILING: PLAYER_STATE_FOOD_CAP_CEILING,
	GIVES_BOUNTY: PLAYER_STATE_GIVES_BOUNTY,
	ALLIED_VICTORY: PLAYER_STATE_ALLIED_VICTORY,
	PLACED: PLAYER_STATE_PLACED,
	OBSERVER_ON_DEATH: PLAYER_STATE_OBSERVER_ON_DEATH,
	OBSERVER: PLAYER_STATE_OBSERVER,
	UNFOLLOWABLE: PLAYER_STATE_UNFOLLOWABLE,
	GOLD_UPKEEP_RATE: PLAYER_STATE_GOLD_UPKEEP_RATE,
	LUMBER_UPKEEP_RATE: PLAYER_STATE_LUMBER_UPKEEP_RATE,
	GOLD_GATHERED: PLAYER_STATE_GOLD_GATHERED,
	LUMBER_GATHERED: PLAYER_STATE_LUMBER_GATHERED,
	NO_CREEP_SLEEP: PLAYER_STATE_NO_CREEP_SLEEP
}

export const DefenseType = {
	LIGHT: DEFENSE_TYPE_LIGHT,
	MEDIUM: DEFENSE_TYPE_MEDIUM,
	LARGE: DEFENSE_TYPE_LARGE,
	FORT: DEFENSE_TYPE_FORT,
	NORMAL: DEFENSE_TYPE_NORMAL,
	HERO: DEFENSE_TYPE_HERO,
	DIVINE: DEFENSE_TYPE_DIVINE,
	NONE: DEFENSE_TYPE_NONE
}
